JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Depot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Trade Customer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/GeoTagging_Distance__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Distance__c</fullName>
        <label>Distance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>GeoTagging Distance</label>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_with_JSW_ELP_program__c</fullName>
        <label>Registered with JSW ELP program?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <recordTypes>
        <fullName>PJP</fullName>
        <active>true</active>
        <label>PJP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distance__c</fullName>
        <formula>DISTANCE( Location__c ,  Visited_Location__c , &apos;mi&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_with_JSW_ELP_program__c</fullName>
        <formula>TEXT( Influencer__r.Registered_with_JSW_ELP_program__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Registered with JSW ELP program?</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <label>Depot</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/AutoCheckInController_test.cls
@istest
public class AutoCheckInController_test {
public static testmethod void AutoCheckInController_method(){
account act=new account();
act.name='testact';
act.account_type__c='depot';
insert act;

Month_Plan__c pjp = new Month_Plan__c();
insert pjp;

Day_Plan__c dp = new Day_Plan__c();
dp.Month_Plan__c = pjp.id;
insert dp;

Visit__c vst=new Visit__c();
vst.name='test';
vst.account__c=act.id;
vst.Day_Plan__c = dp.id;
insert vst;
ApexPages.StandardController sc = new ApexPages.StandardController(vst); 
AutoCheckInController  ACC=new AutoCheckInController (sc);
}

public static testmethod void AutoCheckInController_method1(){

GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
        gtd.Name = 'Geo Tagging';
        gtd.Distance__c = 1;
        insert gtd;

account act=new account();
act.name='testact';
act.account_type__c='depot';
insert act;

Month_Plan__c pjp = new Month_Plan__c();
insert pjp;

Day_Plan__c dp = new Day_Plan__c();
dp.Month_Plan__c = pjp.id;
insert dp;

Visit__c vst=new Visit__c();
vst.name='test';
vst.account__c=act.id;
vst.Day_Plan__c = dp.id;
insert vst;
AutoCheckInController.autoCheckIn('17','15','17','15', vst.Id);

}

public static testmethod void AutoCheckInController_method2(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

account act=new account();
act.name='testact';
act.account_type__c='depot';
insert act;

AutoCheckInController.autoCheckInAcc('17','15','17','15', act.Id);
}

public static testmethod void AutoCheckInController_method3(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

lead ld=new lead();
ld.lastname='testlead';
ld.Company='BT';
ld.status='NEW';
insert ld;

AutoCheckInController.autoCheckInLd('17','15','17','15', ld.Id);
}

public static testmethod void AutoCheckInController_method4(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

Project_Site__c PS=new Project_Site__c();
ps.Name='testprojectsite';
insert ps;

AutoCheckInController.autoCheckInPS('17','15','17','15', ps.Id);
}

public static testmethod void AutoCheckInController_method5(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

Influencer__c inf=new Influencer__c();
inf.Name='testinf';
inf.Registered_with_JSW_ELP_program__c = 'Yes';
insert inf;

AutoCheckInController.autoCheckInInfnc('17','15','17','15', inf.Id);
}

public static testmethod void AutoCheckInController_method6(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

Event__c Evnt=new event__c();
evnt.name='test evnt';
insert evnt;

AutoCheckInController.autoCheckInEvnt('17','15','17','15', evnt.Id);
}

public static testmethod void AutoCheckInController_method7(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

Business_Partner__c BP=new Business_Partner__c();
BP.name='test Buss';
insert BP;

AutoCheckInController.autoCheckInBP('17','15','17','15', BP.Id);
}

public static testmethod void AutoCheckInController_method8(){
/*GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;*/

account act=new account();
act.name='testact';
act.account_type__c='depot';
insert act;

Month_Plan__c pjp = new Month_Plan__c();
insert pjp;

Day_Plan__c dp = new Day_Plan__c();
dp.Month_Plan__c = pjp.id;
insert dp;

Visit__c vst=new Visit__c();
vst.name='test';
vst.account__c=act.id;
vst.Day_Plan__c = dp.id;
insert vst;
AutoCheckInController.autoCheckInVisit('17','15',vst.Id);
}

public static testmethod void AutoCheckInController_method9(){
GeoTagging_Distance__c gtd = new GeoTagging_Distance__c();
gtd.Name = 'Geo Tagging';
gtd.Distance__c = 1;
insert gtd;

account act=new account();
act.name='testact';
act.account_type__c='depot';
insert act;

Month_Plan__c pjp = new Month_Plan__c();
insert pjp;

Day_Plan__c dp = new Day_Plan__c();
dp.Month_Plan__c = pjp.id;
insert dp;

Visit__c vst=new Visit__c();
vst.name='test';
vst.account__c=act.id;
vst.Day_Plan__c = dp.id;
insert vst;
AutoCheckInController.autoCheckdistance('17','15','17', vst.Id);
}
}