JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week Plan</label>
        <referenceTo>Week_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_with_JSW_ELP_program__c</fullName>
        <label>Registered with JSW ELP program?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Month_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSW_Bag_Visibility__c</fullName>
        <label>JSW Bag Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registered_with_JSW_ELP_program__c</fullName>
        <formula>TEXT( Influencer__r.Registered_with_JSW_ELP_program__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Registered with JSW ELP program?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Week_Plan_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Week Plan Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Influencer</fullName>
        <active>true</active>
        <label>Influencer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Week_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Week Plan</relationshipLabel>
        <relationshipName>Week_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Week_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Week Plan</label>
    <nameField>
        <label>Week Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Week Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/ApprovalSubmission_test.cls
@istest
public class ApprovalSubmission_test{
    public static testmethod void ApprovalSubmission_method(){
        Set<String> dpids = new Set<String>();
        List<Visit__c> vstlist=new List<Visit__c>();
        User u = [select firstname from user where id=:userinfo.getuserid()];
        Account ac=new Account();
        ac.name='Mohan';
        insert ac;
        
        Lead ld=new Lead(Company = 'JohnMiller', LastName = 'Mike', Status = 'Open');
        insert ld;
        Project_Site__c ps=new Project_Site__c();
        insert ps;
        District__c ds=new District__c();
        insert ds;
        Influencer__c ifu=new Influencer__c();
        ifu.Name = 'Sample Influencer';
        ifu.Registered_with_JSW_ELP_program__c = 'Yes';
        insert ifu;
        Business_Partner__c bp=new Business_Partner__c();
        insert bp;
        Month_Plan__c MPC=new Month_Plan__c();
        MPC.Name='plan';
        MPC.Start_Date__c=system.today()-30;
        MPC.End_Date__c=system.today();
        MPC.User__c=u.id;
        MPC.Year__c ='2016';
        insert MPC;
        
        Week_Plan__c WP=new Week_Plan__c();
        WP.name='test';
        WP.Start_Date__c=system.today();
        WP.End_Date__c=system.today()+7;
        WP.Month_Plan__c=MPC.id;
        Wp.Submitted_for_Approval__c =true;
        WP.Status__c='New Request';
        insert WP;
        
        Week_Plan__c WP2=new Week_Plan__c();
        WP2.name='test';
        WP2.Start_Date__c=system.today();
        WP2.End_Date__c=system.today()+7;
        WP2.Month_Plan__c=MPC.id;
        Wp2.Submitted_for_Approval__c =False;
        WP2.Status__c='Submitted';
        insert wp2;
        WP2.Status__c='Approved';
        update wp2;
        
        Day_Plan__c dp=new Day_Plan__c();
        dp.Name='day';
        dp.Week_Plan__c=wp2.id;    
        insert dp;
        dp.Date__c=date.today();
        update dp;    
        dpids.add(dp.id);
        
        Visit__c vc=new Visit__c();
        vc.Account__c=ac.id;
        vc.Week_Plan_Submitted__c=true;
        vc.Day_Plan__c=dp.id;
        vc.Address__c='sjfksjdgksdjgs';
        vc.Check_In__c='df';
        vc.JSW_Bag_Visibility__c='Good';
        insert vc;
        vstlist.add(vc);
        
        Visit__c vc1=new Visit__c();
        vc1.Lead__c=ld.id;
        vc1.Week_Plan_Submitted__c=true;
        vc1.Day_Plan__c=dp.id;
        vc1.Address__c='sjfksjdgksdjgs';
        vc1.Check_In__c='df';
        vc1.JSW_Bag_Visibility__c='Good';
        insert vc1;
        
        Visit__c vc2=new Visit__c();
        vc2.Project_Site__c=ps.id;
        vc2.Week_Plan_Submitted__c=true;
        vc2.Day_Plan__c=dp.id;
        vc2.Address__c='sjfksjdgksdjgs';
        vc2.Check_In__c='df';
        vc2.JSW_Bag_Visibility__c='Good';
        insert vc2;
        
        Visit__c vc3=new Visit__c();
        vc3.Territory__c=ds.id;
        vc3.Week_Plan_Submitted__c=true;
        vc3.Day_Plan__c=dp.id;
        vc3.Address__c='sjfksjdgksdjgs';
        vc3.Check_In__c='df';
        vc.JSW_Bag_Visibility__c='Good';
        insert vc3;
        
        Visit__c vc4=new Visit__c();
        vc4.Influencer__c=ifu.id;
        vc4.Week_Plan_Submitted__c=true;
        vc4.Day_Plan__c=dp.id;
        vc4.Address__c='sjfksjdgksdjgs';
        vc4.Check_In__c='df';
        vc4.JSW_Bag_Visibility__c='Good';
        insert vc4;
        
        Visit__c vc5=new Visit__c();
        vc5.Business_Partner__c=bp.id;
        vc5.Week_Plan_Submitted__c=true;
        vc5.Day_Plan__c=dp.id;
        vc5.Address__c='sjfksjdgksdjgs';
        vc5.Check_In__c='df';
        vc5.JSW_Bag_Visibility__c='Good';
        insert vc5;
        apexpages.currentpage().getparameters().put('id', MPC.id);
        ApprovalSubmission ASB=new ApprovalSubmission();
        pagereference pg= new pagereference('/a04/o');
        test.setCurrentPage(pg);
        ASB.pjptab();
        
        ASB.submitforapproval();
    }
}