JSW Devsb/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Trade</fullName>
        <active>true</active>
        <label>Trade</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Actuals</label>
    <nameField>
        <displayFormat>ACTL-{0000000000}</displayFormat>
        <label>Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/ASM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zonal_Head__c</fullName>
        <label>State Head</label>
        <referenceTo>Zonal_Head__c</referenceTo>
        <relationshipLabel>ASM Targets</relationshipLabel>
        <relationshipName>ASM_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ASM Target</label>
    <nameField>
        <displayFormat>ASM-{0000}</displayFormat>
        <label>ASM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Dealer_Target__c.object
<CustomObject>
    <fields>
        <fullName>ASM_Target__c</fullName>
        <label>ASM Target</label>
        <referenceTo>ASM_Targets__c</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Dealer Target</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Monthly Target  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Dealer Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Dealer_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Dealer Target</label>
        <referenceTo>Monthly_Dealer_Target__c</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Targets</label>
    <nameField>
        <label>Monthly Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

JSW Devsb/src/objects/State_Head__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>State_Head</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zonal Head</label>
    <nameField>
        <displayFormat>ZH-{00000}</displayFormat>
        <label>Zonal Head Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zonal Head</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Zonal_Head__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Head__c</fullName>
        <label>State Head</label>
        <referenceTo>State_Head__c</referenceTo>
        <relationshipName>Zonal_Head</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State Head</label>
    <nameField>
        <displayFormat>SH-{00000}</displayFormat>
        <label>State Head Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Head</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/PlanDetailsTest.cls
@isTest
public class PlanDetailsTest {
    public static testMethod void PlanDetailsTestMethod(){
        date myDate = date.today();
        string dt=string.valueOf(myDate);
        string recid=ApexPages.CurrentPage().getparameters().get('id');
        string usrid=userinfo.getUserName();
        id recid1=[select Id,Name from RecordType where RecordType.Name='Trade' and SobjectType='Account'].id;
        account ac = new account(name = 'Dealer Mohan',RecordTypeId=recid1);
        insert ac;
        Lead ld = new Lead(lastname = 'test lead',company='test');
        insert ld;
        Product2 prd = new Product2(name = 'test Product',group__c='psc');
        insert prd;
        Brand__c br=new Brand__c(Name='brand');
        insert br;
        State_Head__c st=new State_Head__c(	Date__c=myDate);
        insert st;
        Zonal_Head__c zh=new Zonal_Head__c(	Date__c=myDate,State_Head__c=st.Id);
        insert zh;
        ASM_Targets__c ast=new ASM_Targets__c(date__C=myDate,Zonal_Head__c=zh.id);
        insert ast;
        PlanDetails.getRecord(recid);
        PlanDetails.getChdRecord(recid);
        PlanDetails.getAllasms();
        PlanDetails.getAllAccounts();
        PlanDetails.getAccounts(dt,prd.group__c);
        PlanDetails.getUserName();
        PlanDetails.getAllProducts();
        PlanDetails.getmtso(dt,prd.group__c,usrid);
        PlanDetails.getAllters('Test Mohan');
        PlanDetails.getAlldists();
        PlanDetails.getNT(dt,prd.group__c);
        Monthly_Dealer_Target__c mdt=new Monthly_Dealer_Target__c();
        mdt.Account__c=ac.id;
        mdt.Actuals__c=258.00;
        mdt.ASM_Target__c=ast.id;
        mdt.Quantity__c=45.00;
        wrapperlightning wrl=new wrapperlightning();
        wrl.dealer='Dealer Mohan';
        wrl.dealerid='34567';
        wrl.LYSMactual=22;
        wrl.dlractual=45.00;
        wrl.dlrqty=45;
        wrl.dlrtrget=545646;
        list<wrapperlightning> wrplst = new list<wrapperlightning>();
        wrplst.add(wrl);
        string newdlrtrgt = JSON.serialize(wrplst);
        PlanDetails.mnthtargts(newdlrtrgt,mdt,dt);
        Monthly_Targets__c mt = new Monthly_Targets__c();
        account acc=[select id,name from account where name=:wrl.dealer limit 1];
           mt.Dealer__c = acc.id;
            insert mt;
    }
}