JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Account__r.Name + Lead__r.FirstName + Lead__r.MiddleName + Lead__r.LastName +  TEXT(Event__r.Type_of_Meet__c) + Area__r.Name +  Business_Partner__r.Name +  Project_Site__r.Name +  Influencer__r.Name +  Territory__r.Name  + Depot__r.Name +
IF( AND(  OR( Account__c == null, Account__c == &apos;&apos;)  ,
          OR( Lead__c == null, Lead__c == &apos;&apos;)  ,
          OR( Event__c == null, Event__c == &apos;&apos;)  ,
          OR( Area__c == null, Area__c == &apos;&apos;)  ,
          OR( Business_Partner__c == null, Business_Partner__c == &apos;&apos;)  ,
          OR( Project_Site__c == null, Project_Site__c == &apos;&apos;)  ,
          OR( Influencer__c == null, Influencer__c == &apos;&apos;) ,
          OR( Territory__c == null, Territory__c == &apos;&apos;) ),
               General_Visit_Type__c , &apos;&apos;)</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/RouteMapExtension.cls
global class RouteMapExtension {

    public RouteMapExtension(ApexPages.StandardController controller) {

    }
    
    @RemoteAction
    // Find warehouses nearest a geolocation
    global static List<Day_Plan__c> getDetails(String strId) {

        String queryString =
        'SELECT Id, Location__Latitude__s,Account__r.Name,Lead__r.Name,Name__c,Location__Longitude__s,Address__c ' +
           'FROM Visit__c WHERE Day_Plan__c  ='+ '\'' + strId + '\' Order By Planned_Date__c ASC';
                     
        System.debug('queryString = ' +queryString);
      //  List<Task> listt=database.Query(queryString);
        // Run and return the query results
        system.debug('*******List'+database.Query(queryString));
        return(database.Query(queryString));
    }


  @RemoteAction
    // Find warehouses nearest a geolocation
    global static List<Day_Plan__c> getDetailsBasedOnCreatedDate(String strId) {

        String queryString =
        'SELECT Id, Location__Latitude__s,Account__r.Name,Lead__r.Name,Name__c,Location__Longitude__s,Address__c ' +
           'FROM Visit__c WHERE   Day_Plan__c='+ '\'' + strId + '\' Order By Check_In__c ASC';
                     
        System.debug('queryString = ' +queryString);
        // Run and return the query results
        return database.Query(queryString);
    }


}