JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Customer_ShipToParty__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CustomersShipToPartys</relationshipLabel>
        <relationshipName>CustomersShipToPartys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <label>Ship To Party</label>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>CustomersShipToPartys</relationshipLabel>
        <relationshipName>CustomersShipToPartys</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer&amp;ShipToParty</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Customer&amp;ShipToParty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CustomersShipToPartys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Orders</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Ship_To_Party__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To Party</relationshipLabel>
        <relationshipName>Ship_To_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Code__c</fullName>
        <label>Sold to Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ship To Party</label>
    <nameField>
        <label>Ship To Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/AccountPopulateAndMultiPicklistValueTest.cls
@isTest
public Class AccountPopulateAndMultiPicklistValueTest{
    
    public static testMethod  void updateAccount()
    {
     list<String>soids=new list<String>();
    
   User u = [select firstname from user where id=:userinfo.getuserid()];
    
     Ship_To_Party__c sh2=new Ship_To_Party__c();
     sh2.Sold_to_Code__c='abc123';
     sh2.External_Id__c='xyz1';
     sh2.ownerid=u.id;
     sh2.Distribution_Channel__c='10';
     sh2.Division__c='50';
     insert sh2;
    
     account ac=new account();
     ac.Customer_Code__c='abc123';
     ac.External_Id__c='abc1231050';
     ac.ownerid=u.id;
     ac.Distribution_Channel__c='10';
     ac.Division__c='50';
     ac.name='testing';
     insert ac;
     
     List<Order__c> orderList=new List<Order__c>();
     Ship_To_Party__c sh=new Ship_To_Party__c();
     sh.Sold_to_Code__c=ac.Customer_Code__c;
     sh.External_Id__c='xyz12';
     sh.ownerid=u.id;
     sh.Distribution_Channel__c='10';
     sh.Division__c='50';
     insert sh;
     
     
     
     Customer_ShipToParty__c sh1=new Customer_ShipToParty__c();
     sh1.Account__c=ac.id;
     sh1.Ship_To_Party__c=sh.id;
     insert sh1;
     
    
    
    
      
    }
}