JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Carpet_Area_Sqft__c</fullName>
        <label>Carpet Area (Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Available__c</fullName>
        <label>Credit Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Last_Updated_Formula__c</fullName>
        <formula>Credit_Last_Updated__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Credit_Limit__c</fullName>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Outstanding__c</fullName>
        <label>Credit Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Descrption__c</fullName>
        <formula>CASE (Distribution_Channel__c,
&quot;10&quot;, &quot;Trade&quot; ,
&quot;20&quot;, &quot;Non-Trade&quot;, 
&quot;30&quot;, &quot;Stock Transfer&quot;, 
&quot;40&quot;, &quot;Third Party&quot;,
&quot;50&quot;, &quot;SEZ&quot;,
&quot;60&quot;, &quot;Consignment Transfer&quot;,
&quot;70&quot;, &quot;Inter Unit Transfer&quot;,
&quot;80&quot;, &quot;Export Sales&quot;,
&quot;none&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distribution Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DivistionDesc__c</fullName>
        <formula>CASE( TEXT(Division__c),&quot;50&quot;, &quot;Cement&quot;,&quot;51&quot;, &quot;Clinker&quot;,&quot;52&quot;, &quot;GGBS&quot;,&quot;53&quot;, &quot;Trading&quot;,&quot;54&quot;, &quot;MISC&quot; ,null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DivistionDesc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_Credit_Period__c</fullName>
        <label>Eligible Credit Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ideal_Storage_Capacity_MT__c</fullName>
        <label>Ideal Storage Capacity (MT)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Overdue_Amount__c</fullName>
        <label>Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packing_Type__c</fullName>
        <label>Packing Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSD__c</fullName>
        <label>SSD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_text__c</fullName>
        <label>Sales Office text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X008_015__c</fullName>
        <label>008 - 015</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X016_030__c</fullName>
        <label>016 - 030</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X031_045__c</fullName>
        <label>031 - 045</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X046_060__c</fullName>
        <label>046 - 060</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X061_090__c</fullName>
        <label>061 - 090</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X091_180__c</fullName>
        <label>091 - 180</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X0_007__c</fullName>
        <label>0 - 007</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X181_365__c</fullName>
        <label>181 - 365</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X365__c</fullName>
        <label>&gt; 365</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/AccountSyncservice.cls
@RestResource(urlMapping='/AccountSync/*')
global with sharing class AccountSyncservice{

  @HttpPost
    global static List<Account> doPost(String userId,DateTime dte) {
        List<Account> accountList = new List<Account>();
        String curRole = '';
        User mobusr = [select id,name,userroleid,userrole.name,Profile.Name from user where id =: userId];
        curRole = mobusr.UserRole.Name.split(' ')[0];
        curRole = curRole+'%';
        List<User> allusrs = [select id,name from User where UserRole.Name like : curRole];
        Set<Id> userset = new Set<Id>();
        for(User usr : allusrs){
            userset.add(usr.id);
        }
        accountList = [SELECT Id,Name, Company_Code__c,DivistionDesc__c,Distribution_Channel_Descrption__c,recordtype.name,Sales_Office__c,
                       Sales_Office_text__c,ownerId,owner.name,Credit_Limit__c,SSD__c,Eligible_Credit_Period__c,Credit_Available__c,Overdue_Amount__c,
                       Credit_Last_Updated_Formula__c,Credit_Outstanding__c,Location__c,X365__c,X0_007__c,X008_015__c,X016_030__c,
                       X031_045__c,X046_060__c,X061_090__c,X091_180__c,X181_365__c,Packing_Type__c,Carpet_Area_Sqft__c,Ideal_Storage_Capacity_MT__c
                        FROM Account where Ownerid in:userset and LastModifiedDate >=: dte];        
        
        return accountList;
    }
 
}