JSW Devsb/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <label>Depot</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Accounts__c</fullName>
        <label>Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Partners__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Business Partners</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Depots__c</fullName>
        <label>Depots</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Influencers__c</fullName>
        <label>Influencers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Leads__c</fullName>
        <label>Leads</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_planned_visits__c</fullName>
        <label>Number of planned visits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Present__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Present</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sites__c</fullName>
        <label>Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Working Day</label>
        <type>Checkbox</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Promoter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middleman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF( Account__c != null, &apos;Account&apos;, &apos;&apos;) + 
 IF( Depot__c != null, &apos;Depot&apos;, &apos;&apos;) + 
 IF( Area__c != null , &apos;Area&apos;, &apos;&apos;) +
 IF( Business_Partner__c != null , &apos;Business Partner&apos;, &apos;&apos;) +
 IF( Customer_Type__c != null , &apos;Customer Type&apos;, &apos;&apos;) +
 IF( Event__c != null , &apos;Event&apos;, &apos;&apos;) +
 IF( Influencer__c != null , &apos;Influencer&apos;, &apos;&apos;) +
 IF( Lead__c != null , &apos;Lead&apos;, &apos;&apos;) +
 IF( Project_Site__c != null , &apos;Project Site&apos;, &apos;&apos;) +
 IF( Territory__c != null , &apos;Territory&apos;, &apos;&apos;) +
 IF( General_Visit__c = true , &apos;General&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit_Checked_In__c</fullName>
        <formula>Check_In__c   &lt;&gt; Null</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Visit Checked In</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Depot</fullName>
        <active>true</active>
        <label>Depot</label>
    </recordTypes>
    <recordTypes>
        <fullName>Influencer</fullName>
        <active>true</active>
        <label>Influencer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Working_Days__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Working Day</label>
    <nameField>
        <label>Working Days Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Working Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchDPReport.cls
global class batchDPReport implements Database.Batchable<sObject> {
    
    String qry {get; set;}
    Set<Date> dateset {get; set;}
    List<Working_Days__c> wrklist {get; set;}
    Map<Date,Boolean> wrkmap {get; set;}
    Map<String,List<Visit__c>> vstmap {get; set;}
    
    public batchDPReport(){
        qry = 'select id,name,Date__c,Number_of_planned_visits__c,Present__c,Accounts__c,Depots__c,Business_Partners__c,Leads__c,Sites__c,Influencers__c,Working_Day__c,(select id,name,Type__c,Visit_Checked_In__c,Planned__c from Visits__r) from Day_Plan__c where Processed__c = false';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(qry);
    }
    
    global void execute(Database.BatchableContext BC, List<Day_Plan__c> dplist) {
        dateset = new Set<Date>();
        wrkmap = new Map<Date,Boolean>();
        vstmap = new Map<String,List<Visit__c>>();
        for(Day_Plan__c dp : dplist){
            dateset.add(dp.Date__c);
            vstmap.put(dp.id,dp.Visits__r);
        }
        wrklist = [select id,name,Date__c from Working_Days__c where Date__c in: dateset];
        for(Working_Days__c wrk : wrklist){
            wrkmap.put(wrk.Date__c,true);
        }
        for(Day_Plan__c dp : dplist){
            if(wrkmap.containsKey(dp.Date__c)){
                if(wrkmap.get(dp.Date__c) == true){
                    dp.Working_Day__c = true;
                } else {
                    dp.Working_Day__c = false;
                }
            }
            for(Visit__c vst : dp.Visits__r){
                if(vst.Visit_Checked_In__c == true){
                    dp.Present__c = true;
                }
                if(vst.Planned__c == true){
                    if(dp.Number_of_planned_visits__c != null)
                    dp.Number_of_planned_visits__c = dp.Number_of_planned_visits__c + 1;
                    else
                    dp.Number_of_planned_visits__c = 0;
                }
                if(vst.Type__c == 'Account'){
                    if(dp.Accounts__c != null)
                    dp.Accounts__c = dp.Accounts__c + 1;
                    else
                    dp.Accounts__c = 0;
                } else if(vst.Type__c == 'Business Partner'){
                    if(dp.Business_Partners__c != null)
                    dp.Business_Partners__c = dp.Business_Partners__c + 1;
                    else
                    dp.Business_Partners__c = 0;
                } else if(vst.Type__c == 'Depot'){
                    if(dp.Depots__c != null)
                    dp.Depots__c = dp.Depots__c + 1;
                    else
                    dp.Depots__c = 0;
                } else if(vst.Type__c == 'Lead'){
                    if(dp.Leads__c != null)
                    dp.Leads__c = dp.Leads__c + 1;
                    else
                    dp.Leads__c = 0;
                } else if(vst.Type__c == 'Project Site'){
                    if(dp.Sites__c != null)
                    dp.Sites__c = dp.Sites__c + 1;
                    else
                    dp.Sites__c = 0;
                } else if(vst.Type__c == 'Influencer'){
                    if(dp.Influencers__c != null)
                    dp.Influencers__c = dp.Influencers__c + 1;
                    else
                    dp.Influencers__c = 0;
                } 
                dp.Processed__c = true;
            }
        }
        update dplist;
    }
    
    global void finish(Database.BatchableContext BC) {
    
    }
}