JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Market_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Details of Competitor Activities</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSW_Average_Monthly_Volume__c</fullName>
        <label>JSW Average Monthly Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JSW_BP_Min__c</fullName>
        <label>Billing Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JSW_RSP_Max__c</fullName>
        <label>JSW RSP Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JSW_RSP_Min__c</fullName>
        <label>Retail Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JSW_WSP_Max__c</fullName>
        <label>JSW WSP Max</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JSW_WSP_Min__c</fullName>
        <label>Wholesale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sites__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Sites</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Market Information</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Information</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Market Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Information JSW</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Marketing_Info__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BP_Min__c</fullName>
        <label>BP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Information</label>
        <referenceTo>Market_Information__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSP_Max__c</fullName>
        <label>RSP Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSP_Min__c</fullName>
        <label>RSP Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sites__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Sites</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSP_Max__c</fullName>
        <label>WSP Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WSP_Min__c</fullName>
        <label>WSP Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price Reading</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Marketing Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Reading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concreel HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC &amp; CHD</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Information</label>
        <referenceTo>Market_Information__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Composite cement</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/mktInfo.cls
public class mktInfo 
{
    @AuraEnabled
    public static list<Market_Information__c> getRecord(string id1)
    {
        return [select id,name,Account__r.Name,Visit__r.Name,Lead__r.Name,Business_Partner__r.Name,Influencer__r.Name,Sites__r.Name,Product__r.Group__c,Comments__c,JSW_BP_Min__c,JSW_WSP_Min__c,JSW_WSP_Max__c,JSW_RSP_Min__c,JSW_RSP_Max__c,JSW_Average_Monthly_Volume__c from Market_Information__c where id=:id1];
    }
    @AuraEnabled
    public static list<Marketing_Info__c> getChdRecord(string id1)
    {
        return [select id,name,Account__r.Name,Business_Partner__r.Name,Influencer__r.Name,Sites__r.Name,BP_Min__c,Products__c,Brand__r.Name,Market_Information__r.Name,RSP_Max__c,RSP_Min__c,WSP_Max__c,WSP_Min__c from Marketing_Info__c where Market_Information__c=:id1];
    }
    @AuraEnabled
    public static list<mktinfowrapper> getAllwraps()
    {
        List<Marketing_Info__c> mkt = new List<Marketing_Info__c>();
        List<mktinfowrapper> mktwrap = new List<mktinfowrapper>();
        for(integer i=0;i<4;i++)
        {
            mktinfowrapper miw = new mktinfowrapper();
            mktwrap.add(miw);
        }
        return mktwrap;
    }
    @AuraEnabled
    public static list<Account> getAllAccounts(String idst)
    {
        if(idst == null)
            return [select id, name from Account where ownerID = :UserInfo.getUserId() Order By Name];
        else
            return [select id, name from Account where id=:idst]; 
    }
    @AuraEnabled
    public static list<District__c> getAllters()
    {
        return [select id, name from District__c Order By Name];
    }
    @AuraEnabled
    public static list<Brand__c> getAllBrands()
    {
        return [select id, name from Brand__c Order By Name];
    }
    @AuraEnabled
    public static list<Lead> getAllLeads(String idst)
    {
        system.debug('idst'+idst);
        if(idst == null)
            return [select id, name from Lead Order By Name];
        else
            return [select id, name from Lead where id=:idst]; 
    }
    @AuraEnabled
    public static list<Business_Partner__c> getAllbnspartns(String idst)
    {
        system.debug('idst'+idst);
        if(idst == null)
            return [select id, name from Business_Partner__c Order By Name];
        else
            return [select id, name from Business_Partner__c where id=:idst]; 
    }
    @AuraEnabled
    public static list<Influencer__c> getAllInfs(String idst)
    {
        system.debug('idst'+idst);
        if(idst == null)
            return [select id, name from Influencer__c Order By Name];
        else
            return [select id, name from Influencer__c where id=:idst]; 
    }
    @AuraEnabled
    public static list<Project_Site__c> getAllpjtsites(String idst)
    {
        system.debug('idst'+idst);
        if(idst == null)
            return [select id, name from Project_Site__c Order By Name];
        else
            return [select id, name from Project_Site__c where id=:idst]; 
    }
    @AuraEnabled
    public static list<Product2> getAllProducts()
    {
        list<Product2> prdlist = [select id,Group__c from Product2 Order By Name];
        map<String,Product2> prdmap = new map<String,Product2>();
        for(Product2 pd : prdlist)
            prdmap.put(pd.Group__c,pd);
        
        list<Product2> prdlst = new list<Product2>();
        for(String str:prdmap.keySet())
            prdlst.add(prdmap.get(str));
        return prdlst;
    }
    @AuraEnabled
    public static list<sObject> getAllVsts(String idst)
    {
        System.debug('----'+idst);
        if(idst == null)
            return null;
        else
        {
            Visit__c vst = [select id, name,Account__c,Lead__c,Business_Partner__c,Influencer__c,Project_Site__c from Visit__c Where id=:idst limit 1];
            if(vst.Account__c != null)
            {
                List<Account> ac = [select id, name from Account where id=:vst.Account__c];
                return ac;
            }
            else if(vst.Lead__c != null)
            {
                List<Lead> ld = [select id, name from Lead where id=:vst.Lead__c];
                return ld;
            }
            else if(vst.Business_Partner__c!= null)
            {
                List<Business_Partner__c> bp = [select id, name from Business_Partner__c where id=:vst.Business_Partner__c];
                return bp;
            }
            else if(vst.Influencer__c != null)
            {
                List<Influencer__c> inf = [select id, name from Influencer__c where id=:vst.Influencer__c];
                return inf;
            }
            else if(vst.Project_Site__c != null)
            {
                List<Project_Site__c> ps = [select id, name from Project_Site__c where id=:vst.Project_Site__c];
                return ps;
            }
            else
                return null;
        }   
    }
    @AuraEnabled
    public Static String getSave(Market_Information__c mktinfo,string newmkinfo,String acid,String ldid,String vstid,string bpid,String psid,String infid)
    {
        system.debug('--acid1--'+mktinfo.Lead__c);
        system.debug('--ldid1--'+mktinfo.Account__c);
        system.debug('--mktinfo--'+mktinfo);
        /*if(acid!=null)
            mktinfo.Account__c = acid;
        if(ldid!=null)
            mktinfo.Lead__c = ldid;*/
        if(!String.isBlank(vstid))
        {
            Visit__c vst = [select id, name,Account__c,Lead__c,Business_Partner__c,Influencer__c,Project_Site__c from Visit__c Where id=:vstid limit 1];
            if(vst.Account__c != null)
            {
                Account ac = [select id, name from Account where id=:vst.Account__c];
                mktinfo.Account__c = ac.id;
            }
            else if(vst.Lead__c != null)
            {
                Lead ld = [select id, name from Lead where id=:vst.Lead__c];
                mktinfo.Lead__c = ld.id;
            }
            else if(vst.Business_Partner__c!= null)
            {
                Business_Partner__c bp = [select id, name from Business_Partner__c where id=:vst.Business_Partner__c];
                mktinfo.Business_Partner__c = bp.id;
            }
            else if(vst.Influencer__c != null)
            {
                Influencer__c inf = [select id, name from Influencer__c where id=:vst.Influencer__c];
                mktinfo.Influencer__c = inf.id;
            }
            else if(vst.Project_Site__c != null)
            {
                Project_Site__c ps = [select id, name from Project_Site__c where id=:vst.Project_Site__c];
                mktinfo.Sites__c = ps.id;
            }
        }
        if(!String.isBlank(bpid))
            mktinfo.Business_Partner__c = bpid;
        if(!String.isBlank(psid))
            mktinfo.Sites__c = psid;
        if(!String.isBlank(infid))
            mktinfo.Influencer__c = infid;
        if(!(String.isBlank(mktinfo.Account__c) && String.isBlank(mktinfo.Lead__c) && String.isBlank(mktinfo.Business_Partner__c) && String.isBlank(mktinfo.Sites__c) && String.isBlank(mktinfo.Influencer__c)))
        {
            try
            {
                system.debug('--true--');
                insert mktinfo;
                system.debug('-----'+mktinfo.id);
                system.debug('-----'+newmkinfo);
                List<Marketing_Info__c> insertmi = new List<Marketing_Info__c>();
                mktinfowrapper[] values = (List<mktinfowrapper>) JSON.deserialize(newmkinfo,List<mktinfowrapper>.Class);
                system.debug('---values--'+values);
                for(mktinfowrapper wl:values)
                {
                    if(wl.Brand != null && wl.Brand != '')
                    {
                        system.debug('---values--'+wl.Brand);
                        Marketing_Info__c mi = new Marketing_Info__c();
                        mi.Market_Information__c = mktinfo.Id;
                        mi.Account__c=mktinfo.Account__c;
                        mi.Business_Partner__c = mktinfo.Business_Partner__c;
                        mi.Sites__c = mktinfo.Sites__c;
                        mi.Influencer__c = mktinfo.Influencer__c;
                        mi.Brand__c = wl.Brand;
                        mi.Products__c = wl.Product;
                        mi.BP_Min__c = wl.BPMin;
                        
                        mi.RSP_Min__c = wl.RSP;
                        
                        mi.WSP_Min__c = wl.WSP;
                        insertmi.add(mi);   
                    }
                }        
                insert insertmi;
                return 'success';
            }
            catch(exception e)
            {
                return e.getMessage();
            }
        }
        else
        {
            return 'Select Account or Lead to Save a record';
        }
    }
    //------------------Edit Market Info----------------//
    @AuraEnabled
    public static list<Marketing_Info__c> getallMi(String acnt,String tdate)
    {
        return [select id,name,Account__c,Business_Partner__r.Name,Influencer__r.Name,Sites__r.Name,Business_Partner__c,Influencer__c,Sites__c,Brand__c,Brand__r.name,RSP_Max__c,RSP_Min__c,WSP_Max__c,WSP_Min__c,BP_Min__c from Marketing_Info__c where Account__c =:acnt and DAY_ONLY(CreatedDate) =:date.valueof(tdate)];
    }
    @AuraEnabled
    public static list<Market_Information__c> getallMijsw(String acnt,String tdate)
    {
        return [select id,name,Account__c,Account__r.Name,Business_Partner__r.Name,Influencer__r.Name,Sites__r.Name,Business_Partner__c,Influencer__c,Sites__c,Comments__c,JSW_Average_Monthly_Volume__c,JSW_BP_Min__c,JSW_RSP_Max__c,JSW_RSP_Min__c,JSW_WSP_Max__c,JSW_WSP_Min__c,Product__c,Visit__c,Territory__c from Market_Information__c where Account__c =:acnt and DAY_ONLY(CreatedDate) =:date.valueof(tdate)];
    }
    @AuraEnabled
    public static void saveEdit(String mkinf,String mkjsw)
    {
        Marketing_Info__c[] values = (List<Marketing_Info__c>) JSON.deserialize(mkinf,List<Marketing_Info__c>.Class);
        Market_Information__c[] values1 = (List<Market_Information__c>) JSON.deserialize(mkjsw,List<Market_Information__c>.Class);
        update values;
        update values1;
    }
}