JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Customer_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Ledgers</relationshipLabel>
        <relationshipName>Customer_Ledgers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Ledger</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Customer Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Ledgers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_To_Party__c</fullName>
        <label>Sold To Party</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Orders</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Ship_To_Party__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To Party</relationshipLabel>
        <relationshipName>Ship_To_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_to_Code__c</fullName>
        <label>Sold to Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ship To Party</label>
    <nameField>
        <label>Ship To Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Targets</relationshipLabel>
        <relationshipName>Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dealer Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/CustomerSharingRules_Test.cls
@isTest
public class CustomerSharingRules_Test {
    public static testmethod void CustomerSharingRulesTest(){
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Customer_Code__c = '12345';
        insert acc;
        
        Account acc1 = new Account();
        acc1.Name = 'Sample Account1';
        acc1.Customer_Code__c = '12345';
        acc1.ParentId=acc.id;
        insert acc1;
        
        Contact con = new Contact();
        con.LastName = 'Sample Contact';
        con.Email = 'testmail@org.com';
        con.AccountId = acc.id;
        insert con;
        
        Contact con1 = new Contact();
        con1.LastName = 'Sample Contact1';
        con1.Email = 'testmail1@org.com';
        con1.AccountId = acc1.id;
        insert con1;
        
        Profile prf = [select id,name from Profile where name = 'JSW Customer'];
        
        User usr = new User(Alias = 'standt', Email='standarduser@testorg.com', ContactId = con.id, EmailEncodingKey='UTF-8',
                            LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_IN', ProfileId = prf.Id, 
                            TimeZoneSidKey='Asia/Kolkata', UserName='standardmnguser@testorg.com');
        insert usr;
        
        Order__c so = new Order__c();
        so.Sold_To_Party__c = '12345';
        so.Account__c = acc.id;
        insert so;
        
        Invoice__c inv = new Invoice__c();
        inv.Sold_To_Code__c = '12345';
        inv.Account__c = acc.id;
        insert inv;
        
        Customer_Ledger__c clr = new Customer_Ledger__c();
        clr.Customer_Code__c = '12345';
        clr.Account__c = acc.id;
        insert clr;
        
        Ship_To_Party__c shp = new Ship_To_Party__c();
        shp.Sold_To_Code__c = '12345';
        shp.Account__c = acc.id;
        insert shp;
        
        Target__c trg = new Target__c();
        trg.Customer_Code__c = '12345';
        trg.Dealer_Name__c = acc.id;
        insert trg;
        
        Test.StartTest();
        CustomerSharingSchedule cus = new CustomerSharingSchedule();
        String sch = '0 15 12 * * ?'; 
        system.schedule('Test batchCustomerSharingRule Check', sch, cus);
        Test.stopTest(); 
    }
}