JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <picklist>
            <picklistValues>
                <fullName>Zone 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zone 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zone 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zone 4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor_Brands__c</fullName>
        <label>Competitor Brands</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email_1__c</fullName>
        <label>Contact Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_2__c</fullName>
        <label>Contact Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_3__c</fullName>
        <label>Contact Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_3__c</fullName>
        <label>Contact Person 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_1__c</fullName>
        <label>Contact Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_2__c</fullName>
        <label>Contact Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_3__c</fullName>
        <label>Contact Phone 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Role_1__c</fullName>
        <label>Contact Role 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_2__c</fullName>
        <label>Contact Role 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_3__c</fullName>
        <label>Contact Role 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Inclination_to_JSW__c</fullName>
        <label>Inclination to JSW</label>
        <picklist>
            <picklistValues>
                <fullName>Fully Inclined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Inclined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Inclined</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_of_concerned_SO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name of concerned SO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_sites_under_influencer__c</fullName>
        <label>No. of sites under influencer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Registered_with_JSW_ELP_program__c</fullName>
        <label>Registered with JSW ELP program?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Name</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Engineers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder office</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_potential_in_MT__c</fullName>
        <label>Volume potential in MT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor_Brands__c</fullName>
        <label>Competitor Brands</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Email_1__c</fullName>
        <label>Contact Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_2__c</fullName>
        <label>Cntact Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_3__c</fullName>
        <label>Contact Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_3__c</fullName>
        <label>Contact Person 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_1__c</fullName>
        <label>Contact Phone 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_2__c</fullName>
        <label>Contact Phone 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_3__c</fullName>
        <label>Contact Phone 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_1__c</fullName>
        <label>Contact Role 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_2__c</fullName>
        <label>Contact Role 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_3__c</fullName>
        <label>Contact Role 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Concerned_SO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name of Concerned SO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_Potential_in_MT__c</fullName>
        <label>Volume Potential in MT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/classes/InfluencerInsert.cls
@RestResource(urlMapping='/InfluencerInsert/*')
global with sharing class InfluencerInsert{

  @HttpPost
    global static string doPost(InfluencerWrapper influencerWrapper,String userid) {
        Influencer__c inf = new Influencer__c();
        Schema.DescribeSObjectResult InfDest = Influencer__c.sObjectType.getDescribe();
        if(userId.startsWith(InfDest.getKeyPrefix())){
            inf = [SELECT Id,Name,Type__c,Account__c,Account__r.name,District__c,District__r.name,Inclination_to_JSW__c,
                            Phone__c,Email__c,Street__c,City__c,State_Province__c,Country__c,Zip_Postal_Code__c,No_of_sites_under_influencer__c,
                            Category__c,Volume_potential_in_MT__c,Site_Name__c,Site_Name__r.Name,Registered_with_JSW_ELP_program__c,Name_of_concerned_SO__c,
                            Name_of_concerned_SO__r.Name,Competitor_Brands__c,Contact_Person_1__c,Contact_Person_2__c,Contact_Person_3__c,
                            Contact_Email_1__c,Contact_Email_2__c,Contact_Email_3__c,Contact_Phone_1__c,Contact_Phone_2__c,Contact_Phone_3__c,
                            Contact_Role_1__c,Contact_Role_2__c,Contact_Role_3__c,ownerId,owner.name,Zone__c FROM Influencer__c where id =: userid];
            inf.Type__c = influencerWrapper.typeOfInfluencer;
            inf.Name = influencerWrapper.influencerName;
            inf.District__c = influencerWrapper.territory;
            inf.Phone__c = influencerWrapper.phone;
            inf.Email__c = influencerWrapper.email;
            inf.Street__c = influencerWrapper.street;
            inf.City__c = influencerWrapper.city;
            inf.State_Province__c = influencerWrapper.state;
            inf.Country__c = influencerWrapper.country;
            inf.Zip_Postal_Code__c = influencerWrapper.postalcode;
            inf.No_of_sites_under_influencer__c = influencerWrapper.sitecount;
            inf.Inclination_to_JSW__c = influencerWrapper.inclination;
            inf.Category__c = influencerWrapper.category;
            inf.Volume_potential_in_MT__c = influencerWrapper.volume;
            inf.Account__c = influencerWrapper.account;  
            inf.Site_Name__c = influencerWrapper.sitename;
            inf.Registered_with_JSW_ELP_program__c = influencerWrapper.isRegistered;
            inf.Name_of_concerned_SO__c = influencerWrapper.SOname;
            inf.Competitor_Brands__c = influencerWrapper.compbrands;
            inf.Contact_Person_1__c = influencerWrapper.person1;
            inf.Contact_Person_2__c = influencerWrapper.person2;
            inf.Contact_Person_3__c = influencerWrapper.person3;
            inf.Contact_Email_1__c = influencerWrapper.email1;
            inf.Contact_Email_2__c = influencerWrapper.email2;
            inf.Contact_Email_3__c = influencerWrapper.email3;
            inf.Contact_Phone_1__c = influencerWrapper.phone1;
            inf.Contact_Phone_2__c = influencerWrapper.phone2;
            inf.Contact_Phone_3__c = influencerWrapper.phone3;
            inf.Contact_Role_1__c = influencerWrapper.role1;
            inf.Contact_Role_2__c = influencerWrapper.role2;
            inf.Contact_Role_3__c = influencerWrapper.role3;
        } else {
            inf.Type__c = influencerWrapper.typeOfInfluencer;
            inf.Name = influencerWrapper.influencerName;
            inf.District__c = influencerWrapper.territory;
            inf.Phone__c = influencerWrapper.phone;
            inf.Email__c = influencerWrapper.email;
            inf.Street__c = influencerWrapper.street;
            inf.City__c = influencerWrapper.city;
            inf.State_Province__c = influencerWrapper.state;
            inf.Country__c = influencerWrapper.country;
            inf.Zip_Postal_Code__c = influencerWrapper.postalcode;
            inf.No_of_sites_under_influencer__c = influencerWrapper.sitecount;
            inf.Inclination_to_JSW__c = influencerWrapper.inclination;
            inf.Category__c = influencerWrapper.category;
            inf.Volume_potential_in_MT__c = influencerWrapper.volume;
            inf.Account__c = influencerWrapper.account;  
            inf.Site_Name__c = influencerWrapper.sitename;
            inf.Registered_with_JSW_ELP_program__c = influencerWrapper.isRegistered;
            inf.Name_of_concerned_SO__c = influencerWrapper.SOname;
            inf.Competitor_Brands__c = influencerWrapper.compbrands;
            inf.Contact_Person_1__c = influencerWrapper.person1;
            inf.Contact_Person_2__c = influencerWrapper.person2;
            inf.Contact_Person_3__c = influencerWrapper.person3;
            inf.Contact_Email_1__c = influencerWrapper.email1;
            inf.Contact_Email_2__c = influencerWrapper.email2;
            inf.Contact_Email_3__c = influencerWrapper.email3;
            inf.Contact_Phone_1__c = influencerWrapper.phone1;
            inf.Contact_Phone_2__c = influencerWrapper.phone2;
            inf.Contact_Phone_3__c = influencerWrapper.phone3;
            inf.Contact_Role_1__c = influencerWrapper.role1;
            inf.Contact_Role_2__c = influencerWrapper.role2;
            inf.Contact_Role_3__c = influencerWrapper.role3;
            inf.Location__Latitude__s = influencerWrapper.lat;
            inf.Location__Longitude__s = influencerWrapper.lon;
            inf.Ownerid = userid;
            insert inf;
            }
            return inf.id;
       }
       
       global class InfluencerWrapper{
           global String typeOfInfluencer {get; set;}
           global String influencerName {get; set;}
           String territory {get; set;}
           String phone {get; set;}
           String email {get; set;}
           String street {get; set;}
           String city {get; set;}
           String state {get; set;}
           String country {get; set;}
           String postalcode {get; set;}
           Double sitecount {get; set;}
           String inclination {get; set;}
           String category {get; set;}
           Double volume {get; set;}
           String account {get; set;}    
           String sitename {get; set;}
           String isRegistered {get; set;}
           String SOname {get; set;}
           String compbrands {get; set;}
           String person1 {get; set;}
           String person2 {get; set;}
           String person3 {get; set;}
           String email1 {get; set;}
           String email2 {get; set;}
           String email3 {get; set;}
           String phone1 {get; set;}
           String phone2 {get; set;}
           String phone3 {get; set;}
           String role1 {get; set;}
           String role2 {get; set;}
           String role3 {get; set;}
           Double lat {get; set;}
           Double lon {get; set;}
       }
}