JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Sales Order (Order Request)</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Orders</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Booking_Line__c.object
<CustomObject>
    <fields>
        <fullName>Material_Code1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material Code</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order request Line Items</relationshipLabel>
        <relationshipName>Order_request_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipName>Order_Booking_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order request Line Item</label>
    <nameField>
        <displayFormat>ORL{000000000}</displayFormat>
        <label>Order Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order request Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Code/Depot Code</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <picklist>
            <picklistValues>
                <fullName>FOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EX</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Type1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Type</label>
        <referenceTo>Order_Type__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>YQC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YORF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YCOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YEXC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YFCL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YSEZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YORD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YNFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YCL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Customer Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Ship_To_Party__c.Sales_District__c</field>
                <operation>equals</operation>
                <valueField>Ship_To_Party__c.Account__r.Sales_District__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment_Type__c</fullName>
        <label>Shipment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Y1-Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y2-Bulker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y3-Loose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y4-Rail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y5-Eight Wheel Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y6-Octrai</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{0000000000}</displayFormat>
        <label>Order Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Type__c.object
<CustomObject>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Type</label>
    <nameField>
        <label>Order Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Ship_To_Party__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To Party</relationshipLabel>
        <relationshipName>Ship_To_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ship To Party</label>
    <nameField>
        <label>Ship To Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/EditOrderRequestDetailsTest.cls
@isTest(SeeAllData=false)
public Class EditOrderRequestDetailsTest {
  
         public static Account account;
  
    public static testMethod  void updateAccount()
    {
    
        
         /*Order_Booking_Line__c ordb=new Order_Booking_Line__c();
        ordb.Price__c  =null;
        insert ordb;*/
         account= new Account();
         account.Name='xyz';
         account.Distribution_Channel__c='20';
         account.Division__c='50';
         account.Sales_District__c='1234';
         insert account;
         
       
         Ship_To_Party__c shipToParty=new Ship_To_Party__c(name='test',Account__c=account.Id,Customer_Code__c='test',External_Id__c='test',Sales_District__c='1234',Address__c='Test');
        insert shipToParty;
        Order_Type__c ordt = new Order_Type__c();
        ordt.Name = 'test ordt';
        ordt.Distribution_Channel__c = '20';
        ordt.Division__c = '50';
        insert ordt;
        
      
        
        Order_Request__c orderRequestRec=new Order_Request__c();
        orderRequestRec.Account__c=account.id;
        orderRequestRec.Distribution_Channel__c=account.Distribution_Channel__c;
        orderRequestRec.Division__c=account.Division__c ;
        orderRequestRec.Sales_Org__c='3000';
        orderRequestRec.Sales_District__c=account.Sales_District__c; 
        orderRequestRec.Inco_Terms__c='EXW';
        //orderRequestRec.Ship_To_Party__c=shipToParty.Id;
        orderRequestRec.Order_Type1__c = ordt.Id;
       orderRequestRec.Shipment_Type__c='Y2-Bulker';
        insert orderRequestRec;
        
        Order_Booking_Line__c ordline=new Order_Booking_Line__c ();
        ordline.Order_Request__c=orderRequestRec.id;
        insert ordline;
        
        product2 p=new product2();
        p.Name='p1';
        insert p;
        system.debug('p.id******'+p.id);
        //Order_Request__c OrderRec=[select id,Name,Inco_Terms__c,Account__c,Order_Type1__c  from Order_Request__c where id=:orderRequestRec.Id];
        Order_Booking_Line__c ordb1 = new Order_Booking_Line__c();
        //ordb1.Price__c  = 50;
        ordb1.Material_Code1__c=p.id;
          system.debug('p.id** ordb1.Material_Code1__c****'+ ordb1.Material_Code1__c);
        ordb1.Plant__c='3001';
       
      
        
        PageReference pageRef = Page.orderRequest; 
        pageRef.getParameters().put('CF00Np00000011pVD_lkid', account.Id);         
        pageRef.getParameters().put('id',orderRequestRec.id);        
        Test.setCurrentPage(pageRef);
         
       ApexPages.StandardController sc = new ApexPages.StandardController(orderRequestRec);
       editOrderRequestDetails ordDetails = new editOrderRequestDetails(sc);
       ordDetails.orderRequest=orderRequestRec;
       ordDetails.selectedPhoneNumberContactName='test';
       ordDetails.accountsID=account.Id;
       ordDetails.rowNum='1';
       ordDetails.selectedPhoneNumber='test';
      //ordDetails.ListOrdBook.add(ordb1);
      //ordDetails.ListOrdBook[1].price__c=null;
       ordDetails.accountDetails();
       ordDetails.forSave();
      
      
      
       /* 
        
        Order_Request__c orderRequestRec1=new Order_Request__c();
        orderRequestRec1.Account__c=account.id;
        orderRequestRec1.Distribution_Channel__c=account.Distribution_Channel__c;
        orderRequestRec1.Division__c=account.Division__c ;
        orderRequestRec1.Sales_Org__c='3000';
        orderRequestRec1.Sales_District__c=account.Sales_District__c; 
        orderRequestRec1.Inco_Terms__c='FOR';
        orderRequestRec1.Order_Type1__c = ordt.Id;
        orderRequestRec1.Ship_To_Party__c=shipToParty.Id;
        insert orderRequestRec1;
       
       
        PageReference pageRef1 = Page.orderRequest; 
        pageRef1.getParameters().put('CF00Np00000011pVD_lkid', account.Id);         
        pageRef1.getParameters().put('id',account.Id);        
        Test.setCurrentPage(pageRef1);
        
       ApexPages.StandardController sc1 = new ApexPages.StandardController(orderRequestRec1);
       OrderRequestDetails ordDetails1 = new OrderRequestDetails(sc1);
       ordDetails1.orderRequest=orderRequestRec1;
         ordDetails.selectedPhoneNumberContactName='test';
       ordDetails.accountsID=account.Id;
       ordDetails.rowNum='1';
       ordDetails.selectedPhoneNumber='test';
        ordDetails1.showOrHide();       
       ordDetails1.getDivAndDC();        
        ordDetails1.blockDeletion();
        ordDetails1.addMoreItems();
       
      
       ordDetails1.showOrHide(); */   
    }
    
    
    
     public static testMethod  void updateAccount1()
    {
    
        
         /*Order_Booking_Line__c ordb=new Order_Booking_Line__c();
        ordb.Price__c  =null;
        insert ordb;*/
         account= new Account();
         account.Name='xyz';
         account.Distribution_Channel__c='10';
         account.Division__c='50';
         account.Sales_District__c='1234';
         insert account;
         
       
         Ship_To_Party__c shipToParty=new Ship_To_Party__c(name='test',Account__c=account.Id,Customer_Code__c='test',External_Id__c='test',Sales_District__c='1234',Address__c='Test');
        insert shipToParty;
        Order_Type__c ordt = new Order_Type__c();
        ordt.Name = 'test ordt';
        ordt.Distribution_Channel__c = '10';
        ordt.Division__c = '50';
        insert ordt;
        
      
        
       
        
        //Order_Request__c OrderRec=[select id,Name,Inco_Terms__c,Account__c,Order_Type1__c  from Order_Request__c where id=:orderRequestRec.Id];
        Order_Booking_Line__c ordb1 = new Order_Booking_Line__c();
        //ordb1.Price__c  = 50;
        insert ordb1;
     
        Order_Request__c orderRequestRec1=new Order_Request__c();
        orderRequestRec1.Account__c=account.id;
        orderRequestRec1.Distribution_Channel__c=account.Distribution_Channel__c;
        orderRequestRec1.Division__c=account.Division__c ;
        orderRequestRec1.Sales_Org__c='3000';
        orderRequestRec1.Sales_District__c=account.Sales_District__c; 
        orderRequestRec1.Inco_Terms__c='FOR';
        orderRequestRec1.Order_Type1__c = ordt.Id;
        orderRequestRec1.Ship_To_Party__c=shipToParty.Id;
        insert orderRequestRec1;
       
        Order_Booking_Line__c ordline=new Order_Booking_Line__c ();
        ordline.Order_Request__c=orderRequestRec1.id;
        insert ordline;
        PageReference pageRef1 = Page.orderRequest; 
        pageRef1.getParameters().put('CF00Np00000011pVD_lkid', account.Id);         
        pageRef1.getParameters().put('id',orderRequestRec1.Id);        
        Test.setCurrentPage(pageRef1);
        
       ApexPages.StandardController sc1 = new ApexPages.StandardController(orderRequestRec1);
       editOrderRequestDetails ordDetails1 = new editOrderRequestDetails(sc1);
       ordDetails1.orderRequest=orderRequestRec1;
        // ordDetails.selectedPhoneNumberContactName='test';
       ordDetails1.accountsID=account.Id;
       ordDetails1.rowNum='1';
       ordDetails1.selectedPhoneNumber='test';
        ordDetails1.ListOrdBook.add(ordb1);
        ordDetails1.showOrHide();       
       ordDetails1.getDivAndDC();        
        ordDetails1.blockDeletion();
        ordDetails1.addMoreItems();
      
       ordDetails1.showOrHide();    
    }
    
     public static testMethod  void updateAccount2()
    {
    
        
         /*Order_Booking_Line__c ordb=new Order_Booking_Line__c();
        ordb.Price__c  =null;
        insert ordb;*/
         account= new Account();
         account.Name='xyz';
         account.Distribution_Channel__c='20';
         account.Division__c='50';
         account.Sales_District__c='1234';
         insert account;
         
       
         Ship_To_Party__c shipToParty=new Ship_To_Party__c(name='test',Account__c=account.Id,Customer_Code__c='test',External_Id__c='test',Sales_District__c='1234',Address__c='Test');
        insert shipToParty;
        Order_Type__c ordt = new Order_Type__c();
        ordt.Name = 'test ordt';
        ordt.Distribution_Channel__c = '10';
        ordt.Division__c = '50';
        insert ordt;
        
        
        product2 p=new product2();
        p.Name='p1';
        insert p;
        
      Order__c ord=new Order__c();
      ord.Incoterm__c='FOR';
      ord.Net_Price__c=100;
      ord.Gr_Rate_mt__c=100;
      ord.PO_No__c='test';
      ord.account__c=account.id;
      ord.SO_STO_Date__c=System.today();
      ord.SO_Type__c='YQC';
      ord.Material__c=p.Name;
      
      insert ord;
        
       
        
        //Order_Request__c OrderRec=[select id,Name,Inco_Terms__c,Account__c,Order_Type1__c  from Order_Request__c where id=:orderRequestRec.Id];
        Order_Booking_Line__c ordb1 = new Order_Booking_Line__c();
        //ordb1.Price__c  = 50;
        insert ordb1;
     
        Order_Request__c orderRequestRec1=new Order_Request__c();
        orderRequestRec1.Account__c=account.id;
        orderRequestRec1.Distribution_Channel__c=account.Distribution_Channel__c;
        orderRequestRec1.Division__c=account.Division__c ;
        orderRequestRec1.Sales_Org__c='3000';
        orderRequestRec1.Sales_District__c=account.Sales_District__c; 
        orderRequestRec1.Inco_Terms__c='EXD';
        orderRequestRec1.Order_Type1__c = ordt.Id;
        orderRequestRec1.Ship_To_Party__c=shipToParty.Id;
           orderRequestRec1.Shipment_Type__c='Y2-Bulker';
           orderRequestRec1.Contracts__c=ord.id;
           orderRequestRec1.Month_Of_Date__c=5;
           orderRequestRec1.Distribution_Channel__c='20';
        insert orderRequestRec1;
        
       
        
        system.debug('p.id******'+p.id);
        //Order_Request__c OrderRec=[select id,Name,Inco_Terms__c,Account__c,Order_Type1__c  from Order_Request__c where id=:orderRequestRec.Id];
        Order_Booking_Line__c ordb5 = new Order_Booking_Line__c();
        //ordb1.Price__c  = 50;
        ordb5.Material_Code1__c=p.id;
          system.debug('p.id** ordb1.Material_Code1__c****'+ ordb1.Material_Code1__c);
            ordb5.Order_Request__c=orderRequestRec1.id;
        ordb5.Plant__c='3001';
      
       insert ordb5;
       
        PageReference pageRef1 = Page.orderRequest; 
        pageRef1.getParameters().put('CF00Np00000011pVD_lkid', account.Id);         
        pageRef1.getParameters().put('id',orderRequestRec1.Id); 
         pageRef1.getParameters().put('rowNum','1');        
        Test.setCurrentPage(pageRef1);
        
       ApexPages.StandardController sc1 = new ApexPages.StandardController(orderRequestRec1);
       editOrderRequestDetails ordDetails1 = new editOrderRequestDetails(sc1);
       ordDetails1.orderRequest=orderRequestRec1;
        // ordDetails.selectedPhoneNumberContactName='test';
       ordDetails1.accountsID=account.Id;
       ordDetails1.rowNum='1';
       ordDetails1.selectedPhoneNumber='test';
        ordDetails1.ListOrdBook.add(ordb1);
        ordDetails1.showOrHide();       
       ordDetails1.getDivAndDC();        
        ordDetails1.blockDeletion();
        ordDetails1.addMoreItems();
      
       ordDetails1.showOrHide();
       ordDetails1.showOrHideContracts();
        ordDetails1.getContractsDetails();
        ordDetails1.materialDetails();
    }
 }