JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Engineers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder office</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Promoter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middleman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Any_image_to_be_captured__c</fullName>
        <label>Any image to be captured</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_In_Time__c</fullName>
        <formula>IF(Check_In__c != null, DATETIMEVALUE(Check_In__c), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_Out_Time__c</fullName>
        <formula>IF(Check_Out__c != null, DATETIMEVALUE(Check_Out__c)-(1/4.8)-(30/1440), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check Out Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Check_Out__c</fullName>
        <label>Check Out</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSW_Bag_Visibility__c</fullName>
        <label>JSW Bag Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>JSW_Shop_Board_Condition__c</fullName>
        <label>JSW Shop Board Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Absent</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Account__r.Name + Lead__r.FirstName + Lead__r.MiddleName + Lead__r.LastName +  TEXT(Event__r.Type_of_Meet__c) + Area__r.Name +  Business_Partner__r.Name +  Project_Site__r.Name +  Influencer__r.Name +  Territory__r.Name  + Depot__r.Name +
IF( AND(  OR( Account__c == null, Account__c == &apos;&apos;)  ,
          OR( Lead__c == null, Lead__c == &apos;&apos;)  ,
          OR( Event__c == null, Event__c == &apos;&apos;)  ,
          OR( Area__c == null, Area__c == &apos;&apos;)  ,
          OR( Business_Partner__c == null, Business_Partner__c == &apos;&apos;)  ,
          OR( Project_Site__c == null, Project_Site__c == &apos;&apos;)  ,
          OR( Influencer__c == null, Influencer__c == &apos;&apos;) ,
          OR( Territory__c == null, Territory__c == &apos;&apos;) ),
               General_Visit_Type__c , &apos;&apos;)</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POP_material_comments__c</fullName>
        <label>POP material – comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Collected_by_SO__c</fullName>
        <label>Payment collected in current visit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pending_Payment_Amount_Committed_Date__c</fullName>
        <label>Pending Payment Committed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Visit__c</fullName>
        <label>Purpose of Visit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_level_JSW__c</fullName>
        <label>JSW stock level (number of bags)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF( Account__c != null, &apos;Account&apos;, &apos;&apos;) + 
 IF( Depot__c != null, &apos;Depot&apos;, &apos;&apos;) + 
 IF( Area__c != null , &apos;Area&apos;, &apos;&apos;) +
 IF( Business_Partner__c != null , &apos;Business Partner&apos;, &apos;&apos;) +
 IF( Customer_Type__c != null , &apos;Customer Type&apos;, &apos;&apos;) +
 IF( Event__c != null , &apos;Event&apos;, &apos;&apos;) +
 IF( Influencer__c != null , &apos;Influencer&apos;, &apos;&apos;) +
 IF( Lead__c != null , &apos;Lead&apos;, &apos;&apos;) +
 IF( Project_Site__c != null , &apos;Project Site&apos;, &apos;&apos;) +
 IF( Territory__c != null , &apos;Territory&apos;, &apos;&apos;) +
 IF( General_Visit__c = true , &apos;General&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit_Status__c</fullName>
        <formula>IF(Planned__c = true , &apos;Planned&apos;, &apos;Unplanned&apos;)+&apos; &apos;+ IF( Check_In__c != null, &apos;Visited&apos;, &apos;Not Visited&apos;)</formula>
        <label>Visit Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visited_Location__c</fullName>
        <label>Visited Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/VisitsWebservice.cls
@RestResource(urlMapping='/VisitsManagement/*')
global with sharing class VisitsWebservice{

  @HttpPost
    global static List<Visit__c> doPost(String userId) {
        
        User mobusr = [select id,name,userroleid,userrole.name,Profile.Name from user where id =: userId];
        
        list<Visit__c> VisitsList = [SELECT Id,Name,Name__c,Type__c,Account__c,Account__r.Name,Business_Partner__c,Lead__c,Lead__r.Name,
                                    Business_Partner__r.Name,Influencer__c,Influencer__r.Name,Project_Site__c,Project_Site__r.Name,Check_In__c,Check_Out__c,POP_material_comments__c,
                                   Ownerid,Owner.Name,Planned_Date__c,Planned__c,Check_In_Time__c,Check_Out_Time__c,Purpose_of_Visit__c,Any_image_to_be_captured__c,
                                   Payment_Amount_Collected_by_SO__c,Pending_Payment_Amount_Committed_Date__c,JSW_Bag_Visibility__c,Visit_Status__c,
                                   JSW_Shop_Board_Condition__c,Stock_level_JSW__c,Visited_Location__c,Location__c FROM Visit__c where Ownerid =: mobusr.id and Planned__c = true];
        return VisitsList;
    }
 
}