JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAP_Code__c</fullName>
        <label>SAP Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Owner:User.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_T_Value__c</fullName>
        <formula>Total_value__c - (  MMC__c   + BED_Total__c + CGST_Value__c +  CSTT__c +  IGST_Value__c +  SGST_Value__c +  UGST_Value__c +   VAT_Value__c + Freight__c + (NSR_C_F_Value__c *  Qty__c ) +    (( NSR_Other_Discount__c ) - ABS(Additional_Discount__c) ) +  NSR_Packing_Cost__c + (NSR_PD_Value__c *  Qty__c ) + (NSR_PRFT_Value__c *  Qty__c ) + NSR_Rake_Discount__c +  Total_Adhoc_Discount__c )- IF( (Commercial_Invoice_Date_Formula__c &gt;  DATE(2017,04,30) &amp;&amp; Commercial_Invoice_Date_Formula__c &lt; DATE(2017,07,01)   &amp;&amp;  (Brand_Short_Form__c  = &apos;PSC  || CHD&apos;)) ,Discount__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Inv_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Inv Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SAP_Code__c</fullName>
        <label>SAP Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_NT_Actuals__c</fullName>
        <label>NSR NT Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Trade_Actuals__c</fullName>
        <label>NSR Trade Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_New_Dealers_in_this_Month__c</fullName>
        <label>No of New Dealers in this Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UT_Code__c</fullName>
        <formula>CASESAFEID( OwnerId ) +&apos;:&apos;+ Month__c +&apos;:&apos;+ Year__c +&apos;:&apos;+ Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UT Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Non_Trade_Actuals__c</fullName>
        <label>User Non-Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_Trade_Actuals__c</fullName>
        <label>User Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X15_Days_Actuals__c</fullName>
        <label>15 Days Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Targets</label>
    <nameField>
        <displayFormat>UT-{000000}</displayFormat>
        <label>User Targets  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchUserTrgtUpdate.cls
global class batchUserTrgtUpdate implements Database.Batchable<sObject> 
{
    public String qrystr;
    public Date myDate;
    public batchUserTrgtUpdate(String str)
    {
        myDate = System.today()-1;
        //qrystr = str+String.valueOf(myDate).substring(0,10);
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        Map<String,Double> usrtrgtmapT = new Map<String,Double>();
        Map<String,Double> usrtrgtmapNT = new Map<String,Double>();
        Map<String,Double> nsrtrgtmapT = new Map<String,Double>();
        Map<String,Double> nsrtrgtmapNT = new Map<String,Double>();
        Map<String,Double> usrtrgtmap15 = new Map<String,Double>();
        Map<Id,String> usrmap = new Map<Id,String>();
        List<invoice__c> invlist = new List<Invoice__c>();
        Set<ID> usrids = new Set<ID>();
        Map<ID,integer> newusrmap = new Map<ID,integer>();
        Date mydate = date.newInstance((System.today()-1).year(),(System.today()-1).month(),16);
        List<Account> newaccs = [Select id,Ownerid from Account where CALENDAR_MONTH(CreatedDate)=:mydate.month()];
        System.debug('---mydate---'+mydate);
        for(Account ac : newaccs)
        {
            if(!newusrmap.containsKey(ac.Ownerid))
                newusrmap.put(ac.Ownerid,1);
            else
                newusrmap.put(ac.Ownerid,newusrmap.get(ac.Ownerid)+1);
        }
        
        for(Invoice__c inv : scope)
        {
            usrids.add(inv.OwnerId);
            if(inv.Distribution_Channel__c == '10')
                if(!usrtrgtmapT.containsKey(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c))
                {
                    nsrtrgtmapT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.NSR_T_Value__c);                 
                    usrtrgtmapT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.Qty__c);                 
                }
                else
                {
                    nsrtrgtmapT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,usrtrgtmapT.get(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.NSR_T_Value__c);   
                    usrtrgtmapT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,usrtrgtmapT.get(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.Qty__c);  
                }
            if(inv.Distribution_Channel__c == '20')
                if(!usrtrgtmapNT.containsKey(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c))
                {
                    nsrtrgtmapNT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.NSR_T_Value__c);
                    usrtrgtmapNT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.Qty__c);
                }
                else
                {
                    nsrtrgtmapNT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,usrtrgtmapNT.get(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.NSR_T_Value__c);
                    usrtrgtmapNT.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,usrtrgtmapNT.get(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.Qty__c);
                }
            if(inv.Commercial_Invoice_Date_Formula__c < mydate && inv.Commercial_Invoice_Date_Formula__c.month() == (System.today()-1).month())
            {
                System.debug('---comDate---'+inv.Commercial_Invoice_Date_Formula__c);
                if(!usrtrgtmap15.containsKey(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c))
                    usrtrgtmap15.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.Qty__c);                 
                else
                    usrtrgtmap15.put(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,usrtrgtmap15.get(inv.OwnerId+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.Qty__c);  
            }
            
            inv.User_Inv_Processed__c = true;
            invlist.add(inv);
        }
        
        System.debug('---T'+usrtrgtmapT);
        System.debug('---NT'+usrtrgtmapNT);
        System.debug('---15'+usrtrgtmap15);
        
        List<User_Targets__c> UTList = [Select id,UT_Code__c,User_Trade_Actuals__c,User_Non_Trade_Actuals__c,Ownerid,X15_Days_Actuals__c,NSR_Trade_Actuals__c,NSR_NT_Actuals__c from User_Targets__c where UT_Code__c IN: usrtrgtmapT.keySet() OR UT_Code__c IN: usrtrgtmapNT.keySet()];
        List<User> usrlst = [Select Id,SAP_Code__c from User where Id IN: usrids];
        List<User_Targets__c> UTListInsert = new List<User_Targets__c>();
        
        for(User usr : usrlst)
        {
            usrmap.put(usr.Id,usr.SAP_Code__c);
        }
        
        for(User_Targets__c ut : UTList)
        {
            if(usrtrgtmapT.containsKey(ut.UT_Code__c))
            {
                ut.NSR_Trade_Actuals__c = ut.NSR_Trade_Actuals__c==null ? nsrtrgtmapT.get(ut.UT_Code__c) : ut.NSR_Trade_Actuals__c + nsrtrgtmapT.get(ut.UT_Code__c);
                ut.User_Trade_Actuals__c = ut.User_Trade_Actuals__c==null ? usrtrgtmapT.get(ut.UT_Code__c) : ut.User_Trade_Actuals__c + usrtrgtmapT.get(ut.UT_Code__c);
                usrtrgtmapT.remove(ut.UT_Code__c);
                nsrtrgtmapT.remove(ut.UT_Code__c);
            }
            if(usrtrgtmapNT.containsKey(ut.UT_Code__c))
            {
                ut.NSR_NT_Actuals__c = ut.NSR_NT_Actuals__c ==null ? nsrtrgtmapNT.get(ut.UT_Code__c) : ut.NSR_NT_Actuals__c+ nsrtrgtmapNT.get(ut.UT_Code__c);
                ut.User_Non_Trade_Actuals__c = ut.User_Non_Trade_Actuals__c==null ? usrtrgtmapNT.get(ut.UT_Code__c) : ut.User_Non_Trade_Actuals__c + usrtrgtmapNT.get(ut.UT_Code__c);
                usrtrgtmapNT.remove(ut.UT_Code__c);
                nsrtrgtmapNT.remove(ut.UT_Code__c);
            }
            if(usrtrgtmap15.containsKey(ut.UT_Code__c))
            {
                ut.X15_Days_Actuals__c = ut.X15_Days_Actuals__c ==null ? usrtrgtmap15.get(ut.UT_Code__c) : ut.X15_Days_Actuals__c + usrtrgtmap15.get(ut.UT_Code__c);
                usrtrgtmap15.remove(ut.UT_Code__c);
            }
            if(newusrmap.containsKey(ut.Ownerid))
            {
                ut.No_of_New_Dealers_in_this_Month__c = newusrmap.get(ut.Ownerid);
                newusrmap.remove(ut.Ownerid);
            }
        }
        System.debug('---2'+usrtrgtmapT);
        System.debug('---2'+usrtrgtmapNT);
        for(String str : usrtrgtmapT.keySet())
        {
            User_Targets__c usrtrgt = new User_Targets__c();
            if(usrmap.containsKey(str.split(':')[0]))
                usrtrgt.Employee_ID__c = usrmap.get(str.split(':')[0]);
            usrtrgt.Month__c = str.split(':')[1];
            usrtrgt.Year__c = str.split(':')[2];
            usrtrgt.Product__c = str.split(':')[3];
            usrtrgt.User_Trade_Actuals__c = usrtrgtmapT.get(str);
            usrtrgt.NSR_Trade_Actuals__c = nsrtrgtmapT.get(str);
            usrtrgt.X15_Days_Actuals__c = usrtrgtmap15.get(str);
            if(newusrmap.containsKey(str.split(':')[0]))
            {
                usrtrgt.No_of_New_Dealers_in_this_Month__c = newusrmap.get(str.split(':')[0]);
                newusrmap.remove(str.split(':')[0]);
            }
            if(usrtrgtmapNT.containsKey(str))
            {
                usrtrgt.User_Non_Trade_Actuals__c = usrtrgtmapNT.get(str);
                usrtrgtmapNT.remove(str);
            }
            UTListInsert.add(usrtrgt);
                
        }
        for(String str : usrtrgtmapNT.keySet())
        {
            User_Targets__c usrtrgt = new User_Targets__c();
            if(usrmap.containsKey(str.split(':')[0]))
                usrtrgt.Employee_ID__c = usrmap.get(str.split(':')[0]);
            usrtrgt.Month__c = str.split(':')[1];
            usrtrgt.Year__c = str.split(':')[2];
            usrtrgt.Product__c = str.split(':')[3];
            usrtrgt.User_Non_Trade_Actuals__c = usrtrgtmapNT.get(str);
            usrtrgt.NSR_NT_Actuals__c = nsrtrgtmapNT.get(str);
            usrtrgt.X15_Days_Actuals__c = usrtrgtmap15.get(str);
            if(newusrmap.containsKey(str.split(':')[0]))
            {
                usrtrgt.No_of_New_Dealers_in_this_Month__c = newusrmap.get(str.split(':')[0]);
                newusrmap.remove(str.split(':')[0]);
            }
            if(usrtrgtmapT.containsKey(str))
            {
                usrtrgt.User_Trade_Actuals__c = usrtrgtmapT.get(str);
                usrtrgtmapT.remove(str);
            }
            UTListInsert.add(usrtrgt);
        }
        Update UTList;
        Update invlist;
        Insert UTListInsert;
    }
    global void finish(Database.BatchableContext BC) {
    }
}