JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <picklist>
            <picklistValues>
                <fullName>Zone 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zone 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zone 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zone 4</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor_Brands__c</fullName>
        <label>Competitor Brands</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email_1__c</fullName>
        <label>Contact Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_2__c</fullName>
        <label>Contact Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_3__c</fullName>
        <label>Contact Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_3__c</fullName>
        <label>Contact Person 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_1__c</fullName>
        <label>Contact Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_2__c</fullName>
        <label>Contact Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_3__c</fullName>
        <label>Contact Phone 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_Role_1__c</fullName>
        <label>Contact Role 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_2__c</fullName>
        <label>Contact Role 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_3__c</fullName>
        <label>Contact Role 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Inclination_to_JSW__c</fullName>
        <label>Inclination to JSW</label>
        <picklist>
            <picklistValues>
                <fullName>Fully Inclined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Inclined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Inclined</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_of_concerned_SO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name of concerned SO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_sites_under_influencer__c</fullName>
        <label>No. of sites under influencer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Registered_with_JSW_ELP_program__c</fullName>
        <label>Registered with JSW ELP program?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site Name</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Influencers</relationshipLabel>
        <relationshipName>Influencers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Engineers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder office</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_potential_in_MT__c</fullName>
        <label>Volume potential in MT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor_Brands__c</fullName>
        <label>Competitor Brands</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Email_1__c</fullName>
        <label>Contact Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_2__c</fullName>
        <label>Cntact Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_3__c</fullName>
        <label>Contact Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_3__c</fullName>
        <label>Contact Person 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_1__c</fullName>
        <label>Contact Phone 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_2__c</fullName>
        <label>Contact Phone 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_3__c</fullName>
        <label>Contact Phone 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_1__c</fullName>
        <label>Contact Role 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_2__c</fullName>
        <label>Contact Role 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role_3__c</fullName>
        <label>Contact Role 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Concerned_SO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name of Concerned SO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_Potential_in_MT__c</fullName>
        <label>Volume Potential in MT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/classes/InfluencersSyncservice.cls
@RestResource(urlMapping='/InfluencersSync/*')
global with sharing class InfluencersSyncservice{

    @HttpPost
    global static List<Influencer__c> doPost(String userId,DateTime dte) {
        
        List<Influencer__c> InfluencersList = new List<Influencer__c>();
        String curRole = '';
        User mobusr = [select id,name,userroleid,userrole.name,Profile.Name from user where id =: userId];
        
        curRole = mobusr.UserRole.Name.split(' ')[0];
        curRole = curRole+'%';
        List<User> allusrs = [select id,name from User where UserRole.Name like : curRole];
        Set<Id> userset = new Set<Id>();
        for(User usr : allusrs){
            userset.add(usr.id);
        }
        
        InfluencersList = [SELECT Id,Name,Type__c,Account__c,Account__r.name,District__c,District__r.name,Inclination_to_JSW__c,
                            Phone__c,Email__c,Street__c,City__c,State_Province__c,Country__c,Zip_Postal_Code__c,No_of_sites_under_influencer__c,
                            Category__c,Volume_potential_in_MT__c,Site_Name__c,Site_Name__r.Name,Registered_with_JSW_ELP_program__c,Name_of_concerned_SO__c,
                            Name_of_concerned_SO__r.Name,Competitor_Brands__c,Contact_Person_1__c,Contact_Person_2__c,Contact_Person_3__c,
                            Contact_Email_1__c,Contact_Email_2__c,Contact_Email_3__c,Contact_Phone_1__c,Contact_Phone_2__c,Contact_Phone_3__c,
                            Contact_Role_1__c,Contact_Role_2__c,Contact_Role_3__c,ownerId,owner.name,Zone__c FROM Influencer__c where Ownerid in: userset and LastModifiedDate >=: dte];
        
        return InfluencersList;
    }
 
}