JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Trade</fullName>
        <active>true</active>
        <label>Trade</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Actuals</label>
    <nameField>
        <displayFormat>ACTL-{0000000000}</displayFormat>
        <label>Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/ASM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <summarizedField>Monthly_Dealer_Target__c.Target__c</summarizedField>
        <summaryForeignKey>Monthly_Dealer_Target__c.ASM_Target__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>ASM Target</label>
    <nameField>
        <displayFormat>ASM-{0000}</displayFormat>
        <label>ASM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Basic_Price__c</fullName>
        <label>Total Basic Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <label>Total value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Dealer_Target__c.object
<CustomObject>
    <fields>
        <fullName>ASM_Target__c</fullName>
        <label>ASM Target</label>
        <referenceTo>ASM_Targets__c</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <defaultValue>0.0</defaultValue>
        <label>Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territorys__c</fullName>
        <label>Territory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Dealer Target</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Monthly Target  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Dealer Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <formula>IF( ISBLANK( Dealer__c ) ,  Dealer_NT_ND__c , Dealer__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dealer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <formula>Monthly_Dealer_Target__r.Districts__r.Name</formula>
        <label>District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Month_Actual__c</fullName>
        <label>Last Month Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Year_Same_Month_Actual__c</fullName>
        <label>Last Year Same Month Actual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>MONTH( Monthly_Dealer_Target__r.Target_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Actaul__c</fullName>
        <label>Monthly Actaul</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Dealer_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Dealer Target</label>
        <referenceTo>Monthly_Dealer_Target__c</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Target__c</fullName>
        <label>Monthly Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>TEXT(YEAR( Monthly_Dealer_Target__r.Target_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Monthly Targets</label>
    <nameField>
        <label>Monthly Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

JSW Devsb/src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Dealer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Targets</relationshipLabel>
        <relationshipName>Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <formula>Territory__r.Districts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/classes/PlanDetails.cls
public class PlanDetails{
    @AuraEnabled
    public static list<Monthly_Dealer_Target__c> getRecord(string id1)
    {
        return [select id, name, ASM_Target__c, ASM_Target__r.Name,Districts__r.Name,Target_Date__c,Products__c,Sales_Officer__c,Sales_Officer__r.name,Territorys__c,Target__c,Actuals__c,Quantity__c from Monthly_Dealer_Target__c where id=:id1 Order By Name];
    }
    @AuraEnabled
    public static list<Monthly_Targets__c> getChdRecord(string id1)
    {
        return [select id,Dealer__c,Dealer__r.Name,Dealer_Name__c,name,Last_Month_Actual__c,Last_Year_Same_Month_Actual__c,Monthly_Dealer_Target__c,Monthly_Dealer_Target__r.Name,Monthly_Target__c,Monthly_Actaul__c,Quantity__c from Monthly_Targets__c where Monthly_Dealer_Target__c=:id1 Order By Dealer__r.Name];
    }
    @AuraEnabled
    public static boolean getmtso(String cdate,String prod,String uname)
    {
        //Date myDate = Date.newInstance(cdate.year(),cdate.month(),cdate.day());
        Integer year = Integer.valueOf(cdate.split('-')[0]);
        Integer mnth = Integer.valueOf(cdate.split('-')[1]);
        Integer day = Integer.valueOf(cdate.split('-')[2]);
        Date myDate = Date.newInstance(year,mnth,day);
        system.debug('myDate'+myDate);
        list<Monthly_Dealer_Target__c> mt = [select id from Monthly_Dealer_Target__c where Products__c=:prod and CALENDAR_MONTH(Target_Date__c)=:mnth and Sales_Officer__r.Name=:uname];
        return (mt.size()>0);
    }
    @AuraEnabled
    public static list<String> getAllProducts()
    {
        list<Product2> prdlist = [select Group__c from Product2 Order By Name];
        set<String> prdset = new set<string>();
        list<String> prdlst = new list<string>();
        for(Product2 str:prdlist)
        prdset.add(str.group__c);
        prdlst.addAll(prdset);
        return prdlst;
    }
    @AuraEnabled
    public static list<ASM_Targets__c> getAllasms()
    {
        return [select id, name from ASM_Targets__c Order By Name];
    }
    @AuraEnabled
    public static list<Account> getAllAccounts()
    {
        system.debug('----');
        return [select id, name from Account Order By Name];
    }
    @AuraEnabled
    public static list<District__c> getAllters(string dist)
    {
        return [select id, name from District__c where Districts__c = :dist Order By Name];
    }
    @AuraEnabled
    public static list<Districts__c> getAlldists()
    {
        return [select id, name from Districts__c Order By Name];
    }
    @AuraEnabled
    public static String getNT(String cdate,String prod)
    {
        Integer samemonth=Integer.valueOf(cdate.split('-')[1]);
        AggregateResult[] groupedResults = [select SUM(Total_value__c)tv from invoice__c where Account__r.OwnerId = :Userinfo.getUserId() and Account__r.RecordType.Name = 'Non-Trade' and Brand_Short_Form__c=:prod and CALENDAR_MONTH(Commercial_Invoice_Date__c)=:samemonth];
        if(groupedResults[0].get('tv') == null)
            return '0.00';
        else
            return String.valueOf(groupedResults[0].get('tv'));
    }
    @AuraEnabled
    public static List<wrapperlightning> getAccounts(String cdate,String prod)
    {
        Integer lastmonth=Integer.valueOf(cdate.split('-')[1])-1;
        Integer samemonth=Integer.valueOf(cdate.split('-')[1]);
        if(lastmonth == 0)
            lastmonth = 12;
        Integer cyear=Integer.valueOf(cdate.split('-')[0]);
        Integer pyear=Integer.valueOf(cdate.split('-')[0])-1;
        
        list<id> accid = new list<id>();
        Map<String,String> invmap = new Map<String,String>();
        List<wrapperlightning> dlrrecrds = new List<wrapperlightning>();

        List<Account> acc = [select id,name from Account where ownerID = :UserInfo.getUserId() and RecordType.Name = 'Trade' Order By Name LIMIT 50];
        for(Account dlrid : acc)
        {
            accid.add(dlrid.id);
        }
        
        List<Monthly_Targets__c> dlrtrgts = [select id,name,Monthly_Actaul__c,Dealer__c,Dealer_Name__c,Last_Month_Actual__c,Last_Year_Same_Month_Actual__c,month__c,year__c from Monthly_Targets__c where Dealer__c IN :accid];     
        list<invoice__c> inv =[select Account__c,Total_Basic_Price__c,Total_value__c,Qty__c from invoice__c where Account__c IN :accid and Brand_Short_Form__c=:prod and CALENDAR_MONTH(Commercial_Invoice_Date__c)=:samemonth];
        AggregateResult[] groupedResults = [select SUM(Total_value__c)tv,SUM(Qty__c)qty from invoice__c where Account__r.OwnerId = :Userinfo.getUserId() and Account__r.RecordType.Name = 'Non-Trade' and Brand_Short_Form__c=:prod and CALENDAR_MONTH(Commercial_Invoice_Date__c)=:samemonth];
        for(Account ac : acc)
        {
            Double total = 0.00;
            Double totalq = 0.00;
            for(invoice__c ivc : inv)
            {
                if(ac.id == ivc.Account__c)
                {
                    if(ivc.Total_value__c != null)
                        total = total + ivc.Total_value__c;
                    if(ivc.Qty__c != null)
                        totalq = totalq + ivc.Qty__c;
                }
            }
            invmap.put(ac.Name,total+':'+totalq);
        }
        wrapperlightning wln = new wrapperlightning();
        wln.dealer = 'Non Trade';
        wln.dlractual = groupedResults[0].get('tv') == null ? 0.00 : Double.valueOf(groupedResults[0].get('tv')) ;
        wln.dlrqty = groupedResults[0].get('qty') == null ? 0.00 : Double.valueOf(groupedResults[0].get('qty')) ;
        dlrrecrds.add(wln);
        for(String acname : invmap.keySet())
        {
            wrapperlightning wl = new wrapperlightning();
            wl.dealer = acname;
            for(Monthly_Targets__c mtid : dlrtrgts)
            {
                if(acname == mtid.Dealer_Name__c) 
                {   
                    if(mtid.Month__c == samemonth && Integer.valueOf(mtid.Year__c) == pyear)
                        wl.LYSMactual = mtid.Monthly_Actaul__c;
                    if(lastmonth == 12)
                    {
                            if(mtid.Month__c == lastmonth && Integer.valueOf(mtid.Year__c) == pyear)
                                wl.LMactual = mtid.Monthly_Actaul__c; 
                    }
                    else if(mtid.Month__c == lastmonth && Integer.valueOf(mtid.Year__c) == cyear)
                        wl.LMactual = mtid.Monthly_Actaul__c; 
                }
            }
            wl.dlractual = double.valueOf(invmap.get(acname).split(':')[0]);
            wl.dlrqty = double.valueOf(invmap.get(acname).split(':')[1]);
            system.debug('dlractual'+wl.dlractual);
            system.debug('dlractual1'+invmap.get('acname'));
            dlrrecrds.add(wl);
        }
        return dlrrecrds;
    }
    @AuraEnabled
    public static String getUserName() {
    return userinfo.getName();
  }
    @AuraEnabled
    public static void mnthtargts(string newdlrtrgt,Monthly_Dealer_Target__c newmdt,String cdate)
    {
        User usr = [select id,managerid from user where id=:Userinfo.getUserId()];
        Integer samemonth=Integer.valueOf(cdate.split('-')[1]);
        newmdt.Sales_Officer__c = usr.id; 
        //ASM_Targets__c asm = [select id from ASM_Targets__c where CreatedById=:usr.ManagerId and CALENDAR_MONTH(Date__c)=:samemonth];
        insert newmdt;
        
        List<Monthly_Targets__c> mtinsert = new List<Monthly_Targets__c>();
        wrapperlightning[] values = (List<wrapperlightning>) JSON.deserialize(newdlrtrgt,List<wrapperlightning>.Class);
        system.debug('=====values'+values);
        system.debug('==='+newmdt);
        Monthly_Dealer_Target__c mdt = [select id,name,Products__c,Target__c,Actuals__c,Quantity__c from Monthly_Dealer_Target__c where id=:newmdt.Id];
        system.debug('---mdt---'+mdt);
        if(values != null)
        for(wrapperlightning wl:values)
        {
            if(wl.dealer != 'Non Trade' && wl.dlrtrget != 0)
            {
                Monthly_Targets__c mt = new Monthly_Targets__c();
                account acc=[select id,name from account where name=:wl.dealer limit 1];
                mt.Dealer__c = acc.id;
                mt.Monthly_Dealer_Target__c = newmdt.id;
                mt.product_short__c = mdt.Products__c;
                mt.Last_Month_Actual__c = wl.LMactual;
                mt.Last_Year_Same_Month_Actual__c = wl.LYSMactual;
                mt.Monthly_Target__c = Double.valueof(wl.dlrtrget);
                mt.Monthly_Actaul__c = wl.dlractual;
                mt.Quantity__c = wl.dlrqty;
                mtinsert.add(mt);
                system.debug('==='+mdt.Target__c);
                system.debug('==='+newmdt.ASM_Target__c);
                /*mdt.Target__c = mdt.Target__c + Double.valueof(wl.dlrtrget);
                mdt.Actuals__c = mdt.Actuals__c==null ? wl.dlractual : mdt.Actuals__c+ wl.dlractual;
                mdt.Quantity__c = mdt.Quantity__c==null ? wl.dlrqty : mdt.Quantity__c+ wl.dlrqty;*/
            }
            else if(wl.dealer == 'Non Trade')
            {
                Monthly_Targets__c nt = new Monthly_Targets__c();
                nt.Dealer_NT_ND__c = 'Non Trade';
                nt.Monthly_Dealer_Target__c = newmdt.id;
                nt.product_short__c = mdt.Products__c;
                nt.Monthly_Target__c = Double.valueof(wl.dlrtrget);
                nt.Monthly_Actaul__c = wl.dlractual;
                nt.Quantity__c = wl.dlrqty;
                mtinsert.add(nt);
            }
        }  
        system.debug('--->'+mtinsert);
        /*Monthly_Targets__c nd = new Monthly_Targets__c();
        nd.Dealer_NT_ND__c = 'New Dealer';
        mtinsert.add(nd);*/
        if(mtinsert.size() > 0)
        insert mtinsert;
        update mdt;
    }
    //---------------Edit----------------//
    @AuraEnabled
    public static Void edittargts(String editmt,String editmdt) 
    {
        Monthly_Targets__c[] values = (List<Monthly_Targets__c>) JSON.deserialize(editmt,List<Monthly_Targets__c>.Class);
        Monthly_Dealer_Target__c[] values1 = (List<Monthly_Dealer_Target__c>) JSON.deserialize(editmdt,List<Monthly_Dealer_Target__c>.Class);
        system.debug('--0--'+values);
        system.debug('--1--'+values1);
        update values;
        update values1;
    }
}