JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>CASE( (Region__c), &quot;36&quot;, &quot;Telangana&quot;, &quot;32&quot;, &quot;Pondicherry&quot;, &quot;25&quot;, &quot;West-Bengal&quot;, &quot;24&quot;, &quot;Uttar-Pradesh&quot;, &quot;22&quot;, &quot;Tamilnadu&quot;, &quot;20&quot;, &quot;Rajastan&quot;, &quot;18&quot;, &quot;Orissa&quot;, &quot;13&quot;, &quot;Maharastra&quot;, &quot;11&quot;, &quot;Kerala&quot;, &quot;10&quot;, &quot;Karnataka&quot;, &quot;06&quot;, &quot;Gujarat&quot;, &quot;05&quot;, &quot;Goa&quot;, &quot;01&quot;, &quot;Andhra-Pradesh&quot;, &quot;Others&quot;)</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>Hyderabad East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rangareddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mahboobnagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagarkurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gadwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nandyal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KGY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cudappah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prodattur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tirupati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madanappalle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nellore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chirala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vijayawada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machlipatnam</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Architect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Architect</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Influencer__c.Type__c</field>
                <operation>equals</operation>
                <value>Architects</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Project Sites (Architect)</relationshipLabel>
        <relationshipName>Project_Sites2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor_Brands__c</fullName>
        <label>Competitor Brands</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Construction_Stage__c</fullName>
        <label>Construction Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-construction stage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nearing completion</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Email_1__c</fullName>
        <label>Contact Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_2__c</fullName>
        <label>Cntact Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Email_3__c</fullName>
        <label>Contact Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person_1__c</fullName>
        <label>Contact Person 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_2__c</fullName>
        <label>Contact Person 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_3__c</fullName>
        <label>Contact Person 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_1__c</fullName>
        <label>Contact Phone 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End_Customer_Name__c</fullName>
        <label>End Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Engineer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Influencer__c.Type__c</field>
                <operation>equals</operation>
                <value>Engineers</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Project Sites</relationshipLabel>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JSW_Cement_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>JSW Cement Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Name_of_Concerned_SO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name of Concerned SO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Quantity_Required__c</fullName>
        <label>Product Quantity Required in MT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concreel HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC &amp; CHD</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Construction End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Status__c</fullName>
        <label>Site Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Active</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Sub_Type__c</fullName>
        <label>Site Sub-Type</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Builder/Contractor SIte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Govt/Institutional SIte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Structural_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Structural Consultant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Influencer__c.Type__c</field>
                <operation>equals</operation>
                <value>Structural Consultants</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Project Sites (Structural Consultant)</relationshipLabel>
        <relationshipName>Project_Sites1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Project Sites (Territory)</relationshipLabel>
        <relationshipName>Project_Sites1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume_Potential_in_MT__c</fullName>
        <label>Volume Potential in MT</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/ProjectSiteInsert.cls
@RestResource(urlMapping='/ProjectSiteInsert/*')
global with sharing class ProjectSiteInsert{
    @HttpPost
    global static string doPost(ProjectSitesWraper projectSitesWraper,String userid) {
        Project_Site__c prj = new Project_Site__c();
        Schema.DescribeSObjectResult PrjDest = Project_Site__c.sObjectType.getDescribe();
        if(userId.startsWith(PrjDest.getKeyPrefix())){
            prj = [SELECT Id,Name,Account__c,Account__r.name,Type__c,Territory__c,Territory__r.name,ownerId,owner.name,
                   End_Customer_Name__c,Phone_Number__c,Site_Sub_Type__c,Product__c,Product_Quantity_Required__c,Site_Status__c,
                   Location__c,Customer_Email__c,Street__c,City__c,State__c,Country__c,Zip_Postal_Code__c,Engineer__c,Architect__c,
                   Structural_Consultant__c,JSW_Cement_Approval__c,Volume_Potential_in_MT__c,Construction_Stage__c,Project_Start_Date__c,
                   Project_End_Date__c,Competitor_Brands__c,Name_of_Concerned_SO__c,Name_of_Concerned_SO__r.Name,Contact_Person_1__c,
                   Contact_Person_2__c,Contact_Person_3__c,Contact_Email_1__c,Contact_Email_2__c,Contact_Email_3__c,Contact_Phone_1__c,
                   Contact_Phone_2__c,Contact_Phone_3__c,Contact_Role_1__c,Contact_Role_2__c,Contact_Role_3__c,Location__Latitude__s,
                   Location__Longitude__s FROM Project_Site__c where id =: userid];
            prj.name = projectSitesWraper.projectSiteName;
            prj.Type__c = projectSitesWraper.type;
            prj.Site_Sub_Type__c = projectSitesWraper.subtype;
            prj.Territory__c = projectSitesWraper.district;
            prj.Account__c = projectSitesWraper.account;
            prj.End_Customer_Name__c = projectSitesWraper.customername;
            prj.Phone_Number__c = projectSitesWraper.phone;
            prj.Customer_Email__c = projectSitesWraper.customeremail;
            prj.Street__c = projectSitesWraper.street;
            prj.City__c = projectSitesWraper.city;
            prj.State__c = projectSitesWraper.state;
            prj.Country__c = projectSitesWraper.country;
            prj.Zip_Postal_Code__c = projectSitesWraper.postalcode;
            if(projectSitesWraper.engineer != null)
            prj.Engineer__c = projectSitesWraper.engineer;
            if(projectSitesWraper.architect != null)
            prj.Architect__c = projectSitesWraper.architect;
            if(projectSitesWraper.stconsultant != null)
            prj.Structural_Consultant__c = projectSitesWraper.stconsultant;
            prj.JSW_Cement_Approval__c = projectSitesWraper.approval;
            prj.Volume_Potential_in_MT__c = projectSitesWraper.volume;
            prj.Construction_Stage__c = projectSitesWraper.stage;
            prj.Project_Start_Date__c = projectSitesWraper.startdt;
            prj.Project_End_Date__c = projectSitesWraper.enddt;
            prj.Competitor_Brands__c = projectSitesWraper.compbrands;
            prj.Name_of_Concerned_SO__c = projectSitesWraper.SOname;
            prj.Contact_Person_1__c = projectSitesWraper.person1;
            prj.Contact_Person_2__c = projectSitesWraper.person2;
            prj.Contact_Person_3__c = projectSitesWraper.person3;
            prj.Contact_Email_1__c = projectSitesWraper.email1;
            prj.Contact_Email_2__c = projectSitesWraper.email2;
            prj.Contact_Email_3__c = projectSitesWraper.email3;
            prj.Contact_Phone_1__c = projectSitesWraper.phone1;
            prj.Contact_Phone_2__c = projectSitesWraper.phone2;
            prj.Contact_Phone_3__c = projectSitesWraper.phone3;
            prj.Contact_Role_1__c = projectSitesWraper.role1;
            prj.Contact_Role_2__c = projectSitesWraper.role2;
            prj.Contact_Role_3__c = projectSitesWraper.role3;
            update prj;
        } else {
            prj = new Project_Site__c();
            prj.name = projectSitesWraper.projectSiteName;
            prj.Type__c = projectSitesWraper.type;
            prj.Site_Sub_Type__c = projectSitesWraper.subtype;
            prj.Territory__c = projectSitesWraper.district;
            prj.Account__c = projectSitesWraper.account;
            prj.End_Customer_Name__c = projectSitesWraper.customername;
            prj.Phone_Number__c = projectSitesWraper.phone;
            prj.Customer_Email__c = projectSitesWraper.customeremail;
            prj.Street__c = projectSitesWraper.street;
            prj.City__c = projectSitesWraper.city;
            prj.State__c = projectSitesWraper.state;
            prj.Country__c = projectSitesWraper.country;
            prj.Zip_Postal_Code__c = projectSitesWraper.postalcode;
            if(projectSitesWraper.engineer != null)
            prj.Engineer__c = projectSitesWraper.engineer;
            if(projectSitesWraper.architect != null)
            prj.Architect__c = projectSitesWraper.architect;
            if(projectSitesWraper.stconsultant != null)
            prj.Structural_Consultant__c = projectSitesWraper.stconsultant;
            prj.JSW_Cement_Approval__c = projectSitesWraper.approval;
            prj.Volume_Potential_in_MT__c = projectSitesWraper.volume;
            prj.Construction_Stage__c = projectSitesWraper.stage;
            prj.Project_Start_Date__c = projectSitesWraper.startdt;
            prj.Project_End_Date__c = projectSitesWraper.enddt;
            prj.Competitor_Brands__c = projectSitesWraper.compbrands;
            prj.Name_of_Concerned_SO__c = projectSitesWraper.SOname;
            prj.Contact_Person_1__c = projectSitesWraper.person1;
            prj.Contact_Person_2__c = projectSitesWraper.person2;
            prj.Contact_Person_3__c = projectSitesWraper.person3;
            prj.Contact_Email_1__c = projectSitesWraper.email1;
            prj.Contact_Email_2__c = projectSitesWraper.email2;
            prj.Contact_Email_3__c = projectSitesWraper.email3;
            prj.Contact_Phone_1__c = projectSitesWraper.phone1;
            prj.Contact_Phone_2__c = projectSitesWraper.phone2;
            prj.Contact_Phone_3__c = projectSitesWraper.phone3;
            prj.Contact_Role_1__c = projectSitesWraper.role1;
            prj.Contact_Role_2__c = projectSitesWraper.role2;
            prj.Contact_Role_3__c = projectSitesWraper.role3;
            prj.Location__Latitude__s = projectSitesWraper.lat;
            prj.Location__Longitude__s = projectSitesWraper.lon;
            prj.Ownerid = userid;
            insert prj;
        }
        return prj.id;
    }
       
    global class ProjectSitesWraper {
       global String projectSiteName {get; set;}
        global String type {get; set;}
        String subtype {get; set;}
        String district {get; set;}
        String account {get; set;}
        global String customername {get; set;}
        String phone {get; set;}
        String customeremail {get; set;}
        String street {get; set;}
        String city {get; set;}
        String state {get; set;}
        String country {get; set;}
        String postalcode {get; set;}
        String engineer {get; set;}
        String architect {get; set;}
        String stconsultant {get; set;}
        global Boolean approval {get; set;}
        Double volume {get; set;}
        String stage {get; set;}
        Date startdt {get; set;}
        Date enddt {get; set;}
        String compbrands {get; set;}
        String SOname {get; set;}
        String person1 {get; set;}
        String person2 {get; set;}
        String person3 {get; set;}
        String email1 {get; set;}
        String email2 {get; set;}
        String email3 {get; set;}
        String phone1 {get; set;}
        String phone2 {get; set;}
        String phone3 {get; set;}
        String role1 {get; set;}
        String role2 {get; set;}
        String role3 {get; set;}
        Double lat {get; set;}
        Double lon {get; set;}
    }
}