JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Partners</relationshipLabel>
        <relationshipName>Business_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Business Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CO_Name__c</fullName>
        <label>CO Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Request_Number__c</fullName>
        <label>Order Request Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Sales Order (Order Request)</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plant Master</label>
        <referenceTo>Plant_Master__c</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Emp__c</fullName>
        <label>Sales Emp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shp_To_Party__c</fullName>
        <label>Shp To Party</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Party__c</fullName>
        <label>Sold To Party</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sales Orders</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Code/Depot Code</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plant Master</label>
        <referenceTo>Plant_Master__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Party</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Ship_To_Party__c.Sales_District__c</field>
                <operation>equals</operation>
                <valueField>Ship_To_Party__c.Account__r.Sales_District__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Ship_To_Party__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{0000000000}</displayFormat>
        <label>Order Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Plant_Master__c.object
<CustomObject>
    <fields>
        <fullName>Plant_Code__c</fullName>
        <label>Plant Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Plant Master</label>
    <nameField>
        <label>Plant MAster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

JSW Devsb/src/objects/Ship_To_Party__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To Party</relationshipLabel>
        <relationshipName>Ship_To_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ship To Party</label>
    <nameField>
        <label>Ship To Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/UpdateOrderTest.cls
@isTest
public Class UpdateOrderTest{
    
    public static testMethod  void updateAccount()
    {
     list<String>soids=new list<String>();
    
  
     account ac=new account();
     ac.Customer_Code__c='abc123';
     ac.name='testing';
        ac.External_ID__c = 'abc123';
     insert ac;
     
     product2 p=new product2();
     p.ProductCode='abc';
     p.name='abc';
     insert p;
     
     Plant_Master__c p2=new Plant_Master__c();
     p2.Plant_Code__c='xyz';
     insert p2;
     
        account ac1=new account();
     ac1.Customer_Code__c='abc123';
     ac1.name='testing';
        ac1.External_ID__c = 'abc1231050';
     insert ac1;
        
     Ship_To_Party__c sh=new Ship_To_Party__c();
     sh.Customer_Code__c='abc123';
        sh.External_ID__c = 'abc1231050';
     insert sh;
     
     Business_Partner__c bp=new Business_Partner__c();
     bp.Customer_Code__c='abc123';
        bp.ExternalId__c='abc1231050';
     insert bp;
     
     Order_Request__c odr= new Order_Request__c();
        odr.Account__c=ac.id;
       insert odr;
        system.debug('odr.name****'+odr.name);
        
        
     List<Order__c> orderList=new List<Order__c>();
     order__c ord=new order__c();
      ord.CO_Name__c='Test';
     
      ord.Sold_To_Party__c =ac.Customer_Code__c;
      ord.Shp_To_Party__c=sh.Customer_Code__c;
      ord.Sales_Emp__c= bp.Customer_Code__c;
        ord.Distribution_Channel__c = '10';
        ord.Division__c = '50';
        ord.Order_Request_Number__c='or001';
        ord.Material__c='abc';
        ord.Plant__c='xyz';
      orderList.add(ord);
      insert orderList;
    
    
    
      
    }
}