JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Trade</fullName>
        <active>true</active>
        <label>Trade</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Actuals</label>
    <nameField>
        <displayFormat>ACTL-{0000000000}</displayFormat>
        <label>Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>Hyderabad East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rangareddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mahboobnagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagarkurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gadwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nandyal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KGY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cudappah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prodattur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tirupati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madanappalle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nellore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chirala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vijayawada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machlipatnam</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <formula>Territory__r.Districts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <formula>Dealer_Name__r.Sales_Office_text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipName>Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Target_Child__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <formula>Customer_Name__r.Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <formula>Text(Customer_Name__r.Distribution_Channel__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Distribution Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Targets__c</fullName>
        <label>Targets</label>
        <referenceTo>Targets__c</referenceTo>
        <relationshipLabel>Target Child</relationshipLabel>
        <relationshipName>Target_Child</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Target Child</relationshipLabel>
        <relationshipName>Target_Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Target Child</label>
    <nameField>
        <displayFormat>CTGT-{00000000}</displayFormat>
        <label>Target Child Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Child</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Targets__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Targets</relationshipLabel>
        <relationshipName>Targets1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/targetClass_Test.cls
@isTest
public class targetClass_Test
{
    public static testmethod void targettest()
    {
        List<Target_Child__c> tchdlst = new List<Target_Child__c>();
        Account acc = new Account();
        acc.Name = 'Sample Account';
        acc.Customer_Code__c = '1111';
        acc.Distribution_Channel__c = '10';
        acc.Sales_Office__c = '0000';
        insert acc;
        Account acc1 = new Account();
        acc1.Name = 'Sample Account1';
        acc.Customer_Code__c = '1112';
        acc.Distribution_Channel__c = '10';
        acc1.Sales_Office__c = '0000';
        insert acc1;
        Actuals__c actl = new Actuals__c();
            actl.Product_Group__c = 'PSC';
            actl.Customer_Code__c = '1111';
            actl.Distribution_Channel__c = '10';
            actl.Month__c = 'June';
            actl.Year__c = '2017';
            actl.Target__c = 10;
        insert actl;
        District__c dt = new District__c();
        dt.Territory_Code__c = '0000';
        dt.Name = 'Test';
        insert dt;
        ID dtid = [Select id from District__c limit 1].id;
        Targets__c tgt = new Targets__c();
        tgt.Month__c = 'June';
        tgt.Year__c = '2017';
        tgt.Product_Group__c = 'CHD';
        tgt.Territory__c = dtid;
        insert tgt;
        Targets__c tgt1 = new Targets__c();
        tgt1.Month__c = 'June';
        tgt1.Year__c = '2017';
        tgt1.Product_Group__c = 'OPC';
        tgt1.Territory__c = dt.Id;
        insert tgt1;
        Target_Child__c tchd = new Target_Child__c();
        tchd.Targets__c = tgt.id;
        tchd.Customer_Name__c = acc.Id;
        tchd.Nature__c='Existing';
        tchd.Target__c = 100;
        //tchd.OwnerId = system.UserInfo.getUserId();
        tchd.Territory__c = dt.id;
        tchd.Product_Group__c = 'OPC';
        tchd.Month__c='June';
        tchd.Year__c = '2018';
        tchd.Type__c = 'Trade';
        tchdlst.add(tchd);
        Target_Child__c tchd1 = new Target_Child__c();
        tchd1.Targets__c = tgt.id;
        tchd1.Customer_Name__c = acc1.Id;
        tchd.Nature__c='New';
        tchd1.Target__c = 100;
        tchdlst.add(tchd1);
        insert tchdlst;
        PageReference pageRef = Page.Target_Edit;
        Test.setCurrentPage(pageRef);
        Apexpages.currentpage().getparameters().put('id',tgt.Id);
        Apexpages.currentpage().getparameters().put('rowIndex1','1');
        Apexpages.currentpage().getparameters().put('lookupindex','1');
        ApexPages.StandardController con = new ApexPages.StandardController(tgt);
        targetClass tc = new targetClass(con);
        
        tc.tgt.Territory__c = dtid;
        tc.tgt.Month__c = 'March';
        tc.tgt.Year__c = '2017';
        tc.tgt.Product_Group__c = 'PSC';
        tc.tgtchd[0].Customer_Name__c = acc.Id;
        tc.tgtchd[0].Target__c = 100;
        tc.tgtrec.id = tgt.id;
        tc.saveTo();
        tc.editSave();
        tc.saveTo();
        //tc.tgtrec = tc.tgt;
        tc.cancel();
        tc.myActionInController();
        tc.myActionInControllerEdit();
        tc.deleteRow();
        tc.cloning();
        //tc.saveTo();
        tc.submit();
        tc.edit();
        //tc.editSave();
        tc.addrow();
        
    }
}