JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_text__c</fullName>
        <label>Sales Office text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Daily_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Summary</relationshipLabel>
        <relationshipName>Daily_Sales1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actuals_in_QTY_MT__c</fullName>
        <label>Actuals in QTY(MT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>Plant__c +&apos;:&apos;+ Sales_Office_Description__c +&apos;:&apos;+  Account__r.Customer_Code__c +&apos;:&apos;+  TEXT(Commercial_Invoice_Date__c) +&apos;:&apos;+ Product_Group__c +&apos;:&apos;+  Distribution_Channel__c +&apos;:&apos;+  Division__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <formula>Account__r.Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grand_Total__c</fullName>
        <label>Grand Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Sales Summary</label>
    <nameField>
        <label>Daily Sales  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Name__c</fullName>
        <label>Plant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Code_Target__c</fullName>
        <formula>Customer_Code__c  +&apos;:&apos;+  Distribution_Channel__c  +&apos;:&apos;+  Division__c  +&apos;:&apos;+  Month__c  +&apos;:&apos;+  Year__c  +&apos;:&apos;+  Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Target</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Actuals__c</fullName>
        <label>Dealer Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <formula>Dealer_Name__r.Sales_District_text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchAccountUpdate.cls
global class batchAccountUpdate implements Database.Batchable<sObject> {

    public String qrystr;
    public batchAccountUpdate(String str)
    {
        qrystr = str;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //String query = 'Select id,name,Plant_Name__c,Sales_Office_Description__c,Account__c,Commercial_Invoice_Date_Formula__c,Qty__c from Invoice__c where Commercial_Invoice_Date_Formula__c in (2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31) and Account__c != null';
        String query = qrystr;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) {
        Map<String,Double> invmap = new Map<String,Double>();
        Map<String,String> acmap = new Map<String,String>();
        Map<String,Double> actrgtmap = new Map<String,Double>();
        List<Daily_Sales__c> sslist = new List<Daily_Sales__c>();
        Set<String> accode = new Set<String>();
        for(Invoice__c inv : scope)
        {
            System.debug('------>'+inv);
            accode.add(inv.Sold_To_Code__c+inv.Distribution_Channel__c+inv.Division__c);
            
            if(!actrgtmap.containsKey(inv.Sold_To_Code__c+inv.Distribution_Channel__c+inv.Division__c+inv.Month_of_Commercial_Invoice_Date__c+inv.Year__c+inv.Brand_Short_Form__c))
                actrgtmap.put(inv.Sold_To_Code__c+inv.Distribution_Channel__c+inv.Division__c+inv.Month_of_Commercial_Invoice_Date__c+inv.Year__c+inv.Brand_Short_Form__c,inv.Qty__c);
            else
                actrgtmap.put(inv.Sold_To_Code__c+inv.Distribution_Channel__c+inv.Division__c+inv.Month_of_Commercial_Invoice_Date__c+inv.Year__c+inv.Brand_Short_Form__c,actrgtmap.get(inv.Sold_To_Code__c+inv.Distribution_Channel__c+inv.Division__c+inv.Month_of_Commercial_Invoice_Date__c+inv.Year__c+inv.Brand_Short_Form__c)+inv.Qty__c);
            
            if(!invmap.containsKey(inv.Plant_Short_Form__c+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c))
                invmap.put(inv.Plant_Short_Form__c+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c,inv.Qty__c);
            else
                invmap.put(inv.Plant_Short_Form__c+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c,invmap.get(inv.Plant_Short_Form__c+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c)+inv.Qty__c);
            
            System.debug('------>'+invmap);
            /*if(!invmap.containsKey(inv.Plant_Name__c+':'+inv.Sales_Office_Description__c+':'+inv.Account__c+':'+inv.Commercial_Invoice_Date_Formula__c))
                invmap.put(inv.Plant_Name__c+':'+inv.Sales_Office_Description__c+':'+inv.Account__c+':'+inv.Commercial_Invoice_Date_Formula__c,inv.Qty__c);
            else
                invmap.put(inv.Plant_Name__c+':'+inv.Sales_Office_Description__c+':'+inv.Account__c+':'+inv.Commercial_Invoice_Date_Formula__c,invmap.get(inv.Plant_Name__c+':'+inv.Sales_Office_Description__c+':'+inv.Account__c+':'+inv.Commercial_Invoice_Date_Formula__c)+inv.Qty__c);*/
        }
        sslist = [Select id,Actuals_in_QTY_MT__c,Plant__c,Sales_Office_Description__c,Customer__c,Commercial_Invoice_Date__c,Product_Group__c,Grand_Total__c,Code_Formula__c from Daily_Sales__c where Code_Formula__c IN: invmap.keyset()];
        List<Account> aclist = [Select id,Name,External_ID__c,OwnerId,Owner.FirstName,Owner.LastName,Sales_Office_text__c,Customer_Code__c from Account where External_ID__c IN :accode]; 
        List<Target__c> trgtlst = [Select id,Code_Target__c,Dealer_Actuals__c from Target__c where Code_Target__c IN :actrgtmap.keySet()];
         
        for(Account ac : aclist)
        {
            acmap.put(ac.Customer_Code__c,ac.id);
        }
        
        for(Target__c tgt : trgtlst)
        {
            if(actrgtmap.containsKey(tgt.Code_Target__c))
                tgt.Dealer_Actuals__c = tgt.Dealer_Actuals__c==null ? actrgtmap.get(tgt.Code_Target__c) : tgt.Dealer_Actuals__c+actrgtmap.get(tgt.Code_Target__c);
        }
        
        for(Daily_Sales__c ds : sslist)
        {
            if(invmap.containsKey(ds.Code_Formula__c))
            {
                ds.Grand_Total__c = ds.Grand_Total__c==null ? invmap.get(ds.Code_Formula__c) : ds.Grand_Total__c+invmap.get(ds.Code_Formula__c);
                invmap.remove(ds.Code_Formula__c);
            }
        }
        
        for(String str : invmap.keySet())
        {
            Daily_Sales__c ds=new Daily_Sales__c();
            ds.Plant__c = str.split(':')[0];
            ds.Sales_Office_Description__c = str.split(':')[1];
            if(acmap.containsKey(str.split(':')[2]))
                ds.Account__c = acmap.get(str.split(':')[2]);
            ds.Commercial_Invoice_Date__c = Date.valueOf(str.split(':')[3]);
            ds.Product_Group__c = str.split(':')[4];
            ds.Grand_Total__c=invmap.get(str);
            sslist.add(ds);
        }
        upsert sslist;   
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
}