JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <label>Account Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Nsrs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_channel__c</fullName>
        <label>Distribution channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NSR</label>
    <nameField>
        <displayFormat>N{0000000}</displayFormat>
        <label>Nsr Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/autoPopulateOnNSRTest.cls
@isTest(SeeAllData=True)
public Class autoPopulateOnNSRTest {
    
    public static testMethod  void updateAccount()
    {
     list<String>soids=new list<String>();
        list<Account> acclist=new list<Account>();
     account ac=new account();
     ac.Customer_Code__c='abc';
     ac.Account_Group__c = 'YCSP';
     ac.Distribution_Channel__c = '10'; 
     ac.External_ID__c='abc1231020';
     ac.name='testing';
     acclist.add(ac);
        account ac1=new account();
     ac1.Customer_Code__c='abc';
     ac1.Account_Group__c = 'YCSP';
     ac1.Distribution_Channel__c = '10'; 
     ac1.External_ID__c='abc1050';
     ac1.name='testing';
     acclist.add(ac1);
      insert acclist;
      Nsr__c nsr= new Nsr__c ();
     nsr.Account__c=ac.id;
     nsr.Customer_Code__c=ac.Customer_Code__c;
     nsr.Distribution_Channel__c='10';
       nsr.Division__c='50'; 
     nsr.External_Id__c='abc1050';
	 insert nsr;
     }
}