JSW Devsb/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <externalId>true</externalId>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_text__c</fullName>
        <label>Sales Office text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Daily_Sales__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Summary</relationshipLabel>
        <relationshipName>Daily_Sales1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <formula>Account__r.Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date__c), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Sales Summary</label>
    <nameField>
        <label>Daily Sales  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_T_Value__c</fullName>
        <formula>Total_value__c - (  MMC__c   + BED_Total__c + CGST_Value__c +  CSTT__c +  IGST_Value__c +  SGST_Value__c +  UGST_Value__c +   VAT_Value__c + Freight__c + (NSR_C_F_Value__c *  Qty__c ) +    (( NSR_Other_Discount__c ) - ABS(Additional_Discount__c) ) +  NSR_Packing_Cost__c + (NSR_PD_Value__c *  Qty__c ) + (NSR_PRFT_Value__c *  Qty__c ) + NSR_Rake_Discount__c +  Total_Adhoc_Discount__c )- IF( (Commercial_Invoice_Date_Formula__c &gt;  DATE(2017,04,30) &amp;&amp; Commercial_Invoice_Date_Formula__c &lt; DATE(2017,07,01)   &amp;&amp;  (Brand_Short_Form__c  = &apos;PSC  || CHD&apos;)) ,Discount__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Name__c</fullName>
        <label>Plant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Target__c.object
<CustomObject>
    <fields>
        <fullName>Code_Target__c</fullName>
        <formula>Customer_Code__c  +&apos;:&apos;+  Distribution_Channel__c  +&apos;:&apos;+  Division__c  +&apos;:&apos;+  Month__c  +&apos;:&apos;+  Year__c  +&apos;:&apos;+  Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Target</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Actuals__c</fullName>
        <label>Dealer Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_Actuals__c</fullName>
        <label>NSR Actuals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Days_in_a_Month__c</fullName>
        <label>No of Days in a Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <formula>Dealer_Name__r.Sales_District_text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales District</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Start_Date__c</fullName>
        <label>Target Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Dealer Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchTargetsUpdateDelete.cls
global class batchTargetsUpdateDelete implements Database.Batchable<sObject> {

    public String qrystr;
    public Date myDate;
    public batchTargetsUpdateDelete(String str)
    {
        myDate = System.today()-1;
        //qrystr = str+String.valueOf(myDate).substring(0,10);
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //String query = 'Select id,name,Plant_Name__c,Sales_Office_Description__c,Account__c,Commercial_Invoice_Date_Formula__c,Qty__c from Invoice__c where Commercial_Invoice_Date_Formula__c in (2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31) and Account__c != null';
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) {
        Map<String,Double> invmap = new Map<String,Double>();
        Map<String,String> acmap = new Map<String,String>();
        Map<String,Double> actrgtmap = new Map<String,Double>();
        Map<String,Double> nsrtrgtmap = new Map<String,Double>();
        List<Daily_Sales__c> sslist = new List<Daily_Sales__c>();
        Set<String> accode = new Set<String>();
        List<Invoice__c > invlist = new List<Invoice__c >();
        
        for(Invoice__c inv : scope)
        {
            System.debug('------>'+inv);
            accode.add(inv.Sold_To_Code__c+inv.Distribution_Channel__c+inv.Division__c);
            
            if(inv.Plant__c!='3399')
            if(inv.Distribution_Channel__c == '20' || inv.Distribution_Channel__c == '10' || inv.Distribution_Channel__c == '50')
            if(inv.Brand_Short_Form__c == 'PSC' || inv.Brand_Short_Form__c == 'CHD' || inv.Brand_Short_Form__c == 'GGBS' || inv.Brand_Short_Form__c == 'OPC')
            if(!(inv.Distribution_Channel__c == '20' && inv.Division__c== '50' && inv.Cust_Grp1_from_Master__c!= 'N01-INSTITUTIONS'))
                if(!actrgtmap.containsKey(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c))
                {
                    nsrtrgtmap.put(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.NSR_T_Value__c);
                    actrgtmap.put(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,inv.Qty__c);
                }
                else
                {
                    nsrtrgtmap.put(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,actrgtmap.get(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.NSR_T_Value__c);
                    actrgtmap.put(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c,actrgtmap.get(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Brand_Short_Form__c)+inv.Qty__c);
                }
            
            if(!invmap.containsKey((inv.Plant_Short_Form__c==null?'':inv.Plant_Short_Form__c)+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c))
                invmap.put((inv.Plant_Short_Form__c==null?'':inv.Plant_Short_Form__c)+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c,inv.Qty__c);
            else
                invmap.put((inv.Plant_Short_Form__c==null?'':inv.Plant_Short_Form__c)+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c,invmap.get((inv.Plant_Short_Form__c==null?'':inv.Plant_Short_Form__c)+':'+inv.Sales_District__c+':'+inv.Sold_To_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).substring(0,10)+':'+inv.Brand_Short_Form__c+':'+inv.Distribution_Channel__c+':'+inv.Division__c)+inv.Qty__c);
            
            System.debug('------>'+invmap);
            System.debug('------>'+actrgtmap);
        }
        
        
        List<Account> aclist = [Select id,Name,External_ID__c,OwnerId,Owner.FirstName,Owner.LastName,Sales_Office_text__c,Customer_Code__c from Account where External_ID__c IN :accode]; 
        List<Target__c> trgtlst = [Select id,Code_Target__c,Dealer_Actuals__c from Target__c where Code_Target__c IN :actrgtmap.keySet()];
        
        //map with account code and account id
        for(Account ac : aclist)
        {
            acmap.put(ac.Customer_Code__c,ac.id);
        }
        //Target records to update
        for(Target__c tgt : trgtlst)
        {
            if(actrgtmap.containsKey(tgt.Code_Target__c))
            {
                tgt.Dealer_Actuals__c = 0;
                tgt.NSR_Actuals__c = 0;
                actrgtmap.remove(tgt.Code_Target__c);
                nsrtrgtmap.remove(tgt.Code_Target__c);
            }
        }
        //Target records to insert
        /*for(String str : actrgtmap.keySet())
        {
                Target__c tgt = new Target__c();
                tgt.Customer_Code__c = str.split(':')[0];
                tgt.Distribution_Channel__c = str.split(':')[1];
                tgt.Division__c = str.split(':')[2];
                tgt.Month__c = str.split(':')[3];
                tgt.Year__c = str.split(':')[4];
                tgt.Product__c = str.split(':')[5];
                if(str.split(':')[3]=='January')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),1,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[3]=='February')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),2,1);
                if(math.mod(Integer.valueOf(str.split(':')[4]),4) == 0)
                    tgt.No_of_Days_in_a_Month__c = 29;
                else
                    tgt.No_of_Days_in_a_Month__c = 28;
            }
            if(str.split(':')[3]=='March')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),3,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[3]=='April')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),4,1);
                //tgt.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[3]=='May')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),5,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[3]=='June')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),6,1);
                //tgt.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[3]=='July')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),7,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[3]=='August')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),8,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[3]=='September')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),9,1);
                //tgt.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[3]=='October')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),10,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[3]=='November')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),11,1);
                //tgt.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[3]=='December')
            {
                tgt.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),12,1);
                //tgt.No_of_Days_in_a_Month__c = 31;
            }
                
                tgt.Dealer_Actuals__c = actrgtmap.get(str);
                trgtlst.add(tgt);
        }
        */
        upsert trgtlst;
            
    }   
    
    global void finish(Database.BatchableContext BC) {
    
        batchTargetsUpdate btu = new batchTargetsUpdate(qrystr);
        database.executebatch(btu);
    }
}