JSW Devsb/src/objects/Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Promoter__c</fullName>
        <label>Sales Promoter</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Start_Date__c</fullName>
        <label>Target Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institution</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <formula>Year__c +&apos;:&apos;+ Month__c +&apos;:&apos;+ Distribution_Channel__c +&apos;:&apos;+ Customer_Code__c +&apos;:&apos;+ Sales_Promoter__c +&apos;:&apos;+ Product_Group__c</formula>
        <label>Unique ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Actuals</label>
    <nameField>
        <displayFormat>ACTL-{0000000000}</displayFormat>
        <label>Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Owner:User.EmployeeNumber</formula>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>Hyderabad East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rangareddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mahboobnagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagarkurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gadwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nandyal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KGY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cudappah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prodattur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tirupati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madanappalle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nellore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chirala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vijayawada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machlipatnam</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Owner:User.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Promoter__c</fullName>
        <label>Sales Promoter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TGT_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TGT Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/classes/TargetsUpdate.cls
global class TargetsUpdate implements Database.Batchable<sObject> 
{
    public String qrystr;
    public Date myDate;
    public TargetsUpdate(String str)
    {
        myDate = System.today()-1;
        //qrystr = str+String.valueOf(myDate).substring(0,10);
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        Map<String,Double> invmap1 = new Map<String,Double>();
        Map<String,Double> invmap2 = new Map<String,Double>();
        Map<String,Double> invmap3 = new Map<String,Double>();
        List<Actuals__c> insertactls = new List<Actuals__c>();
        List<Invoice__c> invupdate = new List<Invoice__c>();
        for(Invoice__c inv : scope)
        {
            system.debug('--->inside');
            if(inv.Distribution_Channel__c=='10' || inv.Distribution_Channel__c=='20')
            {
                if(!invmap1.containsKey(inv.Year__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Distribution_Channel__c+':'+inv.Sold_To_Code__c+':'+(inv.Sales_Promoter__c==null?'':inv.Sales_Promoter__c)+':'+inv.Brand_Short_Form__c))
                {
                    inv.TGT_Process__c = true;
                    invmap1.put(inv.Year__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Distribution_Channel__c+':'+inv.Sold_To_Code__c+':'+(inv.Sales_Promoter__c==null?'':inv.Sales_Promoter__c)+':'+inv.Brand_Short_Form__c,inv.Qty__c);
                }
                else
                {
                    inv.TGT_Process__c = true;
                    invmap1.put(inv.Year__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Distribution_Channel__c+':'+inv.Sold_To_Code__c+':'+(inv.Sales_Promoter__c==null?'':inv.Sales_Promoter__c)+':'+inv.Brand_Short_Form__c,invmap1.get(inv.Year__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Distribution_Channel__c+':'+inv.Sold_To_Code__c+':'+(inv.Sales_Promoter__c==null?'':inv.Sales_Promoter__c)+':'+inv.Brand_Short_Form__c)+inv.Qty__c);
                }
            }
            
            /*if(inv.Distribution_Channel__c==20)(inv.Cust_Grp1_from_Master__c==null?'':inv.Cust_Grp1_from_Master__c)+':'
            {
                if(!invmap2.containsKey(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Sales_Promoter__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c))
                    invmap2.put(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Sales_Promoter__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c,inv.Qty__c);
                else
                    invmap2.put(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Sales_Promoter__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c,invmap2.get(inv.Sold_To_Code__c+':'+inv.Distribution_Channel__c+':'+inv.Sales_Promoter__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c)+inv.Qty__c);
            }*/
            
            invupdate.add(inv);
            system.debug('--->'+invmap1);
            system.debug('--->>>'+invupdate);
        }
        
        List<Actuals__c> actls = [Select Id,Actuals__c,Unique_ID__c,Customer_Code__c,Customer_Name__c,Distribution_Channel__c,District__c,Division__c,Employee_ID__c,Month__c,Product_Group__c,State__c,Target_Start_Date__c,Territory__c,Type__c,Year__c from Actuals__c where Unique_ID__c IN: invmap1.keySet()];
        
        for(Actuals__c act : actls)
        {
            if(invmap1.containsKey(act.Unique_ID__c))
            {
                act.Actuals__c = act.Actuals__c==null ? invmap1.get(act.Unique_ID__c) : act.Actuals__c + invmap1.get(act.Unique_ID__c);
                invmap1.remove(act.Unique_ID__c);
            }
        }
        
        for(String str : invmap1.keySet())
        {
            Actuals__c actl = new Actuals__c();
            actl.Year__c = str.split(':')[0];
            actl.Month__c = str.split(':')[1];
            actl.Distribution_Channel__c= str.split(':')[2];
            actl.Customer_Code__c = str.split(':')[3];
            actl.Sales_Promoter__c= str.split(':')[4];
            actl.Product_Group__c = str.split(':')[5];
            actl.Actuals__c = invmap1.get(str);
            insertactls.add(actl);
        }
        Insert insertactls;
        Update actls;
        update invupdate;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
    }
}