JSW Devsb/src/objects/Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Actuals</label>
    <nameField>
        <displayFormat>ACTL-{0000000000}</displayFormat>
        <label>Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/ASM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zonal_Head__c</fullName>
        <label>State Head</label>
        <referenceTo>Zonal_Head__c</referenceTo>
        <relationshipLabel>ASM Targets</relationshipLabel>
        <relationshipName>ASM_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ASM Target</label>
    <nameField>
        <displayFormat>ASM-{0000}</displayFormat>
        <label>ASM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ASM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Basic_Price_Per_MT__c</fullName>
        <label>Basic Price Per MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Basic_Price__c</fullName>
        <label>Total Basic Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Dealer_Target__c.object
<CustomObject>
    <fields>
        <fullName>ASM_Target__c</fullName>
        <label>ASM Target</label>
        <referenceTo>ASM_Targets__c</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Dealer Targets</relationshipLabel>
        <relationshipName>Monthly_Dealer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Actuals__c</fullName>
        <label>Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Dealer Target</label>
    <nameField>
        <displayFormat>MT-{000000}</displayFormat>
        <label>Monthly Target  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Dealer Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Actaul__c</fullName>
        <label>Monthly Actaul</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Dealer_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Dealer Target</label>
        <referenceTo>Monthly_Dealer_Target__c</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Target__c</fullName>
        <label>Monthly Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_short__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Targets</label>
    <nameField>
        <label>Monthly Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State_Head__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>State_Head</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zonal Head</label>
    <nameField>
        <displayFormat>ZH-{00000}</displayFormat>
        <label>Zonal Head Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zonal Head</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Zonal_Head__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Head__c</fullName>
        <label>State Head</label>
        <referenceTo>State_Head__c</referenceTo>
        <relationshipName>Zonal_Head</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State Head</label>
    <nameField>
        <displayFormat>SH-{00000}</displayFormat>
        <label>State Head Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Head</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/actualsUpdateTest.cls
@isTest
public class actualsUpdateTest 
{
    public static testmethod void invtest()
    {
        Date myDate = System.today();
        State_Head__c sh = new State_Head__c(Date__c=myDate);insert sh;
        Zonal_Head__c zh = new Zonal_Head__c(Date__c=myDate,State_Head__c=sh.id);insert zh;
        ASM_Targets__c asm = new ASM_Targets__c(Date__c=myDate,Zonal_Head__c=zh.id);insert asm;
        Account ac = new Account(name='test');
        insert ac;
        Monthly_Dealer_Target__c mdt = new Monthly_Dealer_Target__c();
        mdt.Target_Date__c = mydate;
        mdt.Products__c = 'PSC';
        mdt.ASM_Target__c = asm.id;
        mdt.Actuals__c = 10.00;
        mdt.Quantity__c = 10.00;
        insert mdt;
        Monthly_Targets__c mt = new Monthly_Targets__c();
        mt.Monthly_Dealer_Target__c = mdt.id;
        mt.Dealer__c = ac.id;
        mt.Product_short__c = 'PSC';
        mt.Monthly_Target__c = 10.00;
        mt.Monthly_Actaul__c = 10.00;
        mt.Quantity__c = 10.00;
         insert mt;
        Monthly_Targets__c mt1 = new Monthly_Targets__c();
        mt1.Monthly_Dealer_Target__c = mdt.id;
        mt1.Dealer__c = ac.id;
        mt1.Product_short__c = 'PSC';
        mt1.Monthly_Target__c = 10.00;
        mt1.Monthly_Actaul__c = 10.00;
        mt1.Quantity__c = 10.00;
         insert mt1;
        Invoice__c inv = new Invoice__c();
        inv.Account__c = ac.id;
        inv.Basic_Price_Per_MT__c = 20.00;
        inv.Brand_Short_Form__c = 'PSC';
        inv.qty__c = 10;
        inv.Commercial_Invoice_Date__c = myDate;
        inv.Total_Basic_Price__c = 10.00;
        insert inv;
    }
}