JSW Devsb/src/objects/Adhoc_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Adhoc Incentives</relationshipLabel>
        <relationshipName>Adhoc_Incentives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Adhoc Incentive</label>
    <nameField>
        <label>Adhoc Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adhoc Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Districts__c.object
<CustomObject>
    <fields>
        <fullName>District_Category__c</fullName>
        <label>District Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Districts</label>
    <nameField>
        <label>Districts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DIstricts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/classes/AdhocValues_Test.cls
@isTest
public class AdhocValues_Test 
{
    public static testmethod void adhocdisttest()
    {
        Districts__c dst = new Districts__c();
        dst.District_Code__c = 'abcdst';
        dst.Name = 'test dst';
        dst.District_Category__c = 'A';
        insert dst;
        
        Adhoc_Incentive__c ad = new Adhoc_Incentive__c();
        ad.District_Code__c = 'abcdst';
        insert ad;
    }
}