JSW Devsb/src/objects/Adhoc_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Adhoc Incentive</label>
    <nameField>
        <label>Adhoc Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adhoc Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Customer_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Incentive</label>
    <nameField>
        <label>Customer Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>District_Actuals_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>District Actuals Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Discount_Value__c</fullName>
        <label>Invoice Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Road_Invoice__c</fullName>
        <formula>IF( Shipping_Type__c =&apos;Rail transport&apos;,false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Road Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <formula>Account__r.Sales_Office__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Office Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice_Discounts__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Discount_Value__c</fullName>
        <label>Invoice Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Discounts</relationshipLabel>
        <relationshipName>Invoice_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Discounts</label>
    <nameField>
        <label>Invoice Discounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_C_F_Value_Changes__c.object
<CustomObject>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MFG_Plant__c</fullName>
        <label>MFG Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Storage_Location__c</fullName>
        <label>Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>NSR C&amp;F Value Changes</label>
    <nameField>
        <label>NSR C&amp;F Value Changes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR C&amp;F Value Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_Other_Values__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Other_Value__c</fullName>
        <label>Other Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>distribution_Channel__c</fullName>
        <label>distribution Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>NSR Other Values</label>
    <nameField>
        <displayFormat>Other-{000000000}</displayFormat>
        <label>NSR Other Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR Other Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PD_Values__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PD_Value__c</fullName>
        <label>PD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>distribution_Channel__c</fullName>
        <label>distribution Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>NSR PD Values</label>
    <nameField>
        <label>NSR PD Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR PD Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PRFT_Values__c.object
<CustomObject>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MFG_Plant__c</fullName>
        <label>MFG Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRFT_Value__c</fullName>
        <label>PRFT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Storage_Location__c</fullName>
        <label>Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR PRFT Values</label>
    <nameField>
        <displayFormat>PRFT-{00000000}</displayFormat>
        <label>NSR PRFT Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR PRFT Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchCalls.cls
public class batchCalls
{
    public date fromdate{set;get;}
    public date todate{set;get;}
    public String classnames{set;get;}
    public String convertparam{set;get;}
    public boolean tobeprocessed{set;get;}
    public String dc{set;get;}
    public String prod{set;get;}
    public String salesdistrict{set;get;}
    public String soldcode{set;get;}
    public String plant{set;get;}
    public String plantshrt{set;get;}
    public String sloc{set;get;}
    public String salesofccode{set;get;}
    public String shptodist{set;get;}
    public String statcode{set;get;}
    
    public void defaultvals()
    {
        dc = 'None';
        prod = 'None';
        salesdistrict = null;
        soldcode = null;
        plant = null;
        plantshrt = null;
        sloc = null;
        statcode = null;
        shptodist = null;
        salesofccode = null;
    }
    public pagereference runbatch()
    {
        system.debug('1'+fromdate);
        system.debug('2'+todate);
        system.debug('3'+classnames);
        system.debug('4'+tobeprocessed);
        if(classnames=='PDClass')
        {
            String query = 'Select district_code__c,Product__c,distribution_Channel__c,From_Date__c,To_Date__c,PD_Value__c,To_Be_Processed__c from NSR_PD_Values__c where From_Date__c>='+String.valueOf(fromdate).substring(0,10)+' AND To_Date__c<='+String.valueOf(todate).substring(0,10)+' AND To_Be_Processed__c='+tobeprocessed+'';
            if(prod != 'None')
                query = query + ' AND Product__c = \''+prod+'\'';
            if(dc != 'None')
                query = query + ' AND distribution_Channel__c = \''+dc+'\'';
            if(!String.isBlank(salesdistrict))
                query = query + ' AND district_code__c = \''+salesdistrict+'\'';
            system.debug('query'+query);
            NSRPDValues bat = new NSRPDValues(query);
            Database.executeBatch(bat,1); 
        }
        else if(classnames=='OtherClass')
        {
            String query = 'Select distribution_Channel__c,District_Code__c,From_Date__c,Other_Value__c,Product__c,To_Be_Processed__c,To_Date__c from NSR_Other_Values__c where From_Date__c>='+String.valueOf(fromdate).substring(0,10)+' AND To_Date__c<='+String.valueOf(todate).substring(0,10)+' AND To_Be_Processed__c='+tobeprocessed+'';
            if(prod != 'None')
                query = query + ' AND Product__c = \''+prod+'\'';
            if(dc != 'None')
                query = query + ' AND distribution_Channel__c = \''+dc+'\'';
            if(!String.isBlank(salesdistrict))
                query = query + ' AND district_code__c = \''+salesdistrict+'\'';
            NSROtherValues bat = new NSROtherValues(query);
            Database.executeBatch(bat,1);
        }
        else if(classnames=='PRFTClass')
        {
            String query = 'Select From_Date__c,MFG_Plant__c,Plant__c,PRFT_Value__c,Product__c,Storage_Location__c,To_Be_Processed__c,To_Date__c from NSR_PRFT_Values__c where From_Date__c>='+String.valueOf(fromdate).substring(0,10)+' AND To_Date__c<='+String.valueOf(todate).substring(0,10)+' AND To_Be_Processed__c='+tobeprocessed+'';
            if(prod != 'None')
                query = query + ' AND Product__c = \''+prod+'\'';
            if(!String.isBlank(plantshrt))
                query = query + ' AND MFG_Plant__c = \''+plantshrt+'\'';
            if(!String.isBlank(plant))
                query = query + ' AND Plant__c = \''+plant+'\'';
            NSRPRFTValues bat = new NSRPRFTValues(query);
            Database.executeBatch(bat,1);
        }
        else if(classnames=='CFClass')
        {
            String query = 'Select From_Date__c,MFG_Plant__c,Plant__c,Product__c,Storage_Location__c,To_Be_Processed__c,To_Date__c,Value__c from NSR_C_F_Value_Changes__c where From_Date__c>='+String.valueOf(fromdate).substring(0,10)+' AND To_Date__c<='+String.valueOf(todate).substring(0,10)+' AND To_Be_Processed__c='+tobeprocessed+'';
            if(prod != 'None')
                query = query + ' AND Product__c = \''+prod+'\'';
            if(!String.isBlank(plant))
                query = query + ' AND Plant__c = \''+plant+'\'';
            if(!String.isBlank(sloc))
                query = query + ' AND Storage_Location__c = \''+sloc+'\'';
            NSRCFValues bat = new NSRCFValues(query);
            Database.executeBatch(bat,1);
        }
        else if(classnames=='CIClass')
        {
            String query = 'Select Customer_Code__c,Distribution_Channel__c,District_Code__c,From_Date__c,Product__c,To_Date__c,To_Be_Processed__c,Value__c from Customer_Incentive__c where From_Date__c>='+String.valueOf(fromdate).substring(0,10)+' AND To_Date__c<='+String.valueOf(todate).substring(0,10)+' AND To_Be_Processed__c='+tobeprocessed+'';
            if(prod != 'None')
                query = query + ' AND Product__c = \''+prod+'\'';
            if(dc != 'None')
                query = query + ' AND distribution_Channel__c = \''+dc+'\'';
            if(!String.isBlank(soldcode))
                query = query + ' AND Customer_Code__c = \''+soldcode+'\'';
            NSRCIValues bat = new NSRCIValues(query);
            Database.executeBatch(bat,1);
        }
        else if(classnames=='AdhocClass')
        {
            String query = 'Select district_code__c,Product__c,distribution_Channel__c,From_Date__c,To_Date__c,Value__c,To_Be_Processed__c from Adhoc_Incentive__c where From_Date__c>='+String.valueOf(fromdate).substring(0,10)+' AND To_Date__c<='+String.valueOf(todate).substring(0,10)+' AND To_Be_Processed__c='+tobeprocessed+'';
            if(prod != 'None')
                query = query + ' AND Product__c = \''+prod+'\'';
            if(dc != 'None')
                query = query + ' AND distribution_Channel__c = \''+dc+'\'';
            if(!String.isBlank(salesdistrict))
                query = query + ' AND district_code__c = \''+salesdistrict+'\'';
            NSRAdhocValues bat = new NSRAdhocValues(query);
            Database.executeBatch(bat,1);
        }
        else if(classnames=='IDClass')
        {
            String query = 'Select Commercial_Invoice_Number__c,Invoice_Discount_Value__c,To_Be_Processed__c from Invoice_Discounts__c where To_Be_Processed__c='+tobeprocessed+'';
            NSRIDValues bat = new NSRIDValues(query);
            Database.executeBatch(bat);
        }
        else if(classnames=='DistrictActualsClass')
        {
            String query = 'Select Distribution_Channel__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,District_Actuals_Process__c,Qty__c,Road_Invoice__c,Depot_Invoice__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'CHD\' OR Brand_Short_Form__c=\'OPC\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\'';
            System.debug('----'+query);
            if(prod != 'None')
                query = 'Select Distribution_Channel__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,District_Actuals_Process__c,Qty__c,Road_Invoice__c,Depot_Invoice__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\'';
            /*if(!String.isBlank(salesofccode))
                query = 'Select Distribution_Channel__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,District_Actuals_Process__c,Qty__c,Road_Invoice__c,Depot_Invoice__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'CHD\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\' AND Sales_Office_Code__c=\''+salesofccode+'\'';
            if(prod != 'None' && !String.isBlank(salesofccode))
                query = 'Select Distribution_Channel__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,District_Actuals_Process__c,Qty__c,Road_Invoice__c,Depot_Invoice__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\' AND Sales_Office_Code__c=\''+salesofccode+'\'';*/
            DistrictActualsDelete distact = new DistrictActualsDelete(query); //ur batch class
            Database.executebatch(distact); 
  
        }
        else if(classnames=='DistrictNSRClass')
        {
            String query = 'Select Distribution_Channel__c,Qty__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'CHD\' OR Brand_Short_Form__c=\'OPC\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\'';
            System.debug('----'+query);
            if(prod != 'None')
                query = 'Select Distribution_Channel__c,Qty__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c= \''+prod+'\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\'';
            /*if(!String.isBlank(salesofccode))
                query = 'Select Distribution_Channel__c,Qty__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'CHD\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\' AND Sales_Office_Code__c=\''+salesofccode+'\'';
            if(prod != 'None' && !String.isBlank(salesofccode))
                query = 'Select Distribution_Channel__c,Qty__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c= \''+prod+'\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c!=\'13\' AND Sales_Office_Code__c=\''+salesofccode+'\'';*/
            NSRDelete nsr = new NSRDelete(query); //ur batch class
            database.executebatch(nsr,100);   
        }
        else if(classnames=='StateActualsClass')
        {
            String query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,State_Actuals_Process__c,Qty__c,Road_Invoice__c,Depot_Invoice__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' and Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'OPC\' OR Brand_Short_Form__c=\'GGBS\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') ';
            System.debug('----'+query);
            if(prod != 'None')
                query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\')';
            if(!String.isBlank(statcode))
                query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'OPC\' OR Brand_Short_Form__c=\'GGBS\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\''+statcode+'\'';
            if(prod != 'None' && !String.isBlank(statcode))
                query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\''+statcode+'\'';
            System.debug('----'+query);
            StateActualsDelete bat1 = new StateActualsDelete(query);
            Database.executeBatch(bat1,100); 
        }
        else if(classnames=='StateNSRClass')
        {
            String query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'OPC\' OR Brand_Short_Form__c=\'GGBS\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\')';
            System.debug('----'+query);
            if(prod != 'None')
                query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\')';
            if(!String.isBlank(statcode))
                query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'OPC\' OR Brand_Short_Form__c=\'GGBS\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\''+statcode+'\'';
            if(prod != 'None' && !String.isBlank(statcode))
                query = 'Select Distribution_Channel__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Qty__c,State_Code__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,NSR_Targets_Processed__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\''+statcode+'\'';
            System.debug('----'+query);
            StateNSRDelete nsr = new StateNSRDelete(query); //ur batch class
            database.executebatch(nsr,100); 
        }
        else if(classnames=='MHClass')
        {
            String query = 'Select Distribution_Channel__c,Ship_To_District__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,Qty__c,MH_Actuals_Processed__c,Road_Invoice__c,Depot_Invoice__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'CHD\' OR Brand_Short_Form__c=\'OPC\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\'13\'';
            if(prod != 'None')
                query = 'Select Distribution_Channel__c,Ship_To_District__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,Qty__c,MH_Actuals_Processed__c,Road_Invoice__c,Depot_Invoice__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\'13\'';
            /*if(!String.isBlank(shptodist))
                query = 'Select Distribution_Channel__c,Ship_To_District__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,Qty__c,MH_Actuals_Processed__c,Road_Invoice__c,Depot_Invoice__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\'PSC\' OR Brand_Short_Form__c=\'CHD\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\'13\' AND Ship_To_District__c=\''+shptodist+'\'';
            if(prod != 'None' && !String.isBlank(shptodist))
                query = 'Select Distribution_Channel__c,Ship_To_District__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,Qty__c,MH_Actuals_Processed__c,Road_Invoice__c,Depot_Invoice__c,NSR_T_Value__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+' AND (Brand_Short_Form__c=\''+prod+'\') AND Cust_Grp1_from_Master__c!=\'N01-Institutions\' AND (Distribution_Channel__c=\'10\' OR Distribution_Channel__c=\'20\' OR Distribution_Channel__c=\'50\') AND State_Code__c=\'13\' AND Ship_To_District__c=\''+shptodist+'\'';*/
            System.debug('----'+query);
            MaharashtraActualsDelete distact = new MaharashtraActualsDelete(query); //ur batch class
            database.executebatch(distact,100); 
        }
        else if(classnames=='DistTargets')
        {
            String query = 'Select Brand_Short_Form__c,Distribution_Channel__c,Division__c,Sales_District__c,Month_of_Commercial_Invoice_Date__c,Year__c,District_Inv_Process__c,Qty__c,Cust_Grp1_from_Master__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+'';
            if(prod != 'None')
                query = query + ' AND Brand_Short_Form__c = \''+prod+'\'';
            batchDistrictUpdateDelete bat = new batchDistrictUpdateDelete(query); //ur batch class
            database.executebatch(bat);    
        }
        else if(classnames=='CustTargets')
        {
            String query = 'Select Sold_To_Code__c,Distribution_Channel__c,Division__c,Plant__c,Brand_Short_Form__c,Cust_Grp1_from_Master__c,Month_of_Commercial_Invoice_Date__c,Year__c,Qty__c,Invoice_Processed__c,Plant_Short_Form__c,Sales_District__c,Commercial_Invoice_Date_Formula__c from Invoice__c where Commercial_Invoice_Date_Formula__c>='+String.valueOf(fromdate).substring(0,10)+' AND Commercial_Invoice_Date_Formula__c<='+String.valueOf(todate).substring(0,10)+'';
            System.debug('----'+query);
            if(prod != 'None')
                query = query + ' AND Brand_Short_Form__c = \''+prod+'\'';
            batchTargetsUpdateDelete bat = new batchTargetsUpdateDelete(query); //ur batch class
            database.executebatch(bat);        
        }
        else if(classnames=='Staging')
        {
            StagingConvert stgcon = new StagingConvert('RecordType.Name = \'Visit\' and Master__c != null and (NOT Master__c LIKE \'a1S%\') LIMIT 30');
        }
        
        if(classnames=='Staging'){
            return null;
        } else {
            pagereference pr = new pagereference('/apexpages/setup/listAsyncApexJobs.apexp?setupid=AsyncApexJobs&retURL=%2Fui%2Fsetup%2FSetup%3Fsetupid%3DJobs&thePage%3AtheTemplate%3Aj_id18%3Afcf=00B2800000AmLCp');
            pr.setRedirect(false);
            return pr;
        }
        
    }
}