JSW Devsb/src/objects/Adhoc_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>District_Code__c +&apos;:&apos;+Product__c+&apos;:&apos;+ Distribution_Channel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Adhoc Incentive</label>
    <nameField>
        <label>Adhoc Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adhoc Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Customer_Incentive__c.object
<CustomObject>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>District_Code__c +&apos;:&apos;+ CASESAFEID(Customer__c)+&apos;:&apos;+ Product__c +&apos;:&apos;+ Distribution_Channel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <label>Customer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Incentive</label>
    <nameField>
        <label>Customer Incentive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plant_Name__c</fullName>
        <label>Plant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLOC__c</fullName>
        <defaultValue>&quot;FG01&quot;</defaultValue>
        <label>SLOC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice_Discounts__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Discounts</relationshipLabel>
        <relationshipName>Invoice_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Discounts</label>
    <nameField>
        <label>Invoice Discounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_C_F_Value_Changes__c.object
<CustomObject>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>Plant__c +&apos;:&apos;+  Storage_Location__c +&apos;:&apos;+ Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MFG_Plant__c</fullName>
        <label>MFG Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Storage_Location__c</fullName>
        <label>Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>NSR C&amp;F Value Changes</label>
    <nameField>
        <label>NSR C&amp;F Value Changes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR C&amp;F Value Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_Other_Values__c.object
<CustomObject>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>District_Code__c +&apos;:&apos;+ Product__c+&apos;:&apos;+distribution_Channel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Other_Value__c</fullName>
        <label>Other Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>distribution_Channel__c</fullName>
        <label>distribution Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>NSR Other Values</label>
    <nameField>
        <displayFormat>Other-{000000000}</displayFormat>
        <label>NSR Other Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR Other Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PD_Values__c.object
<CustomObject>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>District_Code__c +&apos;:&apos;+ Product__c+&apos;:&apos;+distribution_Channel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PD_Value__c</fullName>
        <label>PD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>distribution_Channel__c</fullName>
        <label>distribution Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>NSR PD Values</label>
    <nameField>
        <label>NSR PD Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR PD Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PRFT_Values__c.object
<CustomObject>
    <fields>
        <fullName>Code_Formula__c</fullName>
        <formula>MFG_Plant__c +&apos;:&apos;+Plant__c +&apos;:&apos;+  Storage_Location__c +&apos;:&apos;+ Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MFG_Plant__c</fullName>
        <label>MFG Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRFT_Value__c</fullName>
        <label>PRFT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Storage_Location__c</fullName>
        <label>Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR PRFT Values</label>
    <nameField>
        <displayFormat>PRFT-{00000000}</displayFormat>
        <label>NSR PRFT Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR PRFT Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/NSRCalculations.cls
global class NSRCalculations implements Database.Batchable<sObject> {

    public String qrystr;
    public Date myDate;
    public NSRCalculations(String str)
    {
        myDate = System.today()-1;
        //qrystr = str+String.valueOf(myDate).substring(0,10);
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //String query = 'Select id,name,Plant_Name__c,Sales_Office_Description__c,Account__c,Commercial_Invoice_Date_Formula__c,Qty__c from Invoice__c where Commercial_Invoice_Date_Formula__c in (2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31) and Account__c != null';
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        Set<String> DistProd = new Set<String>();
        Set<String> CustIncv = new Set<String>();
        Set<String> MfgPlntSLoc = new Set<string>();
        Set<String> PlntSLoc = new Set<string>();
        Set<String> cominvnumb = new Set<string>();
        List<Invoice__c > invlist = new List<Invoice__c >();
        
        for(Invoice__c inv : scope)
        {
            DistProd.add(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Distribution_channel__c);
            MfgPlntSLoc.add(inv.Plant_Short_Form__c+':'+inv.Plant__c+':'+inv.SLOC__c+':'+inv.Brand_Short_Form__c);
            PlntSLoc.add(inv.Plant__c+':'+inv.SLOC__c+':'+inv.Brand_Short_Form__c);
            CustIncv.add(inv.Sold_To_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.distribution_Channel__c);
            cominvnumb.add(inv.Commercial_Invoice_Number__c);
        }
        System.debug('----->'+DistProd);
        List<NSR_PD_Values__c> nsrpdvalues = [Select Code_Formula__c,From_Date__c,PD_Value__c,distribution_Channel__c,district_code__c,Product__c,To_Date__c from NSR_PD_Values__c where Code_Formula__c IN: DistProd];
        List<NSR_Other_Values__c> nsrothrvalues = [Select distribution_Channel__c,Code_Formula__c,From_Date__c,Other_Value__c,district_code__c,Product__c,To_Date__c from NSR_Other_Values__c where Code_Formula__c IN: DistProd];
        List<NSR_PRFT_Values__c> nsrprftvalues = [Select Code_Formula__c,From_Date__c,PRFT_Value__c,Plant__c,Product__c,To_Date__c,Storage_Location__c,MFG_Plant__c from NSR_PRFT_Values__c where Code_Formula__c IN: MfgPlntSLoc];
        List<NSR_C_F_Value_Changes__c> nsrcfvalues = [Select Code_Formula__c,From_Date__c,Value__c,Plant__c,Product__c,To_Date__c,Storage_Location__c,MFG_Plant__c from NSR_C_F_Value_Changes__c where Code_Formula__c IN: PlntSLoc];
        List<Adhoc_Incentive__c> adhocvalues = [Select Code_Formula__c,From_Date__c,Value__c,distribution_Channel__c,district_code__c,Product__c,To_Date__c from Adhoc_Incentive__c where Code_Formula__c IN: DistProd];
        List<Customer_Incentive__c> custvalues = [Select Customer_Code__c,Customer__c,Code_Formula__c,From_Date__c,Value__c,distribution_Channel__c,district_code__c,Product__c,To_Date__c from Customer_Incentive__c where Code_Formula__c IN: CustIncv];
        List<Invoice_Discounts__c> invdiscs = [Select Commercial_Invoice_Number__c,Invoice_Discount_Value__c from Invoice_Discounts__c where Commercial_Invoice_Number__c IN: cominvnumb];
        System.debug('----->'+nsrpdvalues);
        for(Invoice__c inv : scope)
        {
            for(NSR_PD_Values__c pd : nsrpdvalues)
            {
                if(inv.Sales_District__c == pd.district_code__c && inv.distribution_Channel__c==pd.distribution_Channel__c && inv.Brand_Short_Form__c == pd.Product__c && inv.Commercial_Invoice_Date_Formula__c >= pd.From_Date__c && inv.Commercial_Invoice_Date_Formula__c <= pd.To_Date__c)
                {
                    System.debug('---Enter1---');
                    inv.NSR_PD_Value__c = pd.PD_Value__c;
                }
                    
            }
            
            for(NSR_Other_Values__c pd : nsrothrvalues)
            {
                if(inv.Sales_District__c == pd.district_code__c && inv.Brand_Short_Form__c == pd.Product__c && inv.distribution_Channel__c==pd.distribution_Channel__c && inv.Commercial_Invoice_Date_Formula__c >= pd.From_Date__c && inv.Commercial_Invoice_Date_Formula__c <= pd.To_Date__c)
                {
                    System.debug('---Enter2---');
                    inv.NSR_Other_Value__c = pd.Other_Value__c;
                }
                    
            }
            
            for(NSR_PRFT_Values__c pd : nsrprftvalues)
            {
                if(inv.Plant_Short_Form__c == pd.MFG_Plant__c && inv.Brand_Short_Form__c == pd.Product__c && inv.Plant__c == pd.Plant__c && inv.SLOC__c == pd.Storage_Location__c && inv.Commercial_Invoice_Date_Formula__c >= pd.From_Date__c && inv.Commercial_Invoice_Date_Formula__c <= pd.To_Date__c)
                {
                    System.debug('---Enter3---');
                    inv.NSR_PRFT_Value__c = pd.PRFT_Value__c;
                }
                    
            }
            
            for(NSR_C_F_Value_Changes__c pd : nsrcfvalues)
            {
                if(inv.Plant__c == pd.Plant__c && inv.Brand_Short_Form__c == pd.Product__c && inv.SLOC__c == pd.Storage_Location__c && inv.Commercial_Invoice_Date_Formula__c >= pd.From_Date__c && inv.Commercial_Invoice_Date_Formula__c <= pd.To_Date__c)
                {
                    System.debug('---Enter4---');
                    inv.NSR_C_F_Value__c = pd.Value__c;
                }
                    
            }
            
            for(Adhoc_Incentive__c pd : adhocvalues)
            {
                if(inv.Sales_District__c == pd.district_code__c && inv.Brand_Short_Form__c == pd.Product__c && inv.distribution_Channel__c == pd.Distribution_Channel__c && inv.Commercial_Invoice_Date_Formula__c >= pd.From_Date__c && inv.Commercial_Invoice_Date_Formula__c <= pd.To_Date__c)
                {
                    System.debug('---Enter5---');
                    inv.Adhoc_Incentive_Value__c = pd.Value__c;
                }
                    
            }
            
            for(Customer_Incentive__c pd : custvalues)
            {
                if(inv.Sold_To_Code__c == pd.Customer_Code__c && inv.Brand_Short_Form__c == pd.Product__c && inv.distribution_Channel__c == pd.Distribution_Channel__c && inv.Commercial_Invoice_Date_Formula__c >= pd.From_Date__c && inv.Commercial_Invoice_Date_Formula__c <= pd.To_Date__c)
                {
                    System.debug('---Enter6---');
                    inv.Customer_Incentive_Value__c = pd.Value__c;
                }
                    
            }
            
            for(Invoice_Discounts__c pd : invdiscs)
            {
                if(inv.Commercial_Invoice_Number__c== pd.Commercial_Invoice_Number__c)
                {
                    System.debug('---Enter7---');
                    inv.Invoice_Discount_Value__c = pd.Invoice_Discount_Value__c;
                }
                    
            }
            inv.Invoice_NSR_Processed__c = True;
            invlist.add(inv);
        }
        Update invlist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        
    }
}