JSW Devsb/src/objects/Area__c.object
<CustomObject>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week Plan</label>
        <referenceTo>Week_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Type</label>
        <referenceTo>Customer_Types__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>Account__r.Name + Lead__r.FirstName + Lead__r.MiddleName + Lead__r.LastName +  TEXT(Event__r.Type_of_Meet__c) + Area__r.Name +  Business_Partner__r.Name +  Project_Site__r.Name +  Influencer__r.Name +  Territory__r.Name  + Depot__r.Name +
IF( AND(  OR( Account__c == null, Account__c == &apos;&apos;)  ,
          OR( Lead__c == null, Lead__c == &apos;&apos;)  ,
          OR( Event__c == null, Event__c == &apos;&apos;)  ,
          OR( Area__c == null, Area__c == &apos;&apos;)  ,
          OR( Business_Partner__c == null, Business_Partner__c == &apos;&apos;)  ,
          OR( Project_Site__c == null, Project_Site__c == &apos;&apos;)  ,
          OR( Influencer__c == null, Influencer__c == &apos;&apos;) ,
          OR( Territory__c == null, Territory__c == &apos;&apos;) ),
               General_Visit_Type__c , &apos;&apos;)</formula>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Past__c</fullName>
        <formula>IF( Planned_Date__c &lt;  TODAY() , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Past</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visited</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Week_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Week Plan</relationshipLabel>
        <relationshipName>Week_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Week Plan</label>
    <nameField>
        <label>Week Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Week Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/WeekPlanController.cls
public class WeekPlanController{
    public List<Visit__c> dailyVstList {get; set;}
    public Week_Plan__c wplan {get; set;}
    public String weekid {get; set;}
    public Boolean flag {get; set;}
    
    public WeekPlanController(ApexPages.StandardController controller){
        weekid = ApexPages.currentPage().getParameters().get('id');
        wplan = [select id,name,Start_Date__c,End_Date__c,Month_Plan__c,Status__c from Week_Plan__c where id =: weekid];
        dailyVstList = [select id,Name__c,Planned_Date__c,Visited__c,Past__c,Account__c,Lead__c,Event__c,Customer_Type__c,Area__c from Visit__c where Day_Plan__r.Week_Plan__c =: weekid];
        flag = dailyVstList.isEmpty();
    }
    
    public pageReference pjptab(){
        Schema.DescribeSObjectResult PJPDest = Month_Plan__c.sObjectType.getDescribe();
        pageReference pref = new pageReference('/'+PJPDest.getKeyPrefix()+'/o');
        pref.setRedirect(true);
        return pref;
    }
    
    public pageReference monthtab(){
        pageReference pref = new pageReference('/'+wplan.Month_Plan__c);
        pref.setRedirect(true);
        return pref;
    }
    
    public pageReference directApprove(){
        Approval.ProcessWorkitemRequest[] prWkItems = New Approval.ProcessWorkItemRequest[]{};
            
            ProcessInstance[] pi = [Select ID, Status, TargetObject.Name, 
                                        (SELECT Id, ActorId, ProcessInstanceId FROM Workitems),
                                        (SELECT Id, StepStatus, Comments FROM Steps) From ProcessInstance Where TargetObjectID =:weekid AND Status = 'Pending'];
            
            for(ProcessInstance instance : pi){
                for(ProcessInstanceWorkItem workItem : instance.WorkItems){
                    Approval.ProcessWorkitemRequest prWkItem = new Approval.ProcessWorkitemRequest();
                    
                    prWkItem.setWorkItemID(workItem.id);
                    prWkItem.setComments('Approved by ' + userInfo.getName());
                    prWkItem.setAction('Approve');
                    prWkItems.add(prWkItem);
                  
                }
            }          
            
            if(!prWkItems.isEmpty()){
                Approval.ProcessResult[] appResult = Approval.process(prWkItems);
            }
            
            PageReference pref = new PageReference('/'+weekid);
            pref.setRedirect(true);
            return pref;
    }
    
    public pageReference directReject(){
        String wrkitmid;
        Approval.ProcessWorkitemRequest[] prWkItems = New Approval.ProcessWorkItemRequest[]{};
            
            ProcessInstance[] pi = [Select ID, Status, TargetObject.Name, 
                                        (SELECT Id, ActorId, ProcessInstanceId FROM Workitems),
                                        (SELECT Id, StepStatus, Comments FROM Steps) From ProcessInstance Where TargetObjectID =:weekid AND Status = 'Pending'];
            for(ProcessInstance instance : pi){
                for(ProcessInstanceWorkItem workItem : instance.WorkItems){
                    wrkitmid = String.valueOf(workItem.id);
                }
            }
            PageReference pref = new PageReference('/p/process/ProcessInstanceWorkitemWizardStageManager?id='+wrkitmid);
            pref.setRedirect(true);
            return pref;
    }
}