JSW Devsb/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Market_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Details of Competitor Activities</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Market Information</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Information</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Market Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Information JSW</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Marketing_Info__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BP_Min__c</fullName>
        <label>BP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Information</label>
        <referenceTo>Market_Information__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSP_Min__c</fullName>
        <label>RSP Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WSP_Min__c</fullName>
        <label>WSP Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price Reading</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Marketing Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Reading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Information</label>
        <referenceTo>Market_Information__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/MarketInfoInsert.cls
@RestResource(urlMapping='/MarketInfoInsert/*')
global with sharing class MarketInfoInsert{

  @HttpPost
    global static void doPost(MarketInfoWrapper marketInfoWrapper) {
       Market_Information__c l=new Market_Information__c();
       l.Account__c=marketInfoWrapper.account;
       l.Lead__c=marketInfoWrapper.lead;
       l.Territory__c=marketInfoWrapper.territory;    
       l.Comments__c=marketInfoWrapper.comments;    
       l.Visit__c=marketInfoWrapper.visit;
       l.ownerId=marketInfoWrapper.owner;
       insert l;
       
       Marketing_Info__c mInfo = new Marketing_Info__c();
        mInfo.Brand__c=marketInfoWrapper.brand;
        mInfo.Products__c=marketInfoWrapper.product;
        mInfo.WSP_Min__c=marketInfoWrapper.wsp;
        mInfo.RSP_Min__c=marketInfoWrapper.rsp;
        mInfo.BP_Min__c=marketInfoWrapper.bp;
        mInfo.Account__c=marketInfoWrapper.account;
        mInfo.Market_Information__c=l.id;
        insert mInfo;
       
       }
       
       global class MarketInfoWrapper {
       String  account{get; set;}
       String lead{get; set;}
       String territory{get; set;}
       String comments{get; set;}
       String brand{get; set;}
       String  product{get; set;}
       Double  wsp{get; set;}
       Double  rsp{get; set;}
       Double  bp{get; set;}
       String  visit{get; set;}
       global String  owner{get; set;}
       }
}