JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Engineers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder office</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Promoter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middleman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>End_Customer_Name__c</fullName>
        <label>End Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Business_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Partner</label>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Influencer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Influencer</label>
        <referenceTo>Influencer__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF( Account__c != null, &apos;Account&apos;, &apos;&apos;) + 
 IF( Depot__c != null, &apos;Depot&apos;, &apos;&apos;) + 
 IF( Area__c != null , &apos;Area&apos;, &apos;&apos;) +
 IF( Business_Partner__c != null , &apos;Business Partner&apos;, &apos;&apos;) +
 IF( Customer_Type__c != null , &apos;Customer Type&apos;, &apos;&apos;) +
 IF( Event__c != null , &apos;Event&apos;, &apos;&apos;) +
 IF( Influencer__c != null , &apos;Influencer&apos;, &apos;&apos;) +
 IF( Lead__c != null , &apos;Lead&apos;, &apos;&apos;) +
 IF( Project_Site__c != null , &apos;Project Site&apos;, &apos;&apos;) +
 IF( Territory__c != null , &apos;Territory&apos;, &apos;&apos;) +
 IF( General_Visit__c = true , &apos;General&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/VisitCheckIn_Test.cls
@isTest
public class VisitCheckIn_Test {
    public static testmethod void unitTest(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser){
            Profile sfp = [select id,name from Profile where name = 'JSW SO'];
            UserRole sfrl = [select id,name from UserRole where name = 'Vijayawada SO'];
            User curusr = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_IN', ProfileId = sfp.Id, UserRoleId = sfrl.id,
                TimeZoneSidKey='Asia/Kolkata', UserName='standardmnguser@testorg.com');
            insert curusr;
            
            Account acc = new Account();
            acc.Name = 'Sample Account';
            insert acc;
            
            Lead ld = new Lead();
            ld.LastName = 'Sample Lead';
            ld.Company = 'Sample Company';
            insert ld;
            
            Business_Partner__c bp = new Business_Partner__c();
            insert bp;
            
            Influencer__c inf = new Influencer__c();
            insert inf;
            
            Project_Site__c prj = new Project_Site__c();
            prj.Type__c = 'Project Sites';
            prj.End_Customer_Name__c = 'Sample End Customer';
            insert prj;
            
            Day_Plan__c dp = new Day_Plan__c();
            dp.Date__c = system.today();
            dp.Ownerid = curusr.id;
            insert dp;
            
            Visit__c vst = new Visit__c();
            vst.Planned_Date__c = system.today();
            vst.OwnerId = curusr.id;
            insert vst;
            
            VisitCheckIn.VisitWraper vstv = new VisitCheckIn.VisitWraper();
            vstv.potentiallead = false;
            
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            req.httpMethod = 'POST';
            RestContext.request = req;
            RestContext.response = res;
            String result = VisitCheckIn.doPost(vstv,vst.id);
        }        
    }
}