JSW Devsb/src/objects/Business_Partner__c.object
<CustomObject>
    <label>Business Partner</label>
    <nameField>
        <label>Business Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Influencer__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Engineers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Consultants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder office</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Influencer</label>
    <nameField>
        <label>Influencer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Influencers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Promoter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middleman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>End_Customer_Name__c</fullName>
        <label>End Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/VisitInsert_Test.cls
@isTest
public class VisitInsert_Test {
    public static testmethod void unitTest(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser){
            Profile sfp = [select id,name from Profile where name = 'JSW SO'];
            UserRole sfrl = [select id,name from UserRole where name = 'Vijayawada SO'];
            User curusr = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_IN', ProfileId = sfp.Id, UserRoleId = sfrl.id,
                TimeZoneSidKey='Asia/Kolkata', UserName='standardmnguser@testorg.com');
            insert curusr;
            
            Account acc = new Account();
            acc.Name = 'Sample Account';
            insert acc;
            
            Lead ld = new Lead();
            ld.LastName = 'Sample Lead';
            ld.Company = 'Sample Company';
            insert ld;
            
            Business_Partner__c bp = new Business_Partner__c();
            insert bp;
            
            Influencer__c inf = new Influencer__c();
            insert inf;
            
            Project_Site__c prj = new Project_Site__c();
            prj.Type__c = 'Project Sites';
            prj.End_Customer_Name__c = 'Sample End Customer';
            insert prj;
            
            Day_Plan__c dp = new Day_Plan__c();
            dp.Date__c = system.today();
            dp.Ownerid = curusr.id;
            insert dp;
            
            VisitInsert.VisitWraperIns vstvpacc = new VisitInsert.VisitWraperIns();
            vstvpacc.plandate = system.today();
            vstvpacc.accid = acc.id;
            VisitInsert.VisitWraperIns vstvpld = new VisitInsert.VisitWraperIns();
            vstvpld.plandate = system.today();
            vstvpld.leadid = ld.id;
            VisitInsert.VisitWraperIns vstvpbp = new VisitInsert.VisitWraperIns();
            vstvpbp.plandate = system.today();
            vstvpbp.bpid = bp.id;
            VisitInsert.VisitWraperIns vstvpinf = new VisitInsert.VisitWraperIns();
            vstvpinf.plandate = system.today();
            vstvpinf.infid = inf.id;
            VisitInsert.VisitWraperIns vstvpprj = new VisitInsert.VisitWraperIns();
            vstvpprj.plandate = system.today();
            vstvpprj.prjid = prj.id;
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            req.httpMethod = 'POST';
            RestContext.request = req;
            RestContext.response = res;
            String result = VisitInsert.doPost(vstvpacc,curusr.id);
            result = VisitInsert.doPost(vstvpld,curusr.id);
            result = VisitInsert.doPost(vstvpbp,curusr.id);
            result = VisitInsert.doPost(vstvpinf,curusr.id);
            result = VisitInsert.doPost(vstvpprj,curusr.id);
        }        
    }
}