JSW Devsb/src/objects/Customer_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Month_of_Year__c</fullName>
        <label>Month of Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Ledger</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Customer Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Ledgers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/DeleteCustomerLedgerPreviousScheduled.cls
global class DeleteCustomerLedgerPreviousScheduled implements Schedulable{
  
    global void execute(SchedulableContext sc){
    Integer Year = Date.Today().Year();
    Integer month = Date.Today().Month()-1;
   
        Map<Integer,String>MonthMap2 = new Map<Integer,String>();
         MonthMap2.put(1,'January');
        MonthMap2.put(2,'February');
        MonthMap2.put(3,'March');
        MonthMap2.put(4,'April');
        MonthMap2.put(5,'May');
        MonthMap2.put(6,'June');
        MonthMap2.put(7,'July');
        MonthMap2.put(8,'August');
        MonthMap2.put(9,'September');
        MonthMap2.put(10,'October');
        MonthMap2.put(11,'November');
        MonthMap2.put(12,'December');
       String monthOfYear=MonthMap2.get(month);
 
       String query = 'select id from Customer_Ledger__c where Month_of_Year__c=\'' + monthOfYear + '\''+' And Year__c=' + Year ;
        DeleteCustomerLedgerPrevious delBatch = new DeleteCustomerLedgerPrevious(query);
       
         Id BatchProcessId = Database.ExecuteBatch(delBatch);

   
    }
}