JSW Devsb/src/objects/Customer_Ledger__c.object
<CustomObject>
    <fields>
        <fullName>Last_Date__c</fullName>
        <formula>DATE
(
	YEAR(  Post_Date_Formula__c),
	Month( Post_Date_Formula__c),
	CASE( MONTH(Post_Date_Formula__c), 
		1, 31, 
		2, IF( MOD( YEAR(Post_Date_Formula__c), 4) = 0, 29, 28), 
		3, 31, 
		4, 30, 
		5, 31, 
		6, 30, 
		7, 31, 
		8, 31, 
		9, 30, 
		10, 31, 
		11, 30, 
		12, 31, 
		0 
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_of_Year__c</fullName>
        <label>Month of Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Customer Ledger</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Customer Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Ledgers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/deleteCustomerLedgerScheduled.cls
global class deleteCustomerLedgerScheduled implements Schedulable{
   /* global static void scheduleMe(String mode)
  {
    deleteCustomerLedgerScheduled msc = new deleteCustomerLedgerScheduled();
    String sch = '00 00 12 * * ?'; // base this on mode or whatever your params are
    String jobID = system.schedule('DepotStock Job', sch, msc);
  }
   */
    global void execute(SchedulableContext sc){
    Integer Year = Date.Today().Year();
    Integer month = Date.Today().Month();
   
        Map<Integer,String>MonthMap2 = new Map<Integer,String>();
         MonthMap2.put(1,'January');
        MonthMap2.put(2,'February');
        MonthMap2.put(3,'March');
        MonthMap2.put(4,'April');
        MonthMap2.put(5,'May');
        MonthMap2.put(6,'June');
        MonthMap2.put(7,'July');
        MonthMap2.put(8,'August');
        MonthMap2.put(9,'September');
        MonthMap2.put(10,'October');
        MonthMap2.put(11,'November');
        MonthMap2.put(12,'December');
       String monthOfYear=MonthMap2.get(month);
  /*      
    if(month==1)
    {
    monthOfYear='January';
    }else if(month==2)
    {
    monthOfYear='February';
    }else if(month==3)
    {
    monthOfYear='March';
    }
    else if(month==4)
    {
    monthOfYear='April';
    system.debug('monthOfYear:'+monthOfYear);
    }
    else if(month==5)
    {
    monthOfYear='May';
    }
    else if(month==6)
    {
    monthOfYear='June';
    }
    else if(month==7)
    {
    monthOfYear='July';
    }
    else if(month==8)
    {
    monthOfYear='August';
    }
    else if(month==9)
    {
    monthOfYear='September';
    }else if(month==10)
    {
    monthOfYear='October';
    }else if(month==11)
    {
    monthOfYear='November';
    }else if(month==12)
    {
    monthOfYear='December';
    }*/

        //String query = 'select id from Customer_Ledger__c where Last_Date__c !=yesterday';
      //String query = 'select id from Customer_Ledger__c where Month_of_Year__c='+monthOfYear+' And Year__c='+Year;
       String query = 'select id from Customer_Ledger__c where Month_of_Year__c=\'' + monthOfYear + '\''+' And Year__c=' + Year ;
        DeleteCustomerLedger delBatch = new DeleteCustomerLedger(query);
        //delBatch.deleteCustLed();
         Id BatchProcessId = Database.ExecuteBatch(delBatch);

   //Database.Execute(delBatch);
    }
}