JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Week_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Week Plan</label>
        <referenceTo>Week_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Week_Plan_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Week Plan Submitted</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Week_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>Week Plan</label>
    <nameField>
        <label>Week Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Week Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/updatevisitsTest.cls
@isTest
public class updatevisitsTest
{
public static testmethod void weekPlan()
{
    Set<String> wpsubids = new Set<String>();
    Set<String> wpunsubids = new Set<String>();
    Set<String> dpids = new Set<String>();
    List<Day_Plan__c> dplist = new List<Day_Plan__c>(); 
User u = [select firstname from user where id=:userinfo.getuserid()];
Account ac=new Account();
ac.Name='Acc';
insert ac;

Week_Plan__c WP=new Week_Plan__c();
WP.name='test';
WP.Start_Date__c=system.today();
WP.End_Date__c=system.today()+7;
Wp.Submitted_for_Approval__c =true;
WP.Status__c='Submitted';
insert WP;
    /*Week_Plan__c WP1=new Week_Plan__c();
WP1.name='test';
WP1.Start_Date__c=system.today();
WP1.End_Date__c=system.today()+7;
Wp1.Submitted_for_Approval__c =true;
WP1.Status__c='Approved';
insert WP1;*/
wpsubids.add(wp.id);
Day_Plan__c dp=new Day_Plan__c();
dp.Name='day';
    dp.Week_Plan__c = WP.Id;
insert dp;

Visit__c vc=new Visit__c();
vc.Account__c=ac.id;
vc.Week_Plan_Submitted__c=true;
vc.Day_Plan__c=dp.id;
insert vc;
    Week_Plan__c wkpln = [select id,Status__c,Submitted_for_Approval__c,End_Date__c,Start_Date__c,name from Week_Plan__c where id = :WP.id];
    wkpln.name = 'test edit';
        update wkpln;
    }
}