JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Market_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Market Information</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Information</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Market Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Information JSW</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Marketing_Info__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Marketing_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Information</label>
        <referenceTo>Market_Information__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Market_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price Reading</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Marketing Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Reading</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Market_Information_Count__c</fullName>
        <label>Market Information Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Reading_Count__c</fullName>
        <label>Price Reading Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Visits_Check_In_Planned__c</fullName>
        <label>Total No of Visits Check-In (Planned)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_No_of_Visits_Planned__c</fullName>
        <label>Total No of Visits (Planned)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_no_of_Visits_Unplanned__c</fullName>
        <label>Total no of Visits (Unplanned)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <recordTypes>
        <fullName>PJP</fullName>
        <active>true</active>
        <label>PJP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Information_Count__c</fullName>
        <label>Market Information Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Information</label>
        <referenceTo>Market_Information__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Planned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Reading_Count__c</fullName>
        <label>Price Reading Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchPJPReportTest.cls
@isTest
public class batchPJPReportTest {
    public static testmethod void unitTest(){
        Account acc = new Account();
        acc.Name = 'Sample Account';
        insert acc;
        
        Month_Plan__c pjp = new Month_Plan__c();
        insert pjp;
        
        /*Month_Plan__c pjp1 = new Month_Plan__c();
        insert pjp1;
        
        Month_Plan__c pjp2 = new Month_Plan__c();
        insert pjp2;
        
        Month_Plan__c pjp3 = new Month_Plan__c();
        insert pjp3;*/
        
        Day_Plan__c dp = new Day_Plan__c();
        dp.Month_Plan__c = pjp.id;
        insert dp;
        
        /*Day_Plan__c dp1 = new Day_Plan__c();
        dp1.Month_Plan__c = pjp1.id;
        insert dp1;
        
        Day_Plan__c dp2 = new Day_Plan__c();
        dp2.Month_Plan__c = pjp2.id;
        insert dp2;*/
        
        Visit__c vst = new Visit__c();
        vst.Day_Plan__c = dp.id;
        insert vst;
        
        Visit__c vst1 = new Visit__c();
        vst1.Day_Plan__c = dp.id;
        insert vst1;
        
        Visit__c vst2 = new Visit__c();
        vst2.Day_Plan__c = dp.id;
        vst2.Planned__c = true;
        vst2.Check_In__c = 'sample';
        insert vst2;
        
        Visit__c vst3 = new Visit__c();
        vst3.Name = 'Some text here';
        vst3.Day_Plan__c = dp.id;
        vst3.Check_In__c = 'sample';
        vst3.Account__c = acc.id;
        vst3.Planned_Date__c = system.today();
        insert vst3;
        
        /*Visit__c vst4 = new Visit__c();
        vst4.Day_Plan__c = dp1.id;
        vst4.Planned__c = true;
        vst4.Check_In__c = 'sample';
        insert vst4;
        
        Visit__c vst5 = new Visit__c();
        vst5.Name = 'Some text here';
        vst5.Day_Plan__c = dp2.id;
        vst5.Check_In__c = 'sample';
        vst5.Account__c = acc.id;
        vst5.Planned_Date__c = system.today();
        insert vst5;*/
        
        Market_Information__c mkt = new Market_Information__c();
        mkt.Visit__c = vst.id;
        insert mkt;
        
        Market_Information__c mkt1 = new Market_Information__c();
        mkt1.Visit__c = vst.id;
        insert mkt1;
        
        Marketing_Info__c mkinf = new Marketing_Info__c();
        mkinf.Market_Information__c = mkt.id;
        insert mkinf;
        
        Test.startTest();
        batchPJPReport pjprep = new batchPJPReport('select id,name,Total_No_of_Visits_Planned__c,Total_No_of_Visits_Check_In_Planned__c,Total_no_of_Visits_Unplanned__c,Market_Information_Count__c,Price_Reading_Count__c from Month_Plan__c where RecordType.Name = \'PJP\'');
    	Database.executeBatch(pjprep,1);
        Test.stopTest();
    }
}