JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Day Plan</relationshipLabel>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <recordTypes>
        <fullName>PJP</fullName>
        <active>true</active>
        <label>PJP</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Staging__c.object
<CustomObject>
    <fields>
        <fullName>App_Version__c</fullName>
        <label>App Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_of_Godown__c</fullName>
        <label>Condition of Godown</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Master_Id__c</fullName>
        <label>External Master Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>userid__c</fullName>
        <label>userid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Staging</label>
    <nameField>
        <label>Staging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_of_Godown__c</fullName>
        <label>Condition of Godown</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not as per ISP</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <label>Master</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/StagingConvertTest.cls
@isTest
public class StagingConvertTest {
    public static testmethod void unitTest(){
        Month_Plan__c pjp = new Month_Plan__c();
        insert pjp;
        Day_Plan__c dp = new Day_Plan__c();
        dp.Date__c = system.today();
        dp.Month_Plan__c = pjp.id;
        insert dp;
        Visit__c vst = new Visit__c();
        vst.Planned_Date__c = system.today();
        insert vst;
        
        Staging__c stg = new Staging__c();
        stg.Check_In__c = 'Check In Time';
        stg.userid__c = 'Sample';
        stg.App_Version__c = 'Sample App Version';
        stg.External_Master_Id__c = 'Sample External Master';
        stg.Planned_Date__c = system.today()+1;
        insert stg;
        
        Staging__c stg1 = new Staging__c();
        stg1.Check_In__c = 'Check In Time';
        stg1.userid__c = vst.id;
        stg1.App_Version__c = 'Sample App Version';
        stg1.External_Master_Id__c = 'Sample External Master';
        insert stg1;
        
        Staging__c stg2 = new Staging__c();
        stg2.Check_In__c = 'Check In Time';
        stg2.userid__c = vst.id;
        stg2.Condition_of_Godown__c = 'Very Bad';
        stg2.App_Version__c = 'Sample App Version';
        stg2.External_Master_Id__c = 'Sample External Master';
        insert stg2;
        StagingConvert stgcon = new StagingConvert('Check_In__c != null');
    }
}