JSW Devsb/src/objects/Day_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Day_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Day Plan</label>
    <nameField>
        <label>Day Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Day Plan</label>
        <referenceTo>Day_Plan__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Customer_Influencer__c</fullName>
        <label>Name of Customer/ Influencer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Customer_Influencer__c</fullName>
        <label>Type of Customer/ Influencer</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eng</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing house</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others ( descriptive)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit_Report__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Visit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_influencer_Email_ID__c</fullName>
        <label>Customer/influencer Email ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_influencer_Mobile_No__c</fullName>
        <label>Customer/influencer  Mobile No</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name_of_Customer_Influencer__c</fullName>
        <label>Name of  Customer/ Influencer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Customer_Influencer__c</fullName>
        <label>Type of Customer/ Influencer</label>
        <picklist>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eng</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing house</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others ( descriptive)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Visit_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DCR</label>
    <nameField>
        <displayFormat>UV-{0000}</displayFormat>
        <label>Visit Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/createUnplanedVisitTest.cls
@istest
public class createUnplanedVisitTest 
{
    public static testmethod void unplnvst()
    {
        
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Visit_Report__c' and Name = 'Daily Call Report'].Id;
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standard123@testorg123.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser123@test123.com');
        
        System.runAs(u){
        Date myDate = system.today();
        Account ac = new Account(name='test');
        insert ac;
        Day_Plan__c dp = new Day_Plan__c(name='test dp',Date__c=myDate,User__c=u.id);
        insert dp;
        Visit__c vst = new Visit__c();
        vst.Account__c = ac.id;
        insert vst;
        Visit_Report__c vrp = new Visit_Report__c();
        vrp.Visit__c = vst.Id;
        //vrp.RecordTypeId = strRecordTypeId;
        vrp.Name_of_Customer_Influencer__c = 'test infln';
        vrp.Customer_influencer_Email_ID__c = 'test@test.com';
        vrp.Customer_influencer_Mobile_No__c = '9999999999';
        vrp.Type_of_Customer_Influencer__c = 'Eng';
        insert vrp;
        Visit_Report__c vrp1 = new Visit_Report__c();
        vrp1.Account__c = ac.id;
        vrp1.Name_of_Customer_Influencer__c = 'test inflncr';
        vrp1.Customer_influencer_Email_ID__c = 'test1@test1.com';
        vrp1.Customer_influencer_Mobile_No__c = '8888888888';
        vrp1.Type_of_Customer_Influencer__c = 'Architect';
        insert vrp1;
    }
    }
}