JSW Devsb/src/objects/Delivery__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Delivery</relationshipLabel>
        <relationshipName>Delivery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Booking_Line__c.object
<CustomObject>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipName>Order_Booking_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order request Line Item</label>
    <nameField>
        <displayFormat>ORL{000000000}</displayFormat>
        <label>Order Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order request Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Code/Depot Code</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address3__c</fullName>
        <label>Address3</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address4__c</fullName>
        <label>Address4</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alt_Tax_Class__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>Alt Tax Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contracts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contracts</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3</booleanFilter>
            <filterItems>
                <field>Order__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <filterItems>
                <field>Order__c.SO_Type__c</field>
                <operation>equals</operation>
                <value>YQC</value>
            </filterItems>
            <filterItems>
                <field>Order__c.Month_Of_STO_Date__c</field>
                <operation>equals</operation>
                <valueField>$Source.Month_Of_Date__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_Time__c</fullName>
        <formula>LEFT(RIGHT(text( CreatedDate),9),8)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Created Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Available__c</fullName>
        <label>Credit Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Outstanding__c</fullName>
        <label>Credit Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Overdue__c</fullName>
        <label>Credit Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <label>Customer Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Nmae__c</fullName>
        <formula>Account__r.Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Description__c</fullName>
        <label>Distribution Channel</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Description__c</fullName>
        <label>Division</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INC_Name__c</fullName>
        <formula>INC__r.Customer_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>INC Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INC</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Business_Partner__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>MMC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Order Requests (INC)</relationshipLabel>
        <relationshipName>Order_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inco_Terms__c</fullName>
        <label>Inco Terms</label>
        <picklist>
            <picklistValues>
                <fullName>FOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FO2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EX</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MMCCode__c</fullName>
        <formula>MMCName__r.SAP_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MMC Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MMCName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MMC</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Business_Partner__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>MMC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Business_Partner__c</referenceTo>
        <relationshipLabel>Order Requests (MMC)</relationshipLabel>
        <relationshipName>Order_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_Of_Date__c</fullName>
        <label>Month Of Date</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Request_Header__c</fullName>
        <externalId>true</externalId>
        <label>Order Request Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Type</label>
        <referenceTo>Order_Type__c</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Type_Name__c</fullName>
        <formula>Order_Type1__r.Order_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>YQC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YORF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YCOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YEXC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YFCL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YSEZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YORD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YNFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YGB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>YCL</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Oreder_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Po_Number__c</fullName>
        <label>Po Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Customer Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{0000000000}</displayFormat>
        <label>Order Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Type__c.object
<CustomObject>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Type__c</fullName>
        <label>Order Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Type</label>
    <nameField>
        <label>Order Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Ship_To_Party__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To Party</relationshipLabel>
        <relationshipName>Ship_To_Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Ship To Party</label>
    <nameField>
        <label>Ship To Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To Party</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/viewOrderRequestDetails.cls
public class viewOrderRequestDetails{
    public String id{get;set;}
    public Order_Request__c orderRequest{get;set;}
    public Order_Booking_Line__c orderBookingLine{get;set;}
        public viewOrderRequestDetails(ApexPages.StandardController controller){
          id=ApexPages.currentPage().getParameters().get('id');
          system.debug('@@ID'+id);
          orderRequest=[select id,Name,Address1__c,Address2__c,Address3__c,Address4__c, Alt_Tax_Class__c,Contact_Number__c, Contracts__c,Created_Date__c,Created_Time__c,Credit_Available__c,Credit_Outstanding__c,Credit_Overdue__c,Customer_Address__c,Customer_Nmae__c,Account__c,Sales_District__c,Distribution_Channel_Description__c,Distribution_Channel__c,Division_Description__c,Division__c,INC__c,INC_Name__c,Inco_Terms__c,MMCName__c, MMCCode__c, Month_Of_Date__c,Oreder_Error__c,Order_Request_Header__c,Order_Type1__c,Order_Type__c,Order_Type_Name__c,Po_Number__c,Quantity__c,Sales_Employee__c,Sales_Org__c,Sales_Promoter_Name__c,Sales_Promotor__c,Sap_No__c,Shipment_Address__c,Shipment_Type__c,Ship_to_Code__c,Ship_To_Party__c,Ship_To_Party_Nmae__c,SalesDistrictShipto__c, So_Number__c,Status__c, Satus_Message__c,Sub_Dealer__c,SubDealer_Name__c,Tax_Type__c from Order_Request__c where id=:id];
          orderBookingLine=[select id,Creation_Date__c,Creation_Time__c,Delivery__c, Material_Code1__c,Material_Code__c, Material_CodeName__c,Order_Error__c,Order_Request__c,Order_Request_Line__c,Order_Request_Name__c,Packing_Type__c,Plant__c,Price__c,Quantity__c,remove__c,rowNO__c,SFDC_Product_Code__c,So_Item_Number__c,SO_Number__c,Status__c,Status_Message__c,Test__c from Order_Booking_Line__c where Order_Request__r.id=:id];
      
    }
   public pagereference editPage(){
    id=ApexPages.currentPage().getParameters().get('id');
    system.debug('@@@id'+id);
    PageReference editPage= new pagereference('https://jswcements--jswdevsb--c.cs57.visual.force.com/apex/editOrderRequestDetails?id='+id);
           editPage.setRedirect(true);
         return editPage; 
   }
}