JSW Devsb/src/objects/District_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Code_DT__c</fullName>
        <formula>District_Code__c +&apos;:&apos;+ Product_Group__c +&apos;:&apos;+ Month__c +&apos;:&apos;+ Division__c +&apos;:&apos;+ Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Code DT</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Non_Trade_Actuals__c</fullName>
        <label>District Non Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District_Trade_Actuals__c</fullName>
        <label>District Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GGBS_Actuals__c</fullName>
        <label>GGBS Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Institutional_Actuals__c</fullName>
        <label>Institutional Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Days_in_a_Month__c</fullName>
        <label>No of Days in a Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEZ_Actuals__c</fullName>
        <label>District SEZ Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Start_Date__c</fullName>
        <label>Target Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Targets__c</fullName>
        <label>Targets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>District Targets</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>District Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>District Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>District_Inv_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>District Inv Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Targets__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_Start_Date__c</fullName>
        <formula>DATE( VALUE( TEXT(Year__c) ) , 
CASE( TEXT(Month__c), 
&quot;January&quot;, 1, 
&quot;February&quot;, 2,
&quot;March&quot;, 3,
&quot;April&quot;, 4,
&quot;May&quot;, 5,
&quot;June&quot;, 6,
&quot;July&quot;, 7,
&quot;August&quot;, 8,
&quot;September&quot;, 9,
&quot;October&quot;, 10,
&quot;November&quot;, 11,
12) ,1)</formula>
        <label>Target Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Targets</label>
    <nameField>
        <displayFormat>TRGT-{0000000000}</displayFormat>
        <label>Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchDistrictUpdateDelete.cls
global class batchDistrictUpdateDelete implements Database.Batchable<sObject> 
{
    public String qrystr;
    public Date myDate;
    public batchDistrictUpdateDelete(String str)
    {
        myDate = System.today()-1;
        //qrystr = str+String.valueOf(myDate).substring(0,10);
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        Map<String,Double> dstrgtmap = new Map<String,Double>();
        Map<String,Double> dstrgtmap1 = new Map<String,Double>();
        Map<String,Double> dstrgtmap2 = new Map<String,Double>();
        Map<String,Double> dstrgtmap3 = new Map<String,Double>();
        Map<String,Double> dstrgtmap4 = new Map<String,Double>();
        List<Invoice__c > invlist = new List<Invoice__c >();
        List<District_Targets__c> dstgtlst = new List<District_Targets__c>();
        for(Invoice__c inv : scope)
        {
            if(inv.Brand_Short_Form__c == 'PSC' || inv.Brand_Short_Form__c == 'CHD')
            {
            if(inv.Distribution_Channel__c == '10' && (inv.Division__c == '50' || inv.Division__c == '53'))
                if(!dstrgtmap.containsKey(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c))
                {
                    dstrgtmap.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,inv.Qty__c);
                }
                else
                {
                    dstrgtmap.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,dstrgtmap.get(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c)+inv.Qty__c);
                }
            
            /*if((inv.Distribution_Channel__c == '20' || inv.Distribution_Channel__c == '50') && (inv.Division__c == '50' || inv.Division__c == '53') && inv.Cust_Grp1_from_Master__c == 'N01-INSTITUTIONS')
                if(!dstrgtmap1.containsKey(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c))
                    dstrgtmap1.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,inv.Qty__c);
                else
                    dstrgtmap1.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,dstrgtmap1.get(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c)+inv.Qty__c);*/
            
            if(inv.Distribution_Channel__c == '20' && (inv.Division__c == '50' || inv.Division__c == '53') && inv.Cust_Grp1_from_Master__c != 'N01-INSTITUTIONS')
                if(!dstrgtmap2.containsKey(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c))
                {
                    dstrgtmap2.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,inv.Qty__c);
                }
                else
                {
                    dstrgtmap2.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,dstrgtmap2.get(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c)+inv.Qty__c);
                }
            
            if(inv.Distribution_Channel__c == '50' && (inv.Division__c == '50' || inv.Division__c == '53') && inv.Cust_Grp1_from_Master__c != 'N01-INSTITUTIONS')
                if(!dstrgtmap4.containsKey(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c))
                {
                    dstrgtmap4.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,inv.Qty__c);
                }
                else
                {
                    dstrgtmap4.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,dstrgtmap4.get(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c)+inv.Qty__c);
                }
            /*if(inv.Division__c == '52')
                if(!dstrgtmap3.containsKey(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c))
                    dstrgtmap3.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,inv.Qty__c);
                else
                    dstrgtmap3.put(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c,dstrgtmap3.get(inv.Sales_District__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Division__c+':'+inv.Year__c)+inv.Qty__c);*/
            
            //inv.District_Inv_Process__c = true;
            }
            System.debug('------>'+dstrgtmap);
        }
        
        List<District_Targets__c> dstgtlst1 = [Select id,Distribution_Channel__c,SEZ_Actuals__c,District_Code__c,GGBS_Actuals__c,District_Non_Trade_Actuals__c,District_Trade_Actuals__c,Institutional_Actuals__c,Division__c,Month__c,Product_Group__c,Targets__c,Code_DT__c,Target_Start_Date__c,No_of_Days_in_a_Month__c from District_Targets__c where Code_DT__c IN: dstrgtmap.keySet() OR Code_DT__c IN: dstrgtmap2.keySet() OR Code_DT__c IN: dstrgtmap4.keySet()];
        
        //District Targets Update
        for(District_Targets__c dt : dstgtlst1)
        {
            if(dstrgtmap.containsKey(dt.Code_DT__c))
            {
                dt.District_Trade_Actuals__c = 0;
                dstrgtmap.remove(dt.Code_DT__c);
            }
            /*if(dstrgtmap1.containsKey(dt.Code_DT__c))
            {
                dt.Institutional_Actuals__c = dt.Institutional_Actuals__c ==null ? dstrgtmap1.get(dt.Code_DT__c) : dt.Institutional_Actuals__c + dstrgtmap1.get(dt.Code_DT__c);
                dstrgtmap1.remove(dt.Code_DT__c);
            }*/
            if(dstrgtmap2.containsKey(dt.Code_DT__c))
            {
                dt.District_Non_Trade_Actuals__c = 0;
                dstrgtmap2.remove(dt.Code_DT__c);
            }
            /*if(dstrgtmap3.containsKey(dt.Code_DT__c))
            {
                dt.GGBS_Actuals__c = dt.GGBS_Actuals__c ==null ? dstrgtmap3.get(dt.Code_DT__c) : dt.GGBS_Actuals__c + dstrgtmap3.get(dt.Code_DT__c);
                dstrgtmap3.remove(dt.Code_DT__c);
            }*/
            if(dstrgtmap4.containsKey(dt.Code_DT__c))
            {
                dt.SEZ_Actuals__c = 0;
                dstrgtmap4.remove(dt.Code_DT__c);
            }
        }
        //District Targets Insert
        /*for(String str : dstrgtmap.keySet())
        {
            District_Targets__c dst = new District_Targets__c();
            dst.District_Code__c = str.split(':')[0];
            dst.Product_Group__c = str.split(':')[1];
            dst.Month__c = str.split(':')[2];
            dst.Division__c = str.split(':')[3];
            dst.Year__c = str.split(':')[4];
            if(str.split(':')[2]=='January')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),1,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='February')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),2,1);
                if(math.mod(Integer.valueOf(str.split(':')[4]),4) == 0)
                    dst.No_of_Days_in_a_Month__c = 29;
                else
                    dst.No_of_Days_in_a_Month__c = 28;
            }
            if(str.split(':')[2]=='March')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),3,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='April')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),4,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='May')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),5,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='June')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),6,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='July')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),7,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='August')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),8,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='September')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),9,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='October')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),10,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='November')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),11,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='December')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),12,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            dst.District_Trade_Actuals__c = dstrgtmap.get(str);
            dstgtlst.add(dst);
        }*/
        /*for(String str : dstrgtmap1.keySet())
        {
            District_Targets__c dst = new District_Targets__c();
            dst.District_Code__c = str.split(':')[0];
            dst.Product_Group__c = str.split(':')[1];
            dst.Month__c = str.split(':')[2];
            dst.Division__c = str.split(':')[3];
            dst.Year__c = str.split(':')[4];
            dst.Institutional_Actuals__c = dstrgtmap1.get(str);
            dstgtlst.add(dst);
        }*/
        /*for(String str : dstrgtmap2.keySet())
        {
            District_Targets__c dst = new District_Targets__c();
            dst.District_Code__c = str.split(':')[0];
            dst.Product_Group__c = str.split(':')[1];
            dst.Month__c = str.split(':')[2];
            dst.Division__c = str.split(':')[3];
            dst.Year__c = str.split(':')[4];
            if(str.split(':')[2]=='January')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),1,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='February')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),2,1);
                if(math.mod(Integer.valueOf(str.split(':')[4]),4) == 0)
                    dst.No_of_Days_in_a_Month__c = 29;
                else
                    dst.No_of_Days_in_a_Month__c = 28;
            }
            if(str.split(':')[2]=='March')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),3,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='April')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),4,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='May')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),5,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='June')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),6,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='July')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),7,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='August')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),8,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='September')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),9,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='October')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),10,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='November')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),11,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='December')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),12,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            dst.District_Non_Trade_Actuals__c = dstrgtmap2.get(str);
            dstgtlst.add(dst);
        }*/
        /*for(String str : dstrgtmap3.keySet())
        {
            District_Targets__c dst = new District_Targets__c();
            dst.District_Code__c = str.split(':')[0];
            dst.Product_Group__c = str.split(':')[1];
            dst.Month__c = str.split(':')[2];
            dst.Division__c = str.split(':')[3];
            dst.Year__c = str.split(':')[4];
            dst.GGBS_Actuals__c = dstrgtmap3.get(str);
            dstgtlst.add(dst);
        }*/
        /*for(String str : dstrgtmap4.keySet())
        {
            District_Targets__c dst = new District_Targets__c();
            dst.District_Code__c = str.split(':')[0];
            dst.Product_Group__c = str.split(':')[1];
            dst.Month__c = str.split(':')[2];
            dst.Division__c = str.split(':')[3];
            dst.Year__c = str.split(':')[4];
            if(str.split(':')[2]=='January')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),1,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='February')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),2,1);
                if(math.mod(Integer.valueOf(str.split(':')[4]),4) == 0)
                    dst.No_of_Days_in_a_Month__c = 29;
                else
                    dst.No_of_Days_in_a_Month__c = 28;
            }
            if(str.split(':')[2]=='March')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),3,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='April')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),4,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='May')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),5,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='June')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),6,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='July')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),7,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='August')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),8,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='September')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),9,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='October')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),10,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            if(str.split(':')[2]=='November')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),11,1);
                dst.No_of_Days_in_a_Month__c = 30;
            }
            if(str.split(':')[2]=='December')
            {
                dst.Target_Start_Date__c = date.newInstance(Integer.valueOf(str.split(':')[4]),12,1);
                dst.No_of_Days_in_a_Month__c = 31;
            }
            dst.SEZ_Actuals__c = dstrgtmap4.get(str);
            dstgtlst.add(dst);
        }
        Insert dstgtlst;*/
        update dstgtlst1;
    }
    
    global void finish(Database.BatchableContext BC) {
    
        batchDistrictUpdate bdu = new batchDistrictUpdate(qrystr);
        database.executebatch(bdu);
    }
}