JSW Devsb/src/objects/District_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Depot_Actuals__c</fullName>
        <label>Depot Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Direct_Actuals__c</fullName>
        <label>Direct Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Actuals__c</fullName>
        <label>District Actuals</label>
        <referenceTo>MRM_Targets__c</referenceTo>
        <relationshipName>District_Rail_Road_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District_Rail_Actuals__c</fullName>
        <label>District Rail Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District_Road_Actuals__c</fullName>
        <label>District Road Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Trade_Actuals__c</fullName>
        <label>Non Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Actuals__c</fullName>
        <label>Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cement_MRM_Volume_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Cement MRM Volume Actuals</label>
    <nameField>
        <displayFormat>DRR-{0000000000}</displayFormat>
        <label>District(Rail/Road) Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cement MRM Volume Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Depot_Invoice__c</fullName>
        <formula>IF(OR(Plant__c=&apos;3001&apos;,Plant__c=&apos;3002&apos;,Plant__c=&apos;3003&apos;,Plant__c=&apos;3004&apos;,Plant__c=&apos;3005&apos;,Plant__c=&apos;3W01&apos;),false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Depot Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>District_Actuals_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>District Actuals Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Road_Invoice__c</fullName>
        <formula>IF( Shipping_Type__c =&apos;Rail transport&apos;,false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Road Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <formula>Account__r.Sales_Office__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Office Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/MRM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Depot_Actuals__c</fullName>
        <label>Depot Actuals</label>
        <summarizedField>District_Actuals__c.Depot_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Direct_Actuals__c</fullName>
        <label>Direct Actuals</label>
        <summarizedField>District_Actuals__c.Direct_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Non_Trade_Actuals__c</fullName>
        <label>Non Trade Actuals</label>
        <summarizedField>District_Actuals__c.Non_Trade_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Actuals__c</fullName>
        <label>Trade Actuals</label>
        <summarizedField>District_Actuals__c.Trade_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <formula>Sales_Office__c +&apos;:&apos;+ TEXT(Product__c) +&apos;:&apos;+ TEXT(Month__c) +&apos;:&apos;+ Year__c +&apos;:&apos;+  Plant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>MRM Target</label>
    <nameField>
        <displayFormat>MRM-{0000000000}</displayFormat>
        <label>MRM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/DistrictActuals.cls
global class DistrictActuals implements Database.Batchable<sObject> 
{
    public String qrystr;
    public DistrictActuals(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<Invoice__c > invupdate = new List<Invoice__c >();
        List<District_Actuals__c > dalist = new List<District_Actuals__c >();
        List<District_Actuals__c > templist = new List<District_Actuals__c >();
        Set<String> uniqcomb = new Set<String>();
        Set<String> uniqcomb1 = new Set<String>();
        Map<String,String> MRMMap = new Map<String,String>();
        Map<String,Double> TradeMap = new Map<String,Double>();
        Map<String,Double> NTradeMap = new Map<String,Double>();
        Map<String,Double> RailMap = new Map<String,Double>();
        Map<String,Double> RoadMap = new Map<String,Double>();
        Map<String,Double> DepotMap = new Map<String,Double>();
        Map<String,Double> DirectMap = new Map<String,Double>();
        Map<MRM_Targets__c,List<District_Actuals__c>> MasterMap = new Map<MRM_Targets__c,List<District_Actuals__c>>();
        
        for(Invoice__c inv : scope)
        {
            if(inv.Distribution_Channel__c == '10')
            if(!TradeMap.containsKey(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId))
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                TradeMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,inv.Qty__c);
            }
            else
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                TradeMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,TradeMap.get(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId)+inv.Qty__c);
            }
            
            if(inv.Distribution_Channel__c == '20' || inv.Distribution_Channel__c == '50')
            if(!NTradeMap.containsKey(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId))
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                NTradeMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,inv.Qty__c);
            }
            else
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                NTradeMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,NTradeMap.get(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId)+inv.Qty__c);
            }
            
            if(!inv.Road_Invoice__c)
            if(!RailMap.containsKey(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId))
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                RailMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,inv.Qty__c);
            }
            else
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                RailMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,RailMap.get(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId)+inv.Qty__c);
            }
            
            if(inv.Road_Invoice__c)
            if(!RoadMap.containsKey(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId))
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                RoadMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,inv.Qty__c);
            }
            else
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                RoadMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,RoadMap.get(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId)+inv.Qty__c);
            }
            
            if(inv.Depot_Invoice__c)
            if(!DepotMap.containsKey(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId))
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                DepotMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,inv.Qty__c);
            }
            else
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                DepotMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,DepotMap.get(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId)+inv.Qty__c);
            }
            
            if(!inv.Depot_Invoice__c)
            if(!DirectMap.containsKey(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId))
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                DirectMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,inv.Qty__c);
            }
            else
            {
                inv.District_Actuals_Process__c = true;
                uniqcomb.add(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId);
                DirectMap.put(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId,DirectMap.get(inv.Sales_Office_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.OwnerId)+inv.Qty__c);
            }
            invupdate.add(inv);
        }
        
        System.debug('---uniqcomb---'+uniqcomb);
        System.debug('---uniqcomb1---'+uniqcomb1);
        System.debug('---TradeMap---'+TradeMap);
        List<MRM_Targets__c> mrmtgt = [Select id,Unique_Code__c from MRM_Targets__c where Unique_Code__c IN: uniqcomb];
        Set<MRM_Targets__c> mrmset = new Set<MRM_Targets__c>();
        List<MRM_Targets__c> mrmlist = new List<MRM_Targets__c>();
        for(MRM_Targets__c mrm : mrmtgt)
        {
            MRMMap.put(mrm.Unique_Code__c,mrm.id);
        }
        System.debug('---MRMMap---'+MRMMap);
        System.debug('---TradeMap---'+TradeMap);
        System.debug('---NTradeMap---'+NTradeMap);
        System.debug('---RailMap---'+RailMap);
        System.debug('---RoadMap---'+RoadMap); 
        System.debug('---DepotMap---'+DepotMap);
        System.debug('---DirectMap---'+DirectMap); 
        for(String st : uniqcomb)
        {
            if(!MRMMap.containsKey(st))
            {
                MRM_Targets__c mrm = new MRM_Targets__c();
                mrm.Sales_Office__c = st.split(':')[0];
                mrm.Product__c = st.split(':')[1];
                mrm.Month__c = st.split(':')[2];
                mrm.Year__c = st.split(':')[3];
                mrm.Plant__c = st.split(':')[4];
                mrmset.add(mrm);
            }
        }      
        mrmlist.addAll(mrmset);
        insert mrmlist;
        for(MRM_Targets__c mrm : mrmlist)
        {
            MRMMap.put(mrm.Sales_Office__c+':'+mrm.Product__c+':'+mrm.Month__c+':'+mrm.Year__c+':'+mrm.Plant__c,mrm.id);
        }
        for(String st : uniqcomb)
        {
            for(String st1 : uniqcomb1)
            {
                District_Actuals__c da = new District_Actuals__c();
                da.District_Actuals__c = MRMMap.get(st);
                if(TradeMap.containsKey(st+':'+st1))
                    da.Trade_Actuals__c = TradeMap.get(st+':'+st1)==null ? 0 :TradeMap.get(st+':'+st1);
                if(NTradeMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Non_Trade_Actuals__c = NTradeMap.get(st+':'+st1)==null ? 0 : NTradeMap.get(st+':'+st1);
                if(RailMap.containsKey(st+':'+String.valueOf(st1)))
                    da.District_Rail_Actuals__c = RailMap.get(st+':'+st1)==null ? 0 : RailMap.get(st+':'+st1);
                if(RoadMap.containsKey(st+':'+String.valueOf(st1)))
                    da.District_Road_Actuals__c = RoadMap.get(st+':'+st1)==null ? 0 : RoadMap.get(st+':'+st1);
                if(DepotMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Depot_Actuals__c = DepotMap.get(st+':'+st1)==null ? 0 : DepotMap.get(st+':'+st1);
                if(DirectMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Direct_Actuals__c = DirectMap.get(st+':'+st1)==null ? 0 : DirectMap.get(st+':'+st1);
                da.Commercial_Invoice_Date__c = Date.valueOF(st1.split(':')[0]);
                //da.User__c = st1.split(':')[1];
                da.Product__c = st.split(':')[1];
                if(da.District_Actuals__c !=null)
                //if(!(da.Trade_Actuals__c==null &&  da.Non_Trade_Actuals__c ==null && da.District_Rail_Actuals__c ==null && da.District_Road_Actuals__c ==null && da.Depot_Actuals__c ==null && da.Direct_Actuals__c ==null))
                    dalist.add(da);
                /*else
                {
                    MRM_Targets__c mrm = new MRM_Targets__c();
                    mrm.District_Code__c = st.split(':')[0];
                    mrm.Product__c = st.split(':')[1];
                    mrm.Month__c = st.split(':')[2];
                    mrm.Year__c = st.split(':')[3];
                    mrm.Plant__c = st.split(':')[4];
                    mrmset.add(mrm);
                    if(MasterMap.containsKey(mrm)){
                        templist.add(da);
                        MasterMap.put(mrm,templist);
                    } else {
                        templist = new List<District_Actuals__c>();
                        templist.add(da);
                        MasterMap.put(mrm,templist);
                    }
                }*/
            }
        }
        /*System.debug(MasterMap+'@11111111111111@@');
        mrmlist.addAll(mrmset);
        insert mrmlist;
        
        System.debug(MasterMap+'@@@');
        
        for(MRM_Targets__c mrm : mrmlist){
            System.debug('@@@@'+mrm);
            for(District_Actuals__c da : MasterMap.get(mrm)){
                da.District_Actuals__c = mrm.id;
                dalist.add(da);
            }
        }
        */
        update invupdate;
        insert dalist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
    }
}