JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Districts__c.object
<CustomObject>
    <fields>
        <fullName>District_Category__c</fullName>
        <label>District Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Districts</label>
    <nameField>
        <label>Districts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DIstricts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Adhoc_Incentive_Value__c</fullName>
        <label>Adhoc Incentive Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Freight__c</fullName>
        <label>Freight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMC__c</fullName>
        <label>MMC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_C_F_Discount__c</fullName>
        <label>NSR C&amp;F Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Other_Discount__c</fullName>
        <label>NSR Other Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PD_Value__c</fullName>
        <label>NSR PD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PRFT_Dump_Discout__c</fullName>
        <label>NSR PRFT Dump Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Rake_Discount__c</fullName>
        <label>NSR Rake Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_T_Value__c</fullName>
        <formula>Total_value__c - (  MMC__c   + BED_Total__c + CGST_Value__c +  CSTT__c +  IGST_Value__c +  SGST_Value__c +  UGST_Value__c +   VAT_Value__c + Freight__c + (NSR_C_F_Value__c *  Qty__c ) +    (( NSR_Other_Discount__c ) - ABS(Additional_Discount__c) ) +  NSR_Packing_Cost__c + (NSR_PD_Value__c *  Qty__c ) + (NSR_PRFT_Value__c *  Qty__c ) + NSR_Rake_Discount__c +  Total_Adhoc_Discount__c )- IF( (Commercial_Invoice_Date_Formula__c &gt;  DATE(2017,04,30) &amp;&amp; Commercial_Invoice_Date_Formula__c &lt; DATE(2017,07,01)   &amp;&amp;  (Brand_Short_Form__c  = &apos;PSC  || CHD&apos;)) ,Discount__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Targets_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NSR Targets Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAcking_Cost__c</fullName>
        <label>PAcking Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <formula>Account__r.Sales_Office__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Office Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_tax__c</fullName>
        <label>Total tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <label>Total value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/MRM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipName>District_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>MRM Target</label>
    <nameField>
        <displayFormat>MRM-{0000000000}</displayFormat>
        <label>MRM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_New_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>NSR Target</relationshipLabel>
        <relationshipName>NSR_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MMC__c</fullName>
        <label>MMC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>CASE( MONTH( Commercial_Invoice_Date__c), 1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_Targets_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NSR Targets Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Packing_Cost__c</fullName>
        <label>Packing Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR( Commercial_Invoice_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>NSR Target</label>
    <nameField>
        <label>NSR Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/NSRActuals_Test.cls
@isTest
public class NSRActuals_Test 
{
	public static testmethod void nsrActlTest()
    {
        List<Invoice__c> invlst = new List<Invoice__c>();
        Date myDate = date.newInstance(2017,06,10);
        String query = 'Select Total_value__c,NSR_PD_Value__c,NSR_Other_Discount__c,NSR_PRFT_Dump_Discout__c,NSR_C_F_Discount__c,Packing_Cost__c,Freight__c,Total_Tax__c,NSR_Rake_Discount__c,Adhoc_Incentive_Value__c,MMC__c,Qty__c,NSR_T_Value__c,NSR_Targets_Processed__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,Distribution_Channel__c from Invoice__c where Day_only(CreatedDate) = TODAY';
        
        Districts__c dst = new Districts__c();
        dst.District_Code__c = 'test1';
        dst.District_Category__c='test';
        dst.Name = 'test dst';
        insert dst;
        District__c ter = new District__c();
        ter.Districts__c = dst.id;
        ter.Territory_Code__c = 'test';
        insert ter;
        MRM_Targets__c mrm = new MRM_Targets__c();
        mrm.District__c = dst.id;
        mrm.District_Code__c = 'test1';
        mrm.Month__c ='June';
        mrm.Year__c = '2017';
        mrm.Product__c = 'PSC';
        mrm.Plant__c = '3001';
        mrm.Sales_Office__c = 'test';
        insert mrm;
        
        NSR_New_Targets__c nsr = new NSR_New_Targets__c();
        nsr.District_Code__c = 'test1';
        nsr.Distribution_Channel__c = 10;
        nsr.Product_Group__c = 'PSC';
        nsr.Plant_Short_Form__c = '3001';
        nsr.Quantity__c = 10;
        nsr.C_F_Value__c = 11;
        nsr.Commercial_Invoice_Date__c = myDate;
        nsr.Discount__c = 12;
        nsr.Discount_Value__c = 13;
        nsr.Frieght__c = 14;
        nsr.Total_Basic_Price__c = 15;
        nsr.Toatl_Value__c = 16;
        nsr.PD_SPL_ADDL__c = 17;
        nsr.Packing_Cost__c = 18;
        nsr.MMC__c = 19;
        nsr.NSR_Value__c = 20;
        nsr.PRFT_Dump_Value__c = 21;
        nsr.Other__c = 22;
        insert nsr;
        
        NSR_New_Targets__c nsr1 = new NSR_New_Targets__c();
        nsr1.District_Code__c = 'test1';
        nsr1.Distribution_Channel__c = 20;
        nsr1.Product_Group__c = 'PSC';
        nsr1.Plant_Short_Form__c = '3001';
        nsr1.Quantity__c = 10;
        nsr1.C_F_Value__c = 11;
        nsr1.Commercial_Invoice_Date__c = myDate;
        nsr1.Discount__c = 12;
        nsr1.Discount_Value__c = 13;
        nsr1.Frieght__c = 14;
        nsr1.Total_Basic_Price__c = 15;
        nsr1.Toatl_Value__c = 16;
        nsr1.PD_SPL_ADDL__c = 17;
        nsr1.Packing_Cost__c = 18;
        nsr1.MMC__c = 19;
        nsr1.NSR_Value__c = 20;
        nsr1.PRFT_Dump_Value__c = 21;
        nsr1.Other__c = 22;
        insert nsr1;
        
        Invoice__c inv = new Invoice__c();
        inv.Plant__c = '3333';
        inv.Plant_Short_Form__c= '3001';
        inv.Shipping_Type__c = 'Bulker';
        inv.Sales_District__c= 'test1';
        inv.NSR_PD_Value__c = 10;
        inv.NSR_C_F_Value__c =20;
        inv.NSR_Other_Value__c = 10;
        inv.NSR_PRFT_Value__c = 20;
        inv.Total_tax__c = 10;
        inv.Total_value__c = 20;
        inv.PAcking_Cost__c = 10;
        inv.Freight__c = 10;
        inv.Adhoc_Incentive_Value__c  = 10;
        inv.MMC__c = 10;
        inv.Commercial_Invoice_Date__c=myDate;
        inv.Sold_To_Code__c='test';
        inv.Brand_Short_Form__c='PSC';
        inv.Qty__c = 10; 
        inv.Distribution_Channel__c = '10';
        inv.Division__c = '50';
        inv.Sales_Office__c = 'test';
        insert inv;
        Invoice__c inv1 = new Invoice__c();
        inv1.Plant__c = '3333';
        inv1.Plant_Short_Form__c= '3001';
        inv1.Shipping_Type__c = 'Bulker';
        inv1.Sales_District__c= 'test1';
        inv1.NSR_PD_Value__c = 10;
        inv1.NSR_C_F_Value__c =20;
        inv1.NSR_Other_Value__c = 10;
        inv1.NSR_PRFT_Value__c = 20;
        inv1.PAcking_Cost__c = 15;
        inv1.Total_tax__c = 10;
        inv1.Total_value__c = 20;
        inv1.Freight__c = 15;
        inv1.Adhoc_Incentive_Value__c  = 10;
        inv1.MMC__c = 19;
        inv1.Commercial_Invoice_Date__c=myDate;
        inv1.Sold_To_Code__c='test';
        inv1.Brand_Short_Form__c='PSC';
        inv1.Qty__c = 10; 
        inv1.Distribution_Channel__c = '20';
        inv1.Division__c = '50';
        inv1.Sales_Office__c = 'test';
        insert inv1;
        
        List<Invoice__c> nsrlst1 = [Select Total_value__c,NSR_PD_Value__c,NSR_Other_Discount__c,NSR_PRFT_Dump_Discout__c,NSR_C_F_Discount__c,Packing_Cost__c,Freight__c,Total_Tax__c,NSR_Rake_Discount__c,Adhoc_Incentive_Value__c,MMC__c,Qty__c,NSR_T_Value__c,NSR_Targets_Processed__c,Sales_Office_Code__c,Brand_Short_Form__c,Month_of_Commercial_Invoice_Date__c,Year__c,Plant_Short_Form__c,Commercial_Invoice_Date_Formula__c,Distribution_Channel__c from Invoice__c];
        NSRActuals bat1 = new NSRActuals(query);
        bat1.execute(null,nsrlst1);
        Database.executeBatch(bat1);
    }
}