JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>Hyderabad East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rangareddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mahboobnagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nagarkurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gadwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nalgonda South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medak West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoni</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nandyal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kurnool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KGY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cudappah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prodattur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anantpur 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chittoor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tirupati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Madanappalle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nellore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gudur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongole</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markapur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chirala</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vijayawada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machlipatnam</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Market_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Details of Competitor Activities</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Market Information JSW</relationshipLabel>
        <relationshipName>Market_Information_JSW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Information</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Market Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Information JSW</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/MarketInfoWebservice.cls
@RestResource(urlMapping='/MarketInfoManagement/*')
global with sharing class MarketInfoWebservice{

  @HttpPost
    global static List<Market_Information__c> doPost(String userId) {
        list<Market_Information__c> MarketInfoList= [SELECT Id,Name,Account__c,Account__r.name,Lead__c,Lead__r.name,Territory__c,Territory__r.name,Comments__c FROM Market_Information__c];
        return MarketInfoList;
    }
 
}