JSW Devsb/src/objects/District__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Blended_cement_potential_in_MT__c</fullName>
        <label>Blended cement potential in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Catgegory_A_potential_in_MT__c</fullName>
        <label>Catgegory A potential in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Volume_Committment_to_JSW__c</fullName>
        <label>Expected Volume Committment to JSW</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KYC_Form_Filled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KYC Form Filled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Response__c</fullName>
        <label>Lead Response</label>
        <picklist>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May Be Interested</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>2</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>No_of_Sub_Dealers__c</fullName>
        <label>No of Sub Dealers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Potential__c</fullName>
        <label>Total Counter Potential in MT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Promoter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middleman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architect</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wholesale_Percentage__c</fullName>
        <label>Wholesale %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/classes/LeadWebservice.cls
@RestResource(urlMapping='/LeadManagement/*')
global with sharing class LeadWebservice{

  @HttpPost
    global static List<Lead> doPost(String userId) {
        List<Lead> leadsList = new List<Lead>();
        String curRole = '';
        User mobusr = [select id,name,userroleid,userrole.name,Profile.Name from user where id =: userId];
        
        curRole = mobusr.UserRole.Name.split(' ')[0];
        curRole = curRole+'%';
        List<User> allusrs = [select id,name from User where UserRole.Name like : curRole];
        Set<Id> userset = new Set<Id>();
        for(User usr : allusrs){
            userset.add(usr.id);
        }
        if(!mobusr.UserRole.Name.contains(' TSO')){
        leadsList = [SELECT Id,Name,Type__c,ownerId,owner.name,Expected_Volume_Committment_to_JSW__c,Location__c,District__c, 
                     Status,Company,Lead_Response__c,Phone,KYC_Form_Filled__c,Potential__c,Blended_cement_potential_in_MT__c,
                     Catgegory_A_potential_in_MT__c,Wholesale_Percentage__c,No_of_Sub_Dealers__c,Street,City,State,Country,PostalCode 
                     FROM Lead where Ownerid in: userset];
        }
        return leadsList;
    }
 
}