JSW Devsb/src/objects/Districts__c.object
<CustomObject>
    <fields>
        <fullName>District_Category__c</fullName>
        <label>District Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Districts</label>
    <nameField>
        <label>Districts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DIstricts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Districts</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plant Master</label>
        <referenceTo>Plant_Master__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_C_F_Value_Changes__c.object
<CustomObject>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plant_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plant</label>
        <referenceTo>Plant_Master__c</referenceTo>
        <relationshipLabel>NSR C&amp;F Value Changes</relationshipLabel>
        <relationshipName>NSR_C_F_Value_Changes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR C&amp;F Value Changes</label>
    <nameField>
        <label>NSR C&amp;F Value Changes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR C&amp;F Value Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_Other_Values__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Districts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>Districts__c</referenceTo>
        <relationshipLabel>NSR Other Values</relationshipLabel>
        <relationshipName>NSR_Other_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR Other Values</label>
    <nameField>
        <displayFormat>Other-{000000000}</displayFormat>
        <label>NSR Other Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR Other Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PD_Values__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR PD Values</label>
    <nameField>
        <label>NSR PD Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR PD Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PRFT_Values__c.object
<CustomObject>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plant_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plant</label>
        <referenceTo>Plant_Master__c</referenceTo>
        <relationshipLabel>NSR PRFT Values</relationshipLabel>
        <relationshipName>NSR_PRFT_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR PRFT Values</label>
    <nameField>
        <displayFormat>PRFT-{00000000}</displayFormat>
        <label>NSR PRFT Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR PRFT Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Plant_Master__c.object
<CustomObject>
    <fields>
        <fullName>Plant_Code__c</fullName>
        <label>Plant Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Plant Master</label>
    <nameField>
        <label>Plant MAster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

JSW Devsb/src/classes/pdvalues_Test.cls
@isTest
public class pdvalues_Test 
{
    public static testmethod void pdval()
    {
        Invoice__c inv = new Invoice__c();
        inv.Plant__c = 'ABC';
        inv.Sales_District__c = 'Dist';
        inv.Brand_Short_Form__c = 'PSC';
        inv.Commercial_Invoice_Date__c = system.today();
        insert inv;
        
        Districts__c dst = new Districts__c();
        dst.District_Code__c = 'Dist';
        dst.Name = 'test dst';
        dst.District_Category__c = 'A';
        insert dst;
        
        product2 p=new product2();
        p.ProductCode='PSC';
        p.name='abc';
        insert p;
        
        Plant_Master__c p2=new Plant_Master__c();
        p2.Plant_Code__c='ABC';
        insert p2;
        
        NSR_Other_Values__c othr = new NSR_Other_Values__c();
        othr.District_Code__c = 'Dist';
        othr.Product__c = 'PSC';
        othr.From_Date__c = System.today() - 1;
        othr.To_Date__c = System.today() + 3;
        insert othr;
        
        NSR_PRFT_Values__c prft = new NSR_PRFT_Values__c();
        prft.Plant__c = 'ABC';
        prft.Product__c = 'PSC';
        prft.From_Date__c = System.today() - 1;
        prft.To_Date__c = System.today() + 3;
        insert prft;
        
        NSR_C_F_Value_Changes__c cf = new NSR_C_F_Value_Changes__c();
        cf.Plant__c = 'ABC';
        cf.Product__c = 'PSC';
        cf.From_Date__c = System.today() - 1;
        cf.To_Date__c = System.today() + 3;
        insert cf;
        
        NSR_PD_Values__c pd = new NSR_PD_Values__c();
        pd.District_Code__c = 'Dist';
        pd.Product__c = 'PSC';
        pd.From_Date__c = System.today() - 1;
        pd.To_Date__c = System.today() + 3;
        insert pd;
    }
}