JSW Devsb/src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_Of_Invitees_for_Each_Meet__c</fullName>
        <label>No Of Invitees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concreel HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSC &amp; CHD</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Meet__c</fullName>
        <label>Type of Meet</label>
        <picklist>
            <picklistValues>
                <fullName>Counter meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project site meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mason meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractors meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer staff training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canopy based activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB MEET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>plant visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stationay lab based activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concrete mix design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering college lecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineers Meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Govt &amp; Inst Meets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mega Mason Meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder/Contractors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Dealers meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsered Meets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP Meets</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/InsertCustomEventTest.cls
@isTest
public class InsertCustomEventTest 
{
    public static testmethod void cusevnt()
    {
        Date myDate = System.today();
        Event evnt = new Event();
        evnt.Subject = 'Test Event Subject';
        evnt.Budget__c = 1000;
        evnt.Event__c = myDate;
        evnt.No_Of_Invitees_for_Each_Meet__c = 20;
        evnt.Product__c = 'PSC';
        evnt.Type_of_Meet__c = 'Mason meet';
        evnt.DurationInMinutes = 30;
        evnt.ActivityDateTime = System.now();
        insert evnt;
    }
}