JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Adhoc_Incentive_Value__c</fullName>
        <label>Adhoc Incentive Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Incentive_Value__c</fullName>
        <label>Customer Incentive Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Invoice_Discount_Value__c</fullName>
        <label>Invoice Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_NSR_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice NSR Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NSR_C_F_Value__c</fullName>
        <label>NSR C&amp;F Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Other_Value__c</fullName>
        <label>NSR Other Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PD_Value__c</fullName>
        <label>NSR PD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PRFT_Value__c</fullName>
        <label>NSR PRFT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLOC__c</fullName>
        <defaultValue>&quot;FG01&quot;</defaultValue>
        <label>SLOC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/NSRCalculationsSchedule.cls
global class NSRCalculationsSchedule Implements Schedulable
{
    global void execute(SchedulableContext sc)
    {
        String query = 'Select Sales_District__c,Brand_Short_Form__c,Distribution_channel__c,Plant_Short_Form__c,Plant__c,SLOC__c,Sold_To_Code__c,Commercial_Invoice_Number__c,NSR_PD_Value__c,Commercial_Invoice_Date_Formula__c,NSR_Other_Value__c,NSR_PRFT_Value__c,NSR_C_F_Value__c,Adhoc_Incentive_Value__c,Customer_Incentive_Value__c,Invoice_Discount_Value__c,Invoice_NSR_Processed__c from Invoice__c where Commercial_Invoice_Date_Formula__c > 2017-06-30 AND Commercial_Invoice_Date_Formula__c < TODAY AND Invoice_NSR_Processed__c=False';
        NSRCalculations bat = new NSRCalculations(query); //ur batch class
        
        database.executebatch(bat);        
    }
}