JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Group_1__c</fullName>
        <label>Customer Group 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>52</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>53</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Name__c</fullName>
        <label>Plant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/batchDistrictUpdate_Test.cls
@isTest
public class batchDistrictUpdate_Test 
{
    public static testmethod void batchtest()
    {
        List<Invoice__c> invlst = new List<Invoice__c>();
		Date myDate = date.newInstance(2017,01,01);
        Date myDate1 = date.newInstance(2017,01,01);
        Date myDate2 = date.newInstance(2017,01,01);
        String query1 = 'Select id,name,Plant_Name__c,Plant__c,Sales_Office_Description__c,Account__c,Commercial_Invoice_Date_Formula__c,Qty__c,Plant_Short_Form__c,Sales_District__c,Brand_Short_Form__c,Sold_To_Code__c,Commercial_Invoice_Date__c,Distribution_Channel__c,Division__c,Month_of_Commercial_Invoice_Date__c,Year__c,Customer_Group_1__c,Cust_Grp1_from_Master__c from Invoice__c where CREATEDDATE=TODAY'; 
        for(integer i=1;i<=12;i++)
		{
			Invoice__c inv = new Invoice__c();
			//inv.Plant_Short_Form__c= 'test';
			inv.Sales_District__c= 'test1';
			inv.Commercial_Invoice_Date__c=myDate+30;
			inv.Sold_To_Code__c='test';
			inv.Brand_Short_Form__c='PSC';
			inv.Qty__c = 10; 
			inv.Distribution_Channel__c = '10';
			inv.Division__c = '50';
			invlst.add(inv);
            myDate = myDate+30;
		}
		for(integer i=1;i<=12;i++)
		{
			Invoice__c inv = new Invoice__c();
			//inv.Plant_Short_Form__c= 'test';
			inv.Sales_District__c= 'test1';
			inv.Commercial_Invoice_Date__c=myDate1+30;
			inv.Sold_To_Code__c='test';
			inv.Brand_Short_Form__c='CHD';
			inv.Qty__c = 10; 
			inv.Distribution_Channel__c = '20';
			inv.Division__c = '50';
			inv.Customer_Group_1__c = 'N01-INSTITUTIONS';
			invlst.add(inv);
            myDate1 = myDate1+30;
		}
		for(integer i=1;i<=12;i++)
		{
			Invoice__c inv = new Invoice__c();
			//inv.Plant_Short_Form__c= 'test';
			inv.Sales_District__c= 'test2';
			inv.Commercial_Invoice_Date__c=myDate2+30;
			inv.Sold_To_Code__c='test';
			inv.Brand_Short_Form__c='PSC';
			inv.Qty__c = 10; 
			inv.Distribution_Channel__c = '50';
			inv.Division__c = '50';
			inv.Customer_Group_1__c = 'N01-INSTITUTIONS';
			invlst.add(inv);
            myDate2 = myDate2+30;
		}
        System.debug('-----'+invlst);
		insert invlst;
        
        List<Invoice__c> invlst1 = [Select id,name,Plant_Name__c,Plant__c,Distribution_Channel__c,Sales_Office_Description__c,Account__c,Commercial_Invoice_Date_Formula__c,Qty__c,Plant_Short_Form__c,Customer_Group_1__c,Brand_Short_Form__c,Sales_District__c,Division__c,Month_of_Commercial_Invoice_Date__c,Year__c,Sold_To_Code__c,Cust_Grp1_from_Master__c from Invoice__c];
        batchDistrictUpdate bat1 = new batchDistrictUpdate(query1);
        bat1.execute(null,invlst1);
        Database.executeBatch(bat1);
        
        batchDistrictUpdateDelete bat = new batchDistrictUpdateDelete(query1);
        bat.execute(null,invlst1);
        Database.executeBatch(bat);
    }
}