JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <externalId>true</externalId>
        <label>Sales District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_PRFT_Values__c.object
<CustomObject>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MFG_Plant__c</fullName>
        <label>MFG Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRFT_Value__c</fullName>
        <label>PRFT Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant__c</fullName>
        <label>Plant</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Storage_Location__c</fullName>
        <label>Storage Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>NSR PRFT Values</label>
    <nameField>
        <displayFormat>PRFT-{00000000}</displayFormat>
        <label>NSR PRFT Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NSR PRFT Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/NSRPRFTValues_Test.cls
@isTest
public class NSRPRFTValues_Test 
{
    public static testmethod void prftvaluestest()
    {
        String query = 'Select From_Date__c,MFG_Plant__c,Plant__c,PRFT_Value__c,Product__c,Storage_Location__c,To_Be_Processed__c,To_Date__c from NSR_PRFT_Values__c where CreatedDate=TODAY';
        
        Invoice__c inv = new Invoice__c();
        inv.Distribution_Channel__c = '10';
        inv.Plant__c = 'ABC';
        inv.Sales_District__c = 'Dist';
        inv.Brand_Short_Form__c = 'PSC';
        inv.Commercial_Invoice_Date__c = system.today();
        insert inv;
        
        NSR_PRFT_Values__c prft = new NSR_PRFT_Values__c();
        prft.Plant__c = 'ABC';
        prft.Product__c = 'PSC';
        prft.From_Date__c = System.today() - 1;
        prft.To_Date__c = System.today() + 3;
        insert prft;
        
        List<NSR_PRFT_Values__c> pdlist = [Select From_Date__c,MFG_Plant__c,Plant__c,PRFT_Value__c,Product__c,Storage_Location__c,To_Be_Processed__c,To_Date__c from NSR_PRFT_Values__c where CreatedDate=TODAY];
        NSRPRFTValues bat = new NSRPRFTValues(query);
        bat.execute(null,pdlist);
        Database.executeBatch(bat);
    }
}