JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State_NSR_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>TEXT( State_MRM_Targets__r.Product_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <label>State NSR Actuals</label>
    <nameField>
        <label>State NSR Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State NSR Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/StateNSRDelete.cls
global class StateNSRDelete implements Database.Batchable<sObject> 
{
    public String qrystr;
    public StateNSRDelete(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<State_NSR_Actuals__c> statensr = new List<State_NSR_Actuals__c>();
        Set<String> Prodset = new Set<String>();
        Date frmdate;
        Date todat;
        
        for(Invoice__c nsr : scope)
        {
            Prodset.add(nsr.Brand_Short_Form__c);
            if(frmdate == null && todat == null)
            {
                frmdate = nsr.Commercial_Invoice_Date_Formula__c;
                todat = nsr.Commercial_Invoice_Date_Formula__c;
            }
            else if(frmdate > nsr.Commercial_Invoice_Date_Formula__c)
                frmdate = nsr.Commercial_Invoice_Date_Formula__c;
            else if(todat < nsr.Commercial_Invoice_Date_Formula__c)
                todat = nsr.Commercial_Invoice_Date_Formula__c;
             
         } 
         
         if(Prodset.size() > 0)
            statensr = [Select id from State_NSR_Actuals__c where Commercial_Invoice_Date__c>= :frmdate AND Commercial_Invoice_Date__c <= :todat AND Product__c IN: Prodset limit 10000];
        else
            statensr = [Select id from State_NSR_Actuals__c where Commercial_Invoice_Date__c>= :frmdate AND Commercial_Invoice_Date__c <= :todat limit 10000];
        Delete statensr;
    }
    global void finish(Database.BatchableContext BC) 
    {
        System.debug('----->'+qrystr);
        StateNSRActuals nsr = new StateNSRActuals(qrystr); //ur batch class
        database.executebatch(nsr);  
    }
}