JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <externalId>true</externalId>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Discount_Value__c</fullName>
        <label>Invoice Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Invoice_Discounts__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Number__c</fullName>
        <label>Commercial Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Discount_Value__c</fullName>
        <label>Invoice Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Discounts</relationshipLabel>
        <relationshipName>Invoice_Discounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Discounts</label>
    <nameField>
        <label>Invoice Discounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/NSRIDValues.cls
global class NSRIDValues implements Database.Batchable<sObject> 
{
    public String qrystr;
    public NSRIDValues(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice_Discounts__c> scope) 
    {
        List<Invoice_Discounts__c> IDList = new List<Invoice_Discounts__c>();
        Set<String> setCIN = new Set<String>();
        for(Invoice_Discounts__c pd : scope)
        {
            setCIN.add(pd.Commercial_Invoice_Number__c);
        }
        
        List<Invoice__c> invList = [Select id,Commercial_Invoice_Number__c,Invoice_Discount_Value__c from Invoice__c where Commercial_Invoice_Number__c IN: setCIN];
        
        for(Invoice_Discounts__c pd : scope)
        {
            for(Invoice__c inv : invList)
            {
                 if(inv.Commercial_Invoice_Number__c== pd.Commercial_Invoice_Number__c)
                    inv.Invoice_Discount_Value__c = pd.Invoice_Discount_Value__c;
            }
            pd.To_Be_Processed__c = False;
            IDList.add(pd);
        }
        update invlist;
        update IDlist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        
    }
}