JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/User_Targets__c.object
<CustomObject>
    <fields>
        <fullName>User_Pro_Rata_Acheivement__c</fullName>
        <formula>User_Actuals__c  /  MTD_Target__c</formula>
        <label>User Pro-Rata Acheivement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>User Targets</label>
    <nameField>
        <displayFormat>UT-{000000}</displayFormat>
        <label>User Targets  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/incentive_netdealer.cls
public class incentive_netdealer
{
    Set<id> acids = new Set<id>();
    Map<String,String> usrmap = new Map<String,String>();
    public void m1()
    {
        Integer mnthnum = System.today().month();
        List<Account> newaccs = [Select id,Ownerid from Account where CALENDAR_MONTH(CreatedDate)=:mnthnum];
        for(Account ac : newaccs)
        {
            acids.add(ac.Ownerid);
        }
        Integer newdlrs = acids.size();
        
        List<Invoice__c> inv = [Select id,ownerId from Invoice__c where ownerId IN:acids];
        for(Invoice__c iv : inv)
        {
            usrmap.put(iv.ownerId,iv.id);
        }
        Integer newdlrbills = acids.size() - usrmap.size();
        
        List<User> userslst = [Select id from User where id IN: usrmap.keyset()];
        
        for(User usr : userslst)
        {
            if(usrmap.containsKey(usr.id))
            {
                //usr.PSC_Sales_Acheivement__c = usrmap.get(usr.id);
                //user field = (newdlrs - newdlrbills)/newdlrs;
            }
        }
        
        /*List<User_Targets__c> usrtgt = [Select id,User_Pro_Rata_Acheivement__c,ownerId from User_Targets__c where ownerId IN: acids];
        
        for(User_Targets__c ut : usrtgt)
        {
            usrmap.put(ut.ownerId,ut.User_Pro_Rata_Acheivement__c);
        }
        
        List<User> userslst = [Select id,PSC_Sales_Acheivement__c from User where id IN: usrmap.keyset()];
        
        for(User usr : userslst)
        {
            if(usrmap.containsKey(usr.id))
            {
                usr.PSC_Sales_Acheivement__c = usrmap.get(usr.id);
            }
        }*/
    }
}