JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <label>Total value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Monthly_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Monthly Targets</relationshipLabel>
        <relationshipName>Monthly_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <formula>MONTH( Monthly_Dealer_Target__r.Target_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Today_Sale__c</fullName>
        <label>Today Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Targets</label>
    <nameField>
        <label>Monthly Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/Invouceupdate.cls
global class Invouceupdate implements Schedulable
{
    public Invouceupdate(){}
    public void execute(SchedulableContext sc)
    {
        integer mnth;
        Date myDate = System.today()-1;
        if(myDate.day()==1)
            mnth = myDate.month()-1;
        else
            mnth = myDate.month();
        list<Monthly_Targets__c> mdt=[select id,Today_Sale__c,Dealer__c from Monthly_Targets__c where month__c = :mnth];
        list<Invoice__c> inv=[select id,Total_value__c,Account__c  from Invoice__c where Commercial_Invoice_Date__c = :myDate];
        
        for(Monthly_Targets__c mt:mdt)
        {
            for(Invoice__c invc:inv)
            {
                if(mt.Dealer__c==invc.Account__c)
                {
                    if(invc.Total_value__c != null)
                        mt.Today_Sale__c=mt.Today_Sale__c+double.valueof(invc.Total_value__c);
                }
            }
        }
        update mdt;
    }
}