JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Maharashtra_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Maharashtra Actuals</label>
    <nameField>
        <displayFormat>MH-{00000000}</displayFormat>
        <label>Maharashtra Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maharashtra Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/MaharashtraActualsDelete.cls
global class MaharashtraActualsDelete implements Database.Batchable<sObject> 
{
    public String qrystr;
    public MaharashtraActualsDelete(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<Maharashtra_Actuals__c> mhlist = new List<Maharashtra_Actuals__c>();
        Set<String> Prodset = new Set<String>();
        Date frmdate;
        Date todat;
        
        for(Invoice__c inv : scope)
        {
            Prodset.add(inv.Brand_Short_Form__c);
            if(frmdate == null && todat == null)
            {
                frmdate = inv.Commercial_Invoice_Date_Formula__c;
                todat = inv.Commercial_Invoice_Date_Formula__c;
            }
            else if(frmdate > inv.Commercial_Invoice_Date_Formula__c)
                frmdate = inv.Commercial_Invoice_Date_Formula__c;
            else if(todat < inv.Commercial_Invoice_Date_Formula__c)
                todat = inv.Commercial_Invoice_Date_Formula__c;      
        }
        
        if(Prodset.size() > 0)
            mhlist = [Select id from Maharashtra_Actuals__c where Commercial_Invoice_Date__c>= :frmdate AND Commercial_Invoice_Date__c <= :todat AND Product__c IN: Prodset limit 10000];
        else
            mhlist = [Select id from Maharashtra_Actuals__c where Commercial_Invoice_Date__c>= :frmdate AND Commercial_Invoice_Date__c <= :todat limit 10000];
        Delete mhlist;
    }
    global void finish(Database.BatchableContext BC) 
    {
        MaharashtraActuals distact = new MaharashtraActuals(qrystr); //ur batch class
        database.executebatch(distact); 
    }
}