JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depot_Invoice__c</fullName>
        <formula>IF(OR(Plant__c=&apos;3001&apos;,Plant__c=&apos;3002&apos;,Plant__c=&apos;3003&apos;,Plant__c=&apos;3004&apos;,Plant__c=&apos;3005&apos;,Plant__c=&apos;3W01&apos;),false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Depot Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Road_Invoice__c</fullName>
        <formula>IF( Shipping_Type__c =&apos;Rail transport&apos;,false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Road Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Actuals_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <label>State Actuals Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/MRM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Depot_Actuals__c</fullName>
        <label>Depot Actuals</label>
        <summarizedField>District_Actuals__c.Depot_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Direct_Actuals__c</fullName>
        <label>Direct Actuals</label>
        <summarizedField>District_Actuals__c.Direct_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Non_Trade_Actuals__c</fullName>
        <label>Non Trade Actuals</label>
        <summarizedField>District_Actuals__c.Non_Trade_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GGBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rail_Actuals__c</fullName>
        <label>Rail Actuals</label>
        <summarizedField>District_Actuals__c.District_Rail_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Road_Actuals__c</fullName>
        <label>Road Actuals</label>
        <summarizedField>District_Actuals__c.District_Road_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Trade_Actuals__c</fullName>
        <label>Trade Actuals</label>
        <summarizedField>District_Actuals__c.Trade_Actuals__c</summarizedField>
        <summaryForeignKey>District_Actuals__c.District_Actuals__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <formula>Sales_Office__c +&apos;:&apos;+ TEXT(Product__c) +&apos;:&apos;+ TEXT(Month__c) +&apos;:&apos;+ Year__c +&apos;:&apos;+  Plant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>MRM Target</label>
    <nameField>
        <displayFormat>MRM-{0000000000}</displayFormat>
        <label>MRM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Depot_Actuals__c</fullName>
        <label>Depot Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Direct_Actuals__c</fullName>
        <label>Direct Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Trade_Actuals__c</fullName>
        <label>Non Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>TEXT( State_MRM_Targets__r.Product_Group__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rail_Actuals__c</fullName>
        <label>Rail Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Road_Actuals__c</fullName>
        <label>Road Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_MRM_Targets__c</fullName>
        <label>State MRM Targets</label>
        <referenceTo>State_MRM_Targets__c</referenceTo>
        <relationshipLabel>State Actuals</relationshipLabel>
        <relationshipName>State_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trade_Actuals__c</fullName>
        <label>Trade Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>State Actuals</label>
    <nameField>
        <label>State Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State_MRM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Depot_Actuals__c</fullName>
        <label>Depot Actuals</label>
        <summarizedField>State_Actuals__c.Depot_Actuals__c</summarizedField>
        <summaryForeignKey>State_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Direct_Actuals__c</fullName>
        <label>Direct Actuals</label>
        <summarizedField>State_Actuals__c.Direct_Actuals__c</summarizedField>
        <summaryForeignKey>State_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Non_Trade_Actuals__c</fullName>
        <label>Non Trade Actuals</label>
        <summarizedField>State_Actuals__c.Non_Trade_Actuals__c</summarizedField>
        <summaryForeignKey>State_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rail_Actuals__c</fullName>
        <label>Rail Actuals</label>
        <summarizedField>State_Actuals__c.Rail_Actuals__c</summarizedField>
        <summaryForeignKey>State_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Road_Actuals__c</fullName>
        <label>Road Actuals</label>
        <summarizedField>State_Actuals__c.Road_Actuals__c</summarizedField>
        <summaryForeignKey>State_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Trade_Actuals__c</fullName>
        <label>Trade Actuals</label>
        <summarizedField>State_Actuals__c.Trade_Actuals__c</summarizedField>
        <summaryForeignKey>State_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <formula>State_Code_Text__c +&apos;:&apos;+ TEXT(Product_Group__c) +&apos;:&apos;+ TEXT(Month__c) +&apos;:&apos;+ TEXT(Year__c) +&apos;:&apos;+ Plant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>State MRM Targets</label>
    <nameField>
        <label>State MRM Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State MRM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/StateActuals.cls
global class StateActuals implements Database.Batchable<sObject> 
{
    public String qrystr;
    public StateActuals(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<Invoice__c> invupdate = new List<Invoice__c>();
        List<State_Actuals__c> dalist = new List<State_Actuals__c>();
        Set<String> uniqcomb = new Set<String>();
        Set<String> uniqcomb1 = new Set<String>();
        Map<String,String> MRMMap = new Map<String,String>();
        Map<String,Double> TradeMap = new Map<String,Double>();
        Map<String,Double> NTradeMap = new Map<String,Double>();
        Map<String,Double> RailMap = new Map<String,Double>();
        Map<String,Double> RoadMap = new Map<String,Double>();
        Map<String,Double> DepotMap = new Map<String,Double>();
        Map<String,Double> DirectMap = new Map<String,Double>();
        
        for(Invoice__c inv : scope)
        {
            if(inv.Brand_Short_Form__c=='PSC' || inv.Brand_Short_Form__c=='OPC' || inv.Brand_Short_Form__c=='GGBS')
            if(((inv.Brand_Short_Form__c=='PSC' || inv.Brand_Short_Form__c=='OPC') && inv.Cust_Grp1_from_Master__c=='N01-Institutions') || inv.Brand_Short_Form__c=='GGBS')
            {
            if(inv.Distribution_Channel__c == '10')
            if(!TradeMap.containsKey(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)))
            {
                inv.State_Actuals_Process__c = true;
                uniqcomb.add(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10));
                TradeMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),inv.Qty__c);
            }
            else
            {
                inv.State_Actuals_Process__c = true;
                TradeMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),TradeMap.get(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10))+inv.Qty__c);
            }
            
            if(inv.Distribution_Channel__c == '20' || inv.Distribution_Channel__c == '50')
            if(!NTradeMap.containsKey(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)))
            {
                inv.State_Actuals_Process__c = true;
                uniqcomb.add(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10));
                NTradeMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),inv.Qty__c);
            }
            else
            {
                inv.State_Actuals_Process__c = true;
                NTradeMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),NTradeMap.get(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10))+inv.Qty__c);
            }
            
            if(!inv.Road_Invoice__c)
            if(!RailMap.containsKey(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)))
            {
                inv.State_Actuals_Process__c = true;
                uniqcomb.add(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10));
                RailMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),inv.Qty__c);
            }
            else
            {
                inv.State_Actuals_Process__c = true;
                RailMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),RailMap.get(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10))+inv.Qty__c);
            }
            
            if(inv.Road_Invoice__c)
            if(!RoadMap.containsKey(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)))
            {
                inv.State_Actuals_Process__c = true;
                uniqcomb.add(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10));
                RoadMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),inv.Qty__c);
            }
            else
            {
                inv.State_Actuals_Process__c = true;
                RoadMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),RoadMap.get(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10))+inv.Qty__c);
            }
            
            if(inv.Depot_Invoice__c)
            if(!DepotMap.containsKey(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)))
            {
                inv.State_Actuals_Process__c = true;
                uniqcomb.add(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10));
                DepotMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),inv.Qty__c);
            }
            else
            {
                inv.State_Actuals_Process__c = true;
                DepotMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),DepotMap.get(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10))+inv.Qty__c);
            }
            
            if(!inv.Depot_Invoice__c)
            if(!DirectMap.containsKey(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)))
            {
                inv.State_Actuals_Process__c = true;
                uniqcomb.add(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c);
                uniqcomb1.add(String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10));
                DirectMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),inv.Qty__c);
            }
            else
            {
                inv.State_Actuals_Process__c = true;
                DirectMap.put(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10),DirectMap.get(inv.State_Code__c+':'+inv.Brand_Short_Form__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Plant_Short_Form__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10))+inv.Qty__c);
            }
            invupdate.add(inv);
            }
        }
        
        System.debug('---uniqcomb---'+uniqcomb);
        System.debug('---uniqcomb1---'+uniqcomb1);
        System.debug('---TradeMap---'+TradeMap);
        List<State_MRM_Targets__c> mrmtgt = [Select id,Unique_Code__c from State_MRM_Targets__c where Unique_Code__c IN: uniqcomb];
        for(State_MRM_Targets__c mrm : mrmtgt)
        {
            MRMMap.put(mrm.Unique_Code__c,mrm.id);
        }
        System.debug('---MRMMap---'+MRMMap);
        System.debug('---TradeMap---'+TradeMap);
        System.debug('---NTradeMap---'+NTradeMap);
        System.debug('---RailMap---'+RailMap);
        System.debug('---RoadMap---'+RoadMap); 
        System.debug('---DepotMap---'+DepotMap);
        System.debug('---DirectMap---'+DirectMap);       
        /*for(MRM_Targets__c mrm : mrmtgt)
        {
            State_Actuals__c da = new State_Actuals__c();
            da.State_MRM_Targets__c = mrm.Id;
            if(TradeMap.containsKey(mrm.Unique_Code__c))
                da.Trade_Actuals__c = TradeMap.get(mrm.Unique_Code__c)==null ? 0 :TradeMap.get(mrm.Unique_Code__c);
            if(NTradeMap.containsKey(mrm.Unique_Code__c))
                da.Non_Trade_Actuals__c = NTradeMap.get(mrm.Unique_Code__c)==null ? 0 : NTradeMap.get(mrm.Unique_Code__c);
            if(RailMap.containsKey(mrm.Unique_Code__c))
                da.Depot_Actuals__c = RailMap.get(mrm.Unique_Code__c)==null ? 0 : RailMap.get(mrm.Unique_Code__c);
            if(RoadMap.containsKey(mrm.Unique_Code__c))
                da.Direct_Actuals__c = RoadMap.get(mrm.Unique_Code__c)==null ? 0 : RoadMap.get(mrm.Unique_Code__c);
            if(DepotMap.containsKey(mrm.Unique_Code__c))
                da.District_Rail_Actuals__c = DepotMap.get(mrm.Unique_Code__c)==null ? 0 : DepotMap.get(mrm.Unique_Code__c);
            if(DirectMap.containsKey(mrm.Unique_Code__c))
                da.District_Road_Actuals__c = DirectMap.get(mrm.Unique_Code__c)==null ? 0 : DirectMap.get(mrm.Unique_Code__c);
            dalist.add(da);
        }*/
        for(String st : uniqcomb)
        {
            for(String st1 : uniqcomb1)
            {
                State_Actuals__c da = new State_Actuals__c();
                da.State_MRM_Targets__c = MRMMap.get(st);
                if(TradeMap.containsKey(st+':'+st1))
                    da.Trade_Actuals__c = TradeMap.get(st+':'+st1)==null ? 0 :TradeMap.get(st+':'+st1);
                if(NTradeMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Non_Trade_Actuals__c = NTradeMap.get(st+':'+st1)==null ? 0 : NTradeMap.get(st+':'+st1);
                if(RailMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Rail_Actuals__c = RailMap.get(st+':'+st1)==null ? 0 : RailMap.get(st+':'+st1);
                if(RoadMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Road_Actuals__c = RoadMap.get(st+':'+st1)==null ? 0 : RoadMap.get(st+':'+st1);
                if(DepotMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Depot_Actuals__c = DepotMap.get(st+':'+st1)==null ? 0 : DepotMap.get(st+':'+st1);
                if(DirectMap.containsKey(st+':'+String.valueOf(st1)))
                    da.Direct_Actuals__c = DirectMap.get(st+':'+st1)==null ? 0 : DirectMap.get(st+':'+st1);
                da.Commercial_Invoice_Date__c = Date.valueOF(st1);
                //da.Product__c = st.split(':')[1];
                if(da.State_MRM_Targets__c !=null)
                if(!(da.Trade_Actuals__c==null && da.Non_Trade_Actuals__c ==null && da.Rail_Actuals__c ==null && da.Road_Actuals__c ==null && da.Depot_Actuals__c ==null && da.Direct_Actuals__c ==null))
                dalist.add(da);
            }
        }
        update invupdate;
        insert dalist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
    }
}