JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <formula>Owner:User.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Employee ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_T_Value__c</fullName>
        <formula>Total_value__c - (  MMC__c   + BED_Total__c + CGST_Value__c +  CSTT__c +  IGST_Value__c +  SGST_Value__c +  UGST_Value__c +   VAT_Value__c + Freight__c + (NSR_C_F_Value__c *  Qty__c ) +    (( NSR_Other_Discount__c ) - ABS(Additional_Discount__c) ) +  NSR_Packing_Cost__c + (NSR_PD_Value__c *  Qty__c ) + (NSR_PRFT_Value__c *  Qty__c ) + NSR_Rake_Discount__c +  Total_Adhoc_Discount__c )- IF( (Commercial_Invoice_Date_Formula__c &gt;  DATE(2017,04,30) &amp;&amp; Commercial_Invoice_Date_Formula__c &lt; DATE(2017,07,01)   &amp;&amp;  (Brand_Short_Form__c  = &apos;PSC  || CHD&apos;)) ,Discount__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Name__c</fullName>
        <label>Plant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <formula>Account__r.Sales_Office__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Office Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Description__c</fullName>
        <label>Sales Office Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/PIB_SO_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <formula>Employee_Code__c +&apos;:&apos;+ Month__c +&apos;:&apos;+ Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>PIB SO Targets</label>
    <nameField>
        <displayFormat>PIBSO-{0000000}</displayFormat>
        <label>PIB SO Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIB SO Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/PIB_Volume_NSR_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Cust_Grup_1__c</fullName>
        <label>Cust Grup 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>PIB_Bolume_NSR_Actuals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_Value__c</fullName>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PIB_SO_Targets__c</fullName>
        <label>PIB SO Targets</label>
        <referenceTo>PIB_SO_Targets__c</referenceTo>
        <relationshipName>PIB_Bolume_NSR_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QTY__c</fullName>
        <label>QTY</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territory_Code__c</fullName>
        <label>Territory Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>TEXT( YEAR( Date__c ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>PIB Volume &amp; NSR Actuals</label>
    <nameField>
        <displayFormat>PIBACTL-{00000000}</displayFormat>
        <label>PIB Volume &amp; NSR Actuals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIB Volume &amp; NSR Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/PIBVolNSR.cls
global class PIBVolNSR implements Database.Batchable<sObject> {

    public String qrystr;
    public Date myDate;
    public PIBVolNSR(String str)
    {
        myDate = System.today()-1;
        //qrystr = str+String.valueOf(myDate).substring(0,10);
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //String query = 'Select id,name,Plant_Name__c,Sales_Office_Description__c,Account__c,Commercial_Invoice_Date_Formula__c,Qty__c from Invoice__c where Commercial_Invoice_Date_Formula__c in (2016-12-23,2016-12-24,2016-12-25,2016-12-26,2016-12-27,2016-12-28,2016-12-29,2016-12-30,2016-12-31) and Account__c != null';
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<Invoice__c> invupdate = new List<Invoice__c>();
        List<PIB_Volume_NSR_Actuals__c> volnsrlist = new List<PIB_Volume_NSR_Actuals__c>();
        Map<String,Decimal> volMap = new Map<String,Decimal>();
        Map<String,Decimal> nsrMap = new Map<String,Decimal>();
        Map<String,String> pibMap = new Map<String,String>();
        Set<String> uniqcomb = new Set<String>();
        Set<String> uniqcomb1 = new Set<String>();
        for(Invoice__c inv : scope)
        {
            if(!volMap.containsKey(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c))
            {
                uniqcomb.add(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c);
                uniqcomb1.add(inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c);
                volMap.put(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c,inv.qty__c);
            }
            else
            {
                volMap.put(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c,volMap.get(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c)+inv.qty__c);
            }
            
            if(!nsrMap.containsKey(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c))
            {
                uniqcomb.add(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c);
                uniqcomb1.add(inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c);
                nsrMap.put(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c,inv.NSR_T_Value__c);
            }
            else
            {
                nsrMap.put(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c,nsrMap.get(inv.Employee_ID__c+':'+inv.Month_of_Commercial_Invoice_Date__c+':'+inv.Year__c+':'+inv.Sales_Office_Code__c+':'+String.valueOf(inv.Commercial_Invoice_Date_Formula__c).right(10)+':'+inv.Distribution_Channel__c+':'+inv.Brand_Short_Form__c+':'+inv.Cust_Grp1_from_Master__c+':'+inv.Account__c)+inv.NSR_T_Value__c);
            }
        }
        
        List<PIB_SO_Targets__c> piblist = [Select id,Unique_ID__c from PIB_SO_Targets__c where Unique_ID__c IN: uniqcomb];
        for(PIB_SO_Targets__c pib : piblist)
        {
            pibMap.put(pib.Unique_ID__c,pib.id);
        }  
        
        for(String st : uniqcomb)
        {
            for(String st1 : uniqcomb1)
            {
                PIB_Volume_NSR_Actuals__c vn = new PIB_Volume_NSR_Actuals__c();
                vn.PIB_SO_Targets__c = pibMap.get(st);
                if(volMap.containsKey(st+':'+st1))
                    vn.QTY__c = volMap.get(st+':'+st1)==null ? 0 :volMap.get(st+':'+st1);
                if(nsrMap.containsKey(st+':'+st1))
                    vn.NSR_Value__c = nsrMap.get(st+':'+st1)==null ? 0 : nsrMap.get(st+':'+st1);
                vn.Territory_Code__c = st1.split(':')[0];
                vn.Date__c = Date.valueOF(st1.split(':')[1]);
                vn.Distribution_Channel__c = st1.split(':')[2];
                vn.Product_Group__c = st1.split(':')[3];
                vn.Cust_Grup_1__c = st1.split(':')[4];
                vn.Customer__c = st1.split(':')[5];
                if(vn.PIB_SO_Targets__c !=null)
                if(!(vn.QTY__c == null && vn.NSR_Value__c == null))
                volnsrlist.add(vn);
            }
        }
        insert volnsrlist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        
    }
}