JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cust_Grp1_from_Master__c</fullName>
        <label>Cust.Grp1 from Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_T_Value__c</fullName>
        <formula>Total_value__c - (  MMC__c   + BED_Total__c + CGST_Value__c +  CSTT__c +  IGST_Value__c +  SGST_Value__c +  UGST_Value__c +   VAT_Value__c + Freight__c + (NSR_C_F_Value__c *  Qty__c ) +    (( NSR_Other_Discount__c ) - ABS(Additional_Discount__c) ) +  NSR_Packing_Cost__c + (NSR_PD_Value__c *  Qty__c ) + (NSR_PRFT_Value__c *  Qty__c ) + NSR_Rake_Discount__c +  Total_Adhoc_Discount__c )- IF( (Commercial_Invoice_Date_Formula__c &gt;  DATE(2017,04,30) &amp;&amp; Commercial_Invoice_Date_Formula__c &lt; DATE(2017,07,01)   &amp;&amp;  (Brand_Short_Form__c  = &apos;PSC  || CHD&apos;)) ,Discount__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StateNSR_Targets_Proccessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>StateNSR Targets Proccessed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_New_Actual__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_C_F_Actuals__c</fullName>
        <label>NSR C&amp;F Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Disc_Value_Actuals__c</fullName>
        <label>NSR Discount Value Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_MMC_Actuals__c</fullName>
        <label>NSR MMC Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Other_Actuals__c</fullName>
        <label>NSR Other Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PD_SPL_ADDL_Actual__c</fullName>
        <label>NSR PD+SPL+ADDL Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PRFT_Dump_Value_Actual__c</fullName>
        <label>NSR PRFT Dump Value Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Packing_Cost_Actual__c</fullName>
        <label>NSR Packing Cost Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Qty_Actuals__c</fullName>
        <label>NSR Qty Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Total_Basic_Price_Actuals__c</fullName>
        <label>NSR Total Basic Price Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Value_Actual__c</fullName>
        <label>NSR Value Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>District NSR Actual</label>
    <nameField>
        <label>NSR Actual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District NSR Actual</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State_MRM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>NSR_MMC_Actuals__c</fullName>
        <label>NSR MMC Actuals</label>
        <summarizedField>State_NSR_Actuals__c.NSR_MMC_Actuals__c</summarizedField>
        <summaryForeignKey>State_NSR_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NSR_Other_Actuals__c</fullName>
        <label>NSR Other Actuals</label>
        <summarizedField>State_NSR_Actuals__c.NSR_Other_Actuals__c</summarizedField>
        <summaryForeignKey>State_NSR_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NSR_PD_SPL_ADDL_Actual__c</fullName>
        <label>NSR PD+SPL+ADDL Actual</label>
        <summarizedField>State_NSR_Actuals__c.NSR_PD_SPL_ADDL_Actual__c</summarizedField>
        <summaryForeignKey>State_NSR_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NSR_Qty_Actuals__c</fullName>
        <label>NSR Qty Actuals</label>
        <summarizedField>State_NSR_Actuals__c.NSR_Qty_Actuals__c</summarizedField>
        <summaryForeignKey>State_NSR_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NSR_Total_Basic_Price_Actuals__c</fullName>
        <label>NSR Total Basic Price Actuals</label>
        <summarizedField>State_NSR_Actuals__c.NSR_Total_Basic_Price_Actuals__c</summarizedField>
        <summaryForeignKey>State_NSR_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NSR_Value_Actuals__c</fullName>
        <label>NSR Value Actuals</label>
        <summarizedField>State_NSR_Actuals__c.NSR_Value_Actuals__c</summarizedField>
        <summaryForeignKey>State_NSR_Actuals__c.State_MRM_Targets__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <formula>State_Code_Text__c +&apos;:&apos;+ TEXT(Product_Group__c) +&apos;:&apos;+ TEXT(Month__c) +&apos;:&apos;+ TEXT(Year__c) +&apos;:&apos;+ Plant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>State MRM Targets</label>
    <nameField>
        <label>State MRM Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State MRM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/State_NSR_Actuals__c.object
<CustomObject>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_C_F_Actuals__c</fullName>
        <label>NSR C&amp;F Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_MMC_Actuals__c</fullName>
        <label>NSR MMC Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Other_Actuals__c</fullName>
        <label>NSR Other Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PD_SPL_ADDL_Actual__c</fullName>
        <label>NSR PD+SPL+ADDL Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PRFT_Dump_Value_Actual__c</fullName>
        <label>NSR PRFT Dump Value Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Packing_Cost_Actual__c</fullName>
        <label>NSR Packing Cost Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Qty_Actuals__c</fullName>
        <label>NSR Qty Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Total_Basic_Price_Actuals__c</fullName>
        <label>NSR Total Basic Price Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Value_Actuals__c</fullName>
        <label>NSR Value Actuals</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_MRM_Targets__c</fullName>
        <label>State MRM Targets</label>
        <referenceTo>State_MRM_Targets__c</referenceTo>
        <relationshipLabel>State NSR Actuals</relationshipLabel>
        <relationshipName>State_NSR_Actuals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State NSR Actuals</label>
    <nameField>
        <label>State NSR Actuals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State NSR Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/StateNSRActuals.cls
global class StateNSRActuals implements Database.Batchable<sObject> 
{
    public String qrystr;
    public StateNSRActuals(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<Invoice__c> nsrupdate = new List<Invoice__c>();
        List<State_NSR_Actuals__c> nsrlist = new List<State_NSR_Actuals__c>();
        Set<String> uniqcomb = new Set<String>();
        Set<String> uniqcomb1 = new Set<String>();
        Map<String,String> MRMMap = new Map<String,String>();
        Map<String,Double> TradeMap = new Map<String,Double>();
        Map<String,Double> NTradeMap = new Map<String,Double>();
        Map<String,Double> QtyMap = new Map<String,Double>();
        Map<String,Double> TBPMap = new Map<String,Double>();
        Map<String,Double> DiscValMap = new Map<String,Double>();
        Map<String,Double> PDSPLAALMap = new Map<String,Double>();
        Map<String,Double> OtherMap = new Map<String,Double>();
        Map<String,Double> MMCMap = new Map<String,Double>();
        Map<String,Double> CFMap = new Map<String,Double>();
        Map<String,Double> PFRTMap = new Map<String,Double>();
        Map<String,Double> PackCostMap = new Map<String,Double>();
        Map<String,Double> NSRValMap = new Map<String,Double>();
        
        
        for(Invoice__c nsr : scope)
        {
            if(nsr.Distribution_Channel__c == '10' || nsr.Distribution_Channel__c == '20' || nsr.Distribution_Channel__c == '50')
            {
                if(nsr.Brand_Short_Form__c=='PSC' || nsr.Brand_Short_Form__c=='CHD' || nsr.Brand_Short_Form__c=='GGBS' || nsr.Brand_Short_Form__c=='OPC')
                if(((nsr.Brand_Short_Form__c=='PSC' || nsr.Brand_Short_Form__c=='OPC' || nsr.Brand_Short_Form__c=='CHD') && nsr.Cust_Grp1_from_Master__c=='N01-Institutions') || nsr.Brand_Short_Form__c=='GGBS')
                {                    
                    System.debug('---NSR Null'+nsr.NSR_T_Value__c);
                    if(nsr.Qty__c!=null)
                    if(!QtyMap.containsKey(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
                    {
                        nsr.StateNSR_Targets_Proccessed__c = true;
                        uniqcomb.add(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
                        uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
                        QtyMap.put(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Qty__c);
                    }
                    else
                    {
                        nsr.StateNSR_Targets_Proccessed__c = true;
                        QtyMap.put(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,QtyMap.get(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Qty__c);
                    }
                    System.debug('---NSRValMap---'+NSRValMap);
                    if(nsr.NSR_T_Value__c!=null)
                    if(!NSRValMap.containsKey(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
                    {
                        nsr.StateNSR_Targets_Proccessed__c = true;
                        uniqcomb.add(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
                        uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
                        NSRValMap.put(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_T_Value__c);
                    }
                    else
                    {
                        nsr.StateNSR_Targets_Proccessed__c = true;
                        NSRValMap.put(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,NSRValMap.get(nsr.State_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_T_Value__c);
                    }
                }
                nsrupdate.add(nsr);
            }
        }
        System.debug('---uniqcomb---'+uniqcomb);
        List<State_MRM_Targets__c > mrmtgt = [Select id,Unique_Code__c from State_MRM_Targets__c  where Unique_Code__c IN: uniqcomb];
        for(State_MRM_Targets__c  mrm : mrmtgt)
        {
            MRMMap.put(mrm.Unique_Code__c,mrm.id);
        }        
        System.debug('---MRMMap---'+MRMMap);
        System.debug('---DiscValMap---'+DiscValMap);
        /*for(State_MRM_Targets__c  mrm : mrmtgt)
        {
            NSR_New_Actual__c da = new NSR_New_Actual__c();
            da.State_MRM_Targets__c  = mrm.Id;
            if(QtyMap.containsKey(mrm.Unique_Code__c))
                da.NSR_Qty_Actuals__c = QtyMap.get(mrm.Unique_Code__c)==null ? 0 :QtyMap.get(mrm.Unique_Code__c);
            if(TBPMap.containsKey(mrm.Unique_Code__c))
                da.NSR_Total_Basic_Price_Actuals__c = TBPMap.get(mrm.Unique_Code__c)==null ? 0 : TBPMap.get(mrm.Unique_Code__c);
            if(DiscValMap.containsKey(mrm.Unique_Code__c))
                da.NSR_Disc_value_Actuals__c = DiscValMap.get(mrm.Unique_Code__c)==null ? 0 : DiscValMap.get(mrm.Unique_Code__c);
            if(PDSPLAALMap.containsKey(mrm.Unique_Code__c))
                da.NSR_PD_SPL_ADDL_Actual__c = PDSPLAALMap.get(mrm.Unique_Code__c)==null ? 0 : PDSPLAALMap.get(mrm.Unique_Code__c);
            if(OtherMap.containsKey(mrm.Unique_Code__c))
                da.NSR_Other_Actuals__c = OtherMap.get(mrm.Unique_Code__c)==null ? 0 : OtherMap.get(mrm.Unique_Code__c);
            if(MMCMap.containsKey(mrm.Unique_Code__c))
                da.NSR_MMC_Actuals__c = MMCMap.get(mrm.Unique_Code__c)==null ? 0 : MMCMap.get(mrm.Unique_Code__c);
            if(CFMap.containsKey(mrm.Unique_Code__c))
                da.NSR_C_F_Actuals__c = CFMap.get(mrm.Unique_Code__c)==null ? 0 : CFMap.get(mrm.Unique_Code__c);
            if(PFRTMap.containsKey(mrm.Unique_Code__c))
                da.NSR_PRFT_Dump_Value_Actual__c = PFRTMap.get(mrm.Unique_Code__c)==null ? 0 : PFRTMap.get(mrm.Unique_Code__c);
            if(PackCostMap.containsKey(mrm.Unique_Code__c))
                da.NSR_Packing_Cost_Actual__c = PackCostMap.get(mrm.Unique_Code__c)==null ? 0 : PackCostMap.get(mrm.Unique_Code__c);
            if(NSRValMap.containsKey(mrm.Unique_Code__c))
                da.NSR_Value_Actual__c = NSRValMap.get(mrm.Unique_Code__c)==null ? 0 : NSRValMap.get(mrm.Unique_Code__c);
            nsrlist.add(da);
        }*/
        for(String st : uniqcomb)
        {
            for(String st1 : uniqcomb1)
            {
                State_NSR_Actuals__c da = new State_NSR_Actuals__c();
                da.State_MRM_Targets__c  = MRMMap.get(st);
                if(QtyMap.containsKey(st+':'+st1))
                    da.NSR_Qty_Actuals__c = QtyMap.get(st+':'+st1)==null ? 0 :QtyMap.get(st+':'+st1);    
                if(NSRValMap.containsKey(st+':'+st1))
                    da.NSR_Value_Actuals__c = NSRValMap.get(st+':'+st1)==null ? 0 : NSRValMap.get(st+':'+st1);
                da.Commercial_Invoice_Date__c = Date.valueOF(st1.split(':')[0]);
                da.Distribution_Channel__c = st1.split(':')[1];
                if(da.State_MRM_Targets__c !=null)
                if(!(da.NSR_Qty_Actuals__c ==null && da.NSR_Value_Actuals__c ==null))
                nsrlist.add(da);
            }
        }
        update nsrupdate;
        insert nsrlist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
    }
}