JSW Devsb/src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Adhoc_Incentive_Value__c</fullName>
        <label>Adhoc Incentive Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Form__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date_Formula__c</fullName>
        <formula>Commercial_Invoice_Date__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date SAP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Freight__c</fullName>
        <label>Freight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMC__c</fullName>
        <label>MMC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_of_Commercial_Invoice_Date__c</fullName>
        <formula>CASE( MONTH(  Commercial_Invoice_Date_Formula__c ),  1, &quot;January&quot;, 2, &quot;February&quot;, 3, &quot;March&quot;, 4, &quot;April&quot;, 5, &quot;May&quot;, 6, &quot;June&quot;, 7, &quot;July&quot;, 8, &quot;August&quot;, 9, &quot;September&quot;, 10, &quot;October&quot;, 11, &quot;November&quot;, 12, &quot;December&quot;, &quot;none&quot;)</formula>
        <label>Month of Commercial Invoice Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSR_C_F_Discount__c</fullName>
        <label>NSR C&amp;F Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Other_Discount__c</fullName>
        <label>NSR Other Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PD_Value__c</fullName>
        <label>NSR PD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_PRFT_Dump_Discout__c</fullName>
        <label>NSR PRFT Dump Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Rake_Discount__c</fullName>
        <label>NSR Rake Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_T_Value__c</fullName>
        <formula>Total_value__c - (  MMC__c   + BED_Total__c + CGST_Value__c +  CSTT__c +  IGST_Value__c +  SGST_Value__c +  UGST_Value__c +   VAT_Value__c + Freight__c + (NSR_C_F_Value__c *  Qty__c ) +    (( NSR_Other_Discount__c ) - ABS(Additional_Discount__c) ) +  NSR_Packing_Cost__c + (NSR_PD_Value__c *  Qty__c ) + (NSR_PRFT_Value__c *  Qty__c ) + NSR_Rake_Discount__c +  Total_Adhoc_Discount__c )- IF( (Commercial_Invoice_Date_Formula__c &gt;  DATE(2017,04,30) &amp;&amp; Commercial_Invoice_Date_Formula__c &lt; DATE(2017,07,01)   &amp;&amp;  (Brand_Short_Form__c  = &apos;PSC  || CHD&apos;)) ,Discount__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NSR_Targets_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NSR Targets Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PAcking_Cost__c</fullName>
        <label>PAcking Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plant_Short_Form__c</fullName>
        <label>Plant Short Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty in MT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <formula>Account__r.Sales_Office__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Office Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_tax__c</fullName>
        <label>Total tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <label>Total value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>Text(YEAR(  Commercial_Invoice_Date_Formula__c  ))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/MRM_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Code__c</fullName>
        <formula>Sales_Office__c +&apos;:&apos;+ TEXT(Product__c) +&apos;:&apos;+ TEXT(Month__c) +&apos;:&apos;+ Year__c +&apos;:&apos;+  Plant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>MRM Target</label>
    <nameField>
        <displayFormat>MRM-{0000000000}</displayFormat>
        <label>MRM Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/NSR_New_Actual__c.object
<CustomObject>
    <fields>
        <fullName>Adhoc_Incentive_Value__c</fullName>
        <label>Adhoc Incentive Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CF_Discount__c</fullName>
        <label>CF Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commercial_Invoice_Date__c</fullName>
        <label>Commercial Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <label>Distribution Channel</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frieght__c</fullName>
        <label>Frieght</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMC__c</fullName>
        <label>MMC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MRM_Targets__c</fullName>
        <label>MRM Target</label>
        <referenceTo>MRM_Targets__c</referenceTo>
        <relationshipName>NSR_Actual</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NSR_Value__c</fullName>
        <label>NSR Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Discount__c</fullName>
        <label>Other Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PD_Values__c</fullName>
        <label>PD Values</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRFT_Dump_Discount__c</fullName>
        <label>PRFT Dump Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packing_Cost__c</fullName>
        <label>Packing Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rake_Discount__c</fullName>
        <label>Rake Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Tax__c</fullName>
        <label>Total Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>District NSR Actual</label>
    <nameField>
        <label>NSR Actual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District NSR Actual</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

JSW Devsb/src/classes/NSRActuals.cls
global class NSRActuals implements Database.Batchable<sObject> 
{
    public String qrystr;
    public NSRActuals(String str)
    {
        qrystr = str;
        System.debug('----->'+qrystr);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        String query = qrystr;
        System.debug('----->'+query);
        return Database.getQueryLocator(qrystr);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> scope) 
    {
        List<Invoice__c> nsrupdate = new List<Invoice__c>();
        List<NSR_New_Actual__c> nsrlist = new List<NSR_New_Actual__c>();
        Set<String> uniqcomb = new Set<String>();
        Set<String> uniqcomb1 = new Set<String>();
        Map<String,String> MRMMap = new Map<String,String>();
        Map<String,Double> TVMap = new Map<String,Double>();
        Map<String,Double> NSRPDMap = new Map<String,Double>();
        Map<String,Double> NSROtherMap = new Map<String,Double>();
        Map<String,Double> NSRPRFTMap = new Map<String,Double>();
        Map<String,Double> NSRCFMap = new Map<String,Double>();
        Map<String,Double> PackCostMap = new Map<String,Double>();
        Map<String,Double> FreightMap = new Map<String,Double>();
        Map<String,Double> TTMap = new Map<String,Double>();
        Map<String,Double> RakeMap = new Map<String,Double>();
        Map<String,Double> AdhocMap = new Map<String,Double>();
        Map<String,Double> MMCMap = new Map<String,Double>();
        Map<String,Double> QtyMap = new Map<String,Double>();
        Map<String,Double> NSRValMap = new Map<String,Double>();
        
        
        for(Invoice__c nsr : scope)
		{
			if(nsr.Distribution_Channel__c == '10' || nsr.Distribution_Channel__c == '20' || nsr.Distribution_Channel__c == '50')
			{
				if(nsr.Total_value__c != null)
				if(!TVMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					TVMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Total_value__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					TVMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,TVMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Total_value__c);
				}
				
				if(nsr.NSR_PD_Value__c != null)
				if(!NSRPDMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					NSRPDMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_PD_Value__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					NSRPDMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,NSRPDMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_PD_Value__c);
				}
				
				if(nsr.NSR_Other_Discount__c != null)
				if(!NSROtherMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					NSROtherMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_Other_Discount__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					NSROtherMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,NSROtherMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_Other_Discount__c);
				}
				
				if(nsr.NSR_PRFT_Dump_Discout__c != null)
				if(!NSRPRFTMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					NSRPRFTMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_PRFT_Dump_Discout__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					NSRPRFTMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,NSRPRFTMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_PRFT_Dump_Discout__c);
				}
				
				if(nsr.NSR_C_F_Discount__c != null)
				if(!NSRCFMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					NSRCFMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_C_F_Discount__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					NSRCFMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,NSRCFMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_C_F_Discount__c);
				}
				
				if(nsr.Packing_Cost__c!=null)
				if(!PackCostMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					PackCostMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Packing_Cost__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					PackCostMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,PackCostMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Packing_Cost__c);
				}
				
				if(nsr.Freight__c!=null)
				if(!FreightMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					FreightMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Freight__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					FreightMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,FreightMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Freight__c);
				}
				
				if(nsr.Total_Tax__c!=null)
				if(!TTMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					TTMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Total_Tax__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					TTMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,TTMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Total_Tax__c);
				}
				
				if(nsr.NSR_Rake_Discount__c!=null)
				if(!RakeMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					RakeMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_Rake_Discount__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					RakeMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,RakeMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_Rake_Discount__c);
				}
				
				if(nsr.Adhoc_Incentive_Value__c!=null)
				if(!AdhocMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					AdhocMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Adhoc_Incentive_Value__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					AdhocMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,AdhocMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Adhoc_Incentive_Value__c);
				}
				
				if(nsr.MMC__c!=null)
				if(!MMCMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					MMCMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.MMC__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					MMCMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,MMCMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.MMC__c);
				}     
				
				if(nsr.Qty__c!=null)
				if(!QtyMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					QtyMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.Qty__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					QtyMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,QtyMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.Qty__c);
				}
				
				if(nsr.NSR_T_Value__c!=null)
				if(!NSRValMap.containsKey(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c))
				{
					nsr.NSR_Targets_Processed__c = true;
					uniqcomb.add(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c);
					uniqcomb1.add(String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c);
					NSRValMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,nsr.NSR_T_Value__c);
				}
				else
				{
					nsr.NSR_Targets_Processed__c = true;
					NSRValMap.put(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c,NSRValMap.get(nsr.Sales_Office_Code__c+':'+nsr.Brand_Short_Form__c+':'+nsr.Month_of_Commercial_Invoice_Date__c+':'+nsr.Year__c+':'+nsr.Plant_Short_Form__c+':'+String.valueOf(nsr.Commercial_Invoice_Date_Formula__c).right(10)+':'+nsr.Distribution_Channel__c)+nsr.NSR_T_Value__c);
				}
				nsrupdate.add(nsr);
			}
		}
        System.debug('---uniqcomb---'+uniqcomb);
        List<MRM_Targets__c> mrmtgt = [Select id,Unique_Code__c from MRM_Targets__c where Unique_Code__c IN: uniqcomb];
        for(MRM_Targets__c mrm : mrmtgt)
        {
            MRMMap.put(mrm.Unique_Code__c,mrm.id);
        }        
        System.debug('---MRMMap---'+MRMMap);
        System.debug('---NSRValMap---'+NSRValMap);
		
        for(String st : uniqcomb)
        {
            for(String st1 : uniqcomb1)
            {
                NSR_New_Actual__c da = new NSR_New_Actual__c();
                da.MRM_Targets__c = MRMMap.get(st);
                if(TVMap.containsKey(st+':'+st1))
                    da.Total_Value__c = TVMap.get(st+':'+st1)==null ? 0 :TVMap.get(st+':'+st1);
                if(NSRPDMap.containsKey(st+':'+st1))
                    da.PD_Values__c = NSRPDMap.get(st+':'+st1)==null ? 0 : NSRPDMap.get(st+':'+st1);
                if(NSROtherMap.containsKey(st+':'+st1))
                    da.Other_Discount__c = NSROtherMap.get(st+':'+st1)==null ? 0 : NSROtherMap.get(st+':'+st1);
                if(NSRPRFTMap.containsKey(st+':'+st1))
                    da.PRFT_Dump_Discount__c = NSRPRFTMap.get(st+':'+st1)==null ? 0 : NSRPRFTMap.get(st+':'+st1);
                if(NSRCFMap.containsKey(st+':'+st1))
                    da.CF_Discount__c = NSRCFMap.get(st+':'+st1)==null ? 0 : NSRCFMap.get(st+':'+st1);
                if(PackCostMap.containsKey(st+':'+st1))
                    da.Packing_Cost__c = PackCostMap.get(st+':'+st1)==null ? 0 : PackCostMap.get(st+':'+st1);
                if(FreightMap.containsKey(st+':'+st1))
                    da.Frieght__c = FreightMap.get(st+':'+st1)==null ? 0 : FreightMap.get(st+':'+st1);
                if(TTMap.containsKey(st+':'+st1))
                    da.Total_Tax__c = TTMap.get(st+':'+st1)==null ? 0 : TTMap.get(st+':'+st1);
                if(RakeMap.containsKey(st+':'+st1))
                    da.Rake_Discount__c = RakeMap.get(st+':'+st1)==null ? 0 : RakeMap.get(st+':'+st1);
                if(AdhocMap.containsKey(st+':'+st1))
                    da.Adhoc_Incentive_Value__c = AdhocMap.get(st+':'+st1)==null ? 0 : AdhocMap.get(st+':'+st1);
				if(MMCMap.containsKey(st+':'+st1))
                    da.MMC__c = MMCMap.get(st+':'+st1)==null ? 0 : MMCMap.get(st+':'+st1);
				if(QtyMap.containsKey(st+':'+st1))
                    da.Quantity__c = QtyMap.get(st+':'+st1)==null ? 0 : QtyMap.get(st+':'+st1);
				if(NSRValMap.containsKey(st+':'+st1))
                    da.NSR_Value__c = NSRValMap.get(st+':'+st1)==null ? 0 : NSRValMap.get(st+':'+st1);
                da.Commercial_Invoice_Date__c = Date.valueOF(st1.split(':')[0]);
                da.Distribution_Channel__c = st1.split(':')[1];
                if(da.MRM_Targets__c !=null)
                if(!(da.Total_Value__c ==null &&  da.PD_Values__c ==null && da.Other_Discount__c ==null && da.PRFT_Dump_Discount__c ==null && da.CF_Discount__c ==null && da.Packing_Cost__c ==null &&  da.Frieght__c ==null && da.Total_Tax__c ==null && da.Rake_Discount__c ==null && da.Adhoc_Incentive_Value__c ==null &&  da.MMC__c ==null && da.Quantity__c ==null && da.NSR_Value__c ==null))
                nsrlist.add(da);
            }
        }
        update nsrupdate;
        insert nsrlist;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
    }
}