JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Week_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Month_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Month Plan</label>
        <referenceTo>Month_Plan__c</referenceTo>
        <relationshipLabel>Week Plan</relationshipLabel>
        <relationshipName>Week_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Submitted for Approval</label>
        <type>Checkbox</type>
    </fields>
    <label>Week Plan</label>
    <nameField>
        <label>Week Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Week Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/ApprovalSubmission.cls
public class ApprovalSubmission{
    public String pjpid {get; set;}
    public List<Week_Plan__c> wplist {get; set;}
    
    public ApprovalSubmission(){
        pjpid = ApexPages.currentPage().getParameters().get('id');
        wplist = [select id,name,Start_Date__c,End_Date__c,Month_Plan__c,Size__c,Submitted_for_Approval__c,Status__c from Week_Plan__c where Month_Plan__c =: pjpid and (Status__c = 'New Request' or Status__c = 'Rejected')];
    }
    
    public pageReference pjptab(){
        pageReference pref = new pageReference('/a04/o');
        pref.setRedirect(true);
        return pref;
    }
    
    public pageReference submitforapproval(){
        List<Week_Plan__c> sublist = new List<Week_Plan__c>();
        for(Week_Plan__c wp : wplist){
            if(wp.Submitted_for_Approval__c == true)
            sublist.add(wp);
        }
        
        for(Week_Plan__c wp : sublist){
            try{
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval');
            req1.setObjectId(wp.id);
            req1.setSubmitterId(userInfo.getUserId());
            Approval.ProcessResult result = Approval.process(req1);
            }catch(Exception ex){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select your approver as Manager'));
            }
        }
        
        //PageReference pref = new PageReference('/apex/DailyVisitPlanView?id='+pjpid);
        PageReference pref = new PageReference('/'+pjpid);
        pref.setRedirect(true);
        return pref;
    }
}