JSW Devsb/src/objects/Month_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Month_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PJP</label>
    <nameField>
        <label>Month Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PJP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/RemoveRelatedVisitsTest.cls
@isTest
public class RemoveRelatedVisitsTest {
    public static testmethod void month(){

User u = [select firstname from user where id=:userinfo.getuserid()];
Account ac=new Account();
ac.name='Mohan';
insert ac;
 
Month_Plan__c MPC=new Month_Plan__c();
MPC.Name='plan';
MPC.Start_Date__c=system.today()-30;
MPC.End_Date__c=system.today();
MPC.User__c=u.id;
MPC.Year__c ='2016';
insert MPC;
delete  MPC;   

    }
}