JSW Devsb/src/objects/NSR_PD_Values__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PD_Value__c</fullName>
        <label>PD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Be_Processed__c</fullName>
        <defaultValue>true</defaultValue>
        <label>To Be Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>distribution_Channel__c</fullName>
        <label>distribution Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>NSR PD Values</label>
    <nameField>
        <label>NSR PD Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSR PD Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/runBatches.cls
global class runBatches{
   @InvocableMethod
   public static void runBatches(List<String> details) 
   {
       /*if(batchname = 'NSRPDClass')
       {
           String query = 'Select district_code__c,Product__c,distribution_Channel__c,From_Date__c,To_Date__c,PD_Value__c,To_Be_Processed__c from NSR_PD_Values__c where From_Date__c>='+fromdate+' AND To_Date__c<='+todate+'';
           NSRPDValues bat = new NSRPDValues(query);
           Database.executeBatch(bat,1);
       }  */
       System.debug('List'+details); 
   }
}