JSW Devsb/src/objects/Order_Booking_Line__c.object
<CustomObject>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipName>Order_Booking_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SO_Number__c</fullName>
        <label>SO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order request Line Item</label>
    <nameField>
        <displayFormat>ORL{000000000}</displayFormat>
        <label>Order Booking Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order request Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Booking_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Order_Booking_Line_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Booking Line Item</label>
        <referenceTo>Order_Booking_Line__c</referenceTo>
        <relationshipLabel>Order request line Schedule</relationshipLabel>
        <relationshipName>Order_Booking_Schedule</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order request line Schedule</relationshipLabel>
        <relationshipName>Order_Booking_Schedule</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SO_Number__c</fullName>
        <label>SO Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Qty__c</fullName>
        <label>Schedule Qty</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order request line Schedule</label>
    <nameField>
        <displayFormat>ORS{0000000000}</displayFormat>
        <label>Order Booking Schedule  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order request line Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Code/Depot Code</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Requests</relationshipLabel>
        <relationshipName>Order_Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Request_Header__c</fullName>
        <externalId>true</externalId>
        <label>Order Request Header</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Satus_Message__c</fullName>
        <label>Status Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>So_Number__c</fullName>
        <label>So Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Order Request</label>
    <nameField>
        <displayFormat>OR-{0000000000}</displayFormat>
        <label>Order Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/classes/populateOrderRequestTest.cls
@isTest
public class populateOrderRequestTest {
    public static testmethod void orderMethod(){
        account ac=new account();
        ac.name='test';
        insert ac;
        Order_Request__c orq=new Order_Request__c();
        orq.Order_Request_Header__c = '1234';
        orq.Satus_Message__c = 'okay';
        orq.Account__c=ac.id;
        orq.Status__c = 'Good';
        orq.SO_Number__c = '1234';
        insert orq;
        orq.Contact_Number__c='56456';
        update orq;
        Order_Booking_Line__c obl=new Order_Booking_Line__c();
        obl.Order_Request__c = orq.id;
        insert obl;
        Order_Booking_Schedule__c obs=new Order_Booking_Schedule__c();
        obs.Order_Request__c = orq.id;
        obs.Schedule_Date__c = System.today();
        obs.Schedule_Qty__c = '100';
        obs.Order_Booking_Line_Item__c = obl.id;
        insert obs;
        Order_Request__c ordr = [select Order_Request_Header__c,Satus_Message__c,Status__c,SO_Number__c from Order_Request__c where id=:orq.id];
        ordr.Satus_Message__c = 'Okay 2';
        Update ordr;
    }
}