JSW Devsb/src/objects/Project_Site__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IHB Sites</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sites</label>
    <nameField>
        <label>Project Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Check_In_Time__c</fullName>
        <formula>IF(Check_In__c != null, DATETIMEVALUE(Check_In__c), null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>If_Potential_Lead_Share_with_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Potential Lead Share with Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Site</label>
        <referenceTo>Project_Site__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>IF( Account__c != null, &apos;Account&apos;, &apos;&apos;) + 
 IF( Depot__c != null, &apos;Depot&apos;, &apos;&apos;) + 
 IF( Area__c != null , &apos;Area&apos;, &apos;&apos;) +
 IF( Business_Partner__c != null , &apos;Business Partner&apos;, &apos;&apos;) +
 IF( Customer_Type__c != null , &apos;Customer Type&apos;, &apos;&apos;) +
 IF( Event__c != null , &apos;Event&apos;, &apos;&apos;) +
 IF( Influencer__c != null , &apos;Influencer&apos;, &apos;&apos;) +
 IF( Lead__c != null , &apos;Lead&apos;, &apos;&apos;) +
 IF( Project_Site__c != null , &apos;Project Site&apos;, &apos;&apos;) +
 IF( Territory__c != null , &apos;Territory&apos;, &apos;&apos;) +
 IF( General_Visit__c = true , &apos;General&apos;, &apos;&apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/PotentialLeadNotifScheduler.cls
global class PotentialLeadNotifScheduler implements Schedulable{
 
    global void execute(SchedulableContext sc){
        String query = 'select id,OwnerID,If_Potential_Lead_Share_with_Manager__c,Name,Type__c,Project_Site__c from Visit__c where If_Potential_Lead_Share_with_Manager__c = true and Check_In_Time__c = TODAY';

        PotentialLeadNotif leadnotif = new PotentialLeadNotif(query);
        database.ExecuteBatch(leadnotif);

    }
}