JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/visitedcontrollerTest.cls
@isTest
public class visitedcontrollerTest 
{
    public static testmethod void vstcntl()
    {
        Visit__c vst = new Visit__c();
        vst.Start__c = system.now();
        vst.End__c = system.now();
        visitedcontroller vc = new visitedcontroller();        
        vc.vst = vst;
        vc.save();
        vst.Start__c = system.now()-1;
        vc.vst = vst;
        vc.save();
        vst.Start__c = system.now()+1;
        vc.vst = vst;
        vc.save();
        vc.cancel();
    }
}