JSW Devsb/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Sub_Type__c</fullName>
        <label>Activity Sub Type</label>
        <picklist>
            <controllingField>Activity_Type__c</controllingField>
            <picklistValues>
                <fullName>Introductory visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site demo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical aspects</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint redressal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-conversion/ customer retention</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-sale</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Any_image_to_be_captured__c</fullName>
        <label>Any image to be captured</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_Out__c</fullName>
        <label>Check Out</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition_of_Godown__c</fullName>
        <label>Condition of Godown</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not as per ISP</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Construction_Stage__c</fullName>
        <label>Construction Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nearing Completion</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Damage_Stock_Ageing_for_CC__c</fullName>
        <label>Damage Stock Ageing for CC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Damage_Stock_Ageing_for_CHD__c</fullName>
        <label>Damage Stock Ageing for CHD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Damage_Stock_Ageing_for_OPC__c</fullName>
        <label>Damage Stock Ageing for OPC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Damage_Stock_Ageing_for_PSC__c</fullName>
        <label>Damage Stock Ageing for PSC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Damaged_Cement_MT_for_CC__c</fullName>
        <label>Damaged Cement (MT) for CC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Damaged_Cement_MT_for_CHD__c</fullName>
        <label>Damaged Cement (MT) for CHD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Damaged_Cement_MT_for_OPC__c</fullName>
        <label>Damaged Cement (MT) for OPC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Damaged_Cement_MT_for_PSC__c</fullName>
        <label>Damaged Cement (MT) for PSC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Inspection__c</fullName>
        <defaultValue>today()</defaultValue>
        <label>Date of Inspection</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>F_I_F_O_movement__c</fullName>
        <label>F.I-F.O movement</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Godown_Stock_as_on_Month_end_MT_for_CC__c</fullName>
        <label>Godown Stock as on Month end (MT) for CC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_Stock_as_on_Month_end_MT_for_OPC__c</fullName>
        <label>Godown Stock on Month end (MT) for OPC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_Stock_as_on_Month_end_MT_for_PSC__c</fullName>
        <label>Godown Stock as on Month end (MT) for PS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_Stock_on_Month_end_MT_for_CHD__c</fullName>
        <label>Godown Stock as Month end (MT) for CHD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_stock_MT_for_CHD__c</fullName>
        <label>Godown stock (MT) for CHD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_stock_MT_for_OPC__c</fullName>
        <label>Godown stock (MT) for OPC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_stock_MT_for_PSC__c</fullName>
        <label>Godown stock (MT) for PSC</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Godown_stock_MT_for_composite_Cement__c</fullName>
        <label>Godown stock (MT) for composite Cement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Good_Stock_Ageing_for_CC__c</fullName>
        <label>Good Stock Ageing for CC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Good_Stock_Ageing_for_CHD__c</fullName>
        <label>Good Stock Ageing for CHD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Good_Stock_Ageing_for_OPC__c</fullName>
        <label>Good Stock Ageing for OPC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Good_Stock_Ageing_for_PSC__c</fullName>
        <label>Good Stock Ageing for PSC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>If_Potential_Lead_Share_with_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Potential Lead Share with Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JSW_Bag_Visibility__c</fullName>
        <label>JSW Bag Visibility</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>JSW_Shop_Board_Condition__c</fullName>
        <label>JSW Shop Board Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Absent</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LATF_Name__c</fullName>
        <label>LATF Name</label>
        <picklist>
            <picklistValues>
                <fullName>Y Shrikanth Reddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J Ramanjaeyulu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K Raghvendra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K Nagarjuna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vishnu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akhil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shiras M.V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sagar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tousif</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hemanth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chetan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R Mouleswaran</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V. Charles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R Vibhusan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rajesh Kumar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A Muthukumar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manoj</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mr. Vishal</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Amount_Collected_by_SO__c</fullName>
        <label>Payment collected in current visit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pending_Payment_Amount_Committed_Date__c</fullName>
        <label>Pending Payment Committed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_Inspection__c</fullName>
        <label>Previous Inspection</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>PSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Composite cement</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Visit__c</fullName>
        <label>Purpose of Visit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Details of the Visit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Seggregation_of_good_damaged_cement__c</fullName>
        <label>Seggregation of good &amp; damaged cement</label>
        <picklist>
            <picklistValues>
                <fullName>Good</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_demo_type__c</fullName>
        <label>Site demo type</label>
        <picklist>
            <picklistValues>
                <fullName>Cube casting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Slab Supervision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cover block Demo</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stacking_pattern_As_per_ISP__c</fullName>
        <label>Stacking pattern (As per ISP?)</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stock_level_JSW__c</fullName>
        <label>JSW stock level (number of bags)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visit_by_TSO_LATF__c</fullName>
        <label>Visit by TSO/LATF</label>
        <picklist>
            <picklistValues>
                <fullName>TSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATF</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

JSW Devsb/src/classes/VisitCheckIn.cls
@RestResource(urlMapping='/VisitCheckIn/*')
global with sharing class VisitCheckIn{

    @HttpPost
    global static String doPost(VisitWraper vp,String visitid) {
       Visit__c vst = [select id,Purpose_of_Visit__c,Remarks__c,JSW_Shop_Board_Condition__c,JSW_Bag_Visibility__c,Stock_level_JSW__c,
                       Payment_Amount_Collected_by_SO__c,Pending_Payment_Amount_Committed_Date__c,Any_image_to_be_captured__c,
                       If_Potential_Lead_Share_with_Manager__c,Visit_by_TSO_LATF__c,Visited_Location__Latitude__s,Site_demo_type__c,
                       LATF_Name__c,Construction_Stage__c,Date_of_Inspection__c,Previous_Inspection__c,Check_In__c,Check_Out__c,
                       Godown_stock_MT_for_CHD__c,Godown_stock_MT_for_composite_Cement__c,Godown_stock_MT_for_OPC__c,Product__c,
                       Godown_stock_MT_for_PSC__c,Godown_Stock_on_Month_end_MT_for_CHD__c,Godown_Stock_as_on_Month_end_MT_for_CC__c,
                       Godown_Stock_as_on_Month_end_MT_for_PSC__c,Godown_Stock_as_on_Month_end_MT_for_OPC__c,Damaged_Cement_MT_for_CC__c,
                       Damaged_Cement_MT_for_CHD__c,Damaged_Cement_MT_for_OPC__c,Damaged_Cement_MT_for_PSC__c,Damage_Stock_Ageing_for_CC__c,
                       Damage_Stock_Ageing_for_CHD__c,Damage_Stock_Ageing_for_OPC__c,Activity_Type__c,Visited_Location__Longitude__s,
                       Damage_Stock_Ageing_for_PSC__c,Good_Stock_Ageing_for_CC__c,Good_Stock_Ageing_for_CHD__c,Activity_Sub_Type__c,
                       Good_Stock_Ageing_for_OPC__c,Good_Stock_Ageing_for_PSC__c,Condition_of_Godown__c,Seggregation_of_good_damaged_cement__c,
                       Stacking_pattern_As_per_ISP__c,F_I_F_O_movement__c,Offline_App_CheckIn__c from Visit__c where id =: visitid];
       vst.Purpose_of_Visit__c = vp.purposeofvisit;
       vst.Remarks__c = vp.visitdetails;
       vst.JSW_Shop_Board_Condition__c = vp.JSWShopBoardCondition;
       vst.JSW_Bag_Visibility__c = vp.JSWBagVisibility;
       vst.Stock_level_JSW__c = vp.StocklevelJSW;
       vst.Payment_Amount_Collected_by_SO__c = vp.PaymentAmountCollectedbySO;
       vst.Pending_Payment_Amount_Committed_Date__c = vp.PendingPaymentAmountCommittedDate;
       vst.Any_image_to_be_captured__c = vp.Anyimagetobecaptured;
       vst.If_Potential_Lead_Share_with_Manager__c = vp.potentiallead;
       vst.Visit_by_TSO_LATF__c = vp.visitby;
       vst.LATF_Name__c = vp.latfname;
       vst.Activity_Type__c = vp.ActType;
       vst.Activity_Sub_Type__c = vp.ActSType;
       vst.Site_demo_type__c = vp.sdemotype;
       vst.Construction_Stage__c = vp.constage;
       vst.Date_of_Inspection__c = vp.dofinsp;
       vst.Previous_Inspection__c = vp.prvinsp;
       vst.Product__c = vp.prodtype;
       vst.Godown_stock_MT_for_CHD__c = vp.GDSTKforCHD;
       vst.Godown_stock_MT_for_composite_Cement__c = vp.GDSTKforCC;
       vst.Godown_stock_MT_for_OPC__c = vp.GDSTKforOPC;
       vst.Godown_stock_MT_for_PSC__c = vp.GDSTKforPSC;
       vst.Godown_Stock_on_Month_end_MT_for_CHD__c = vp.GDMTforCHD;
       vst.Godown_Stock_as_on_Month_end_MT_for_CC__c = vp.GDMTforCC;
       vst.Godown_Stock_as_on_Month_end_MT_for_PSC__c = vp.GDMTforPSC;
       vst.Godown_Stock_as_on_Month_end_MT_for_OPC__c = vp.GDMTforOPC;
       vst.Damaged_Cement_MT_for_CC__c = vp.DCMTforCC;
       vst.Damaged_Cement_MT_for_CHD__c = vp.DCMTforCHD;
       vst.Damaged_Cement_MT_for_OPC__c = vp.DCMTforOPC;
       vst.Damaged_Cement_MT_for_PSC__c = vp.DCMTforPSC;
       vst.Damage_Stock_Ageing_for_CC__c = vp.DSAforCC;
       vst.Damage_Stock_Ageing_for_CHD__c = vp.DSAforCHD;
       vst.Damage_Stock_Ageing_for_OPC__c = vp.DSAforOPC;
       vst.Damage_Stock_Ageing_for_PSC__c = vp.DSAforPSC;
       vst.Good_Stock_Ageing_for_CC__c = vp.GSAforCC;
       vst.Good_Stock_Ageing_for_CHD__c = vp.GSAforCHD;
       vst.Good_Stock_Ageing_for_OPC__c = vp.GSAforOPC;
       vst.Good_Stock_Ageing_for_PSC__c = vp.GSAforPSC;
       vst.Condition_of_Godown__c = vp.godowncondition;
       vst.Seggregation_of_good_damaged_cement__c = vp.segg;
       vst.Stacking_pattern_As_per_ISP__c = vp.stackpattern;
       vst.F_I_F_O_movement__c = vp.fifo;
       vst.Check_In__c = vp.checkin;
       vst.Check_Out__c = vp.checkout;
       vst.Visited_Location__Latitude__s = vp.lat;
       vst.Visited_Location__Longitude__s = vp.lon;
       vst.Offline_App_CheckIn__c = true;
       update vst;
       return vst.id;
    }
       
    global class VisitWraper {
       String purposeofvisit {get; set;}
       String visitdetails {get; set;}
       String JSWShopBoardCondition{get; set;}
       String JSWBagVisibility{get; set;}
       Double StocklevelJSW{get; set;}
       Double PaymentAmountCollectedbySO{get; set;}
       Date PendingPaymentAmountCommittedDate{get; set;}
       String Anyimagetobecaptured{get; set;}
       String checkin {get; set;}
       String checkout {get; set;}
       Double lat {get; set;}
       Double lon {get; set;}
       global Boolean potentiallead {get; set;}
       String visitby {get; set;}
       String latfname {get; set;}
       String ActType {get; set;}
       String ActSType {get; set;}
       String sdemotype {get; set;}
       String constage {get; set;}
       Date dofinsp {get; set;}
       Date prvinsp {get; set;}
       String prodtype {get; set;}
       Double GDSTKforPSC {get; set;}
       Double GDSTKforOPC {get; set;}
       Double GDSTKforCC {get; set;}
       Double GDSTKforCHD {get; set;}
       Double GDMTforPSC {get; set;}
       Double GDMTforOPC {get; set;}
       Double GDMTforCC {get; set;}
       Double GDMTforCHD {get; set;}
       Double DCMTforPSC {get; set;}
       Double DCMTforOPC {get; set;}
       Double DCMTforCC {get; set;}
       Double DCMTforCHD {get; set;}
       Date DSAforPSC {get; set;}
       Date DSAforOPC {get; set;}
       Date DSAforCC {get; set;}
       Date DSAforCHD {get; set;}
       Date GSAforPSC {get; set;}
       Date GSAforOPC {get; set;}
       Date GSAforCC {get; set;}
       Date GSAforCHD {get; set;}
       String godowncondition {get; set;}
       String segg {get; set;}
       String stackpattern {get; set;}
       String fifo {get; set;}
    }
}